### ISSUE TITLE
Add AWS NeuronSDK / AWS Inferentia as a new optimizer

### ISSUE THREAD

**Issue by samir-souza** [huggingface/optimum#102]
AWS Inferentia is a chip created to accelerate ML Models. NeuronSDK, the compiler/optimizer, supports hugging face transformers. So, this could be included in the list of the supported optimizers: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/
If you need help to evaluate the tool, just ping me and I can connect you to the service team.

**Comment by sinking-point** [comment]
Also neuronx, which is for the newer inf2/trn1. Unlike inf1, these are well suited to generative transformers.

**Comment by fxmarty** [comment]
https://github.com/huggingface/optimum-neuron is probably what you are looking for!

See as well: https://huggingface.co/docs/optimum-neuron/index
