### ISSUE TITLE
Trying to convert bigcode/starcoder to onnx returns an error

### ISSUE THREAD

**Issue by matbee-eth** [huggingface/optimum#1039]
### System Info

```shell
KeyError: "gpt-bigcode is not supported yet. Only {'squeezebert', 'detr', 'xlm-roberta', 'wavlm', 'wav2vec2', 'groupvit', 'splinter', 'poolformer', 'flaubert', 'convnext', 'bert', 'deit', 'yolos', 'convbert', 'ibert', 'nystromformer', 'sew', 'speech-to-text', 'marian', 'electra', 'donut-swin', 'data2vec-vision', 'deberta', 'longt5', 'blenderbot-small', 'albert', 'gptj', 'audio-spectrogram-transformer', 'camembert', 'segformer', 'gpt2', 'data2vec-text', 'blenderbot', 'gpt-neo', 'roberta', 'opt', 'unispeech-sat', 'whisper', 'codegen', 'regnet', 'imagegpt', 'sew-d', 'layoutlmv3', 'resnet', 'mpnet', 'llama', 'm2m-100', 'mt5', 'hubert', 'beit', 'distilbert', 'wav2vec2-conformer', 'gpt-neox', 'perceiver', 'vision-encoder-decoder', 'mobilevit', 'levit', 't5', 'roformer', 'vit', 'deberta-v2', 'layoutlm', 'clip', 'unispeech', 'swin', 'bart', 'mobilenet-v1', 'pegasus', 'mobilebert', 'data2vec-audio', 'mbart', 'xlm', 'mobilenet-v2', 'bloom'} are supported. If you want to support gpt-bigcode please propose a PR or open up an issue."
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

optimum-cli export onnx --model bigcode/starcoder starcoder2

### Expected behavior

conversion

**Comment by JingyaHuang** [comment]
Hi @matbee-eth, we will add the support of starcoder for ONNX/ORT in Optimum. You can track its progress here: #1042.

**Comment by matbee-eth** [comment]
Are there any guides on adding support?

**Comment by matbee-eth** [comment]
> Hi @matbee-eth, we will add the support of starcoder for ONNX/ORT in Optimum. You can track its progress here: #1042.

Does h5/optimum have a bounty system? Would love to contribute for these kinds of tasks.

**Comment by JingyaHuang** [comment]
Finished by #1042
