### ISSUE TITLE
Make torchvision optional?

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/optimum#1046]
### Feature request

Currently torchvision is a required dependency

https://github.com/huggingface/optimum/blob/22e4fd6de3ac5e7780571570f962947bd8777fd4/setup.py#L20

### Motivation

I only work on text so I don't need vision support

### Your contribution

I am sure the change would be more difficult than just "remove the line from the setup.py" file but if you have other suggestions how to tackle the removal, I am happy to help.

**Comment by JingyaHuang** [comment]
I think we can move `torchvision` from `REQUIRED_PKGS` to `TESTS_REQUIRE` as we did for diffusers, WDYT? Are there any constraints from our subpackages? @regisss @michaelbenayoun @echarlaix

**Comment by JingyaHuang** [comment]
Just checked, should also be ok for the neuron side, `torchvision` is installed explicitly for tests. Not seems to break for intel either. 

@BramVanroy Would you like to submit a PR for it?
