### ISSUE TITLE
Support for Pix2Struct

### ISSUE THREAD

**Issue by andyPhysics** [huggingface/optimum#1054]
### Feature request

Currently, Pix2Struct is not supported by this package. 

### Motivation

Testing the capabilities of pix2struct-docvqa-large and running into long inference times. 

### Your contribution

By testing an ensuring that the method is faster and more efficient for this model

**Comment by fxmarty** [comment]
Hi @andyPhysics , there is an open PR for it here: https://github.com/huggingface/optimum/pull/1034

**Comment by fxmarty** [comment]
ONNX pix2struct is now supported on the main branch.
