### ISSUE TITLE
mpt model support?

### ISSUE THREAD

**Issue by sail1369** [huggingface/optimum#1061]
### Feature request

Can you please add mpt model support to this library?

### Motivation

just testing things, and mpt seems to be unsupported by multiple huggingface libraries

### Your contribution

im just getting started, im not sure if ill be of any help

**Comment by regisss** [comment]
Hi @sail1369! We will have to wait for MPT to be integrated to Transformers first. And then it would be possible to work on it.
More specifically, what are you interested in? ONNX export for MPT?

**Comment by sail1369** [comment]
> Hi @sail1369! We will have to wait for MPT to be integrated to Transformers first. And then it would be possible to work on it. More specifically, what are you interested in? ONNX export for MPT?

The model inference is quite slow even on a 3090, and I was also trying out multigpu to see how that would make any difference

**Comment by zacharyblank** [comment]
Has there been any movement on this? Mosaic includes converter from HF to ONNX (https://github.com/mosaicml/llm-foundry/blob/main/scripts/inference/convert_hf_to_onnx.py) but I cannot get the exported model to load with Optimum.

**Comment by fxmarty** [comment]
hi @zacharyblank , for native support we will need to have https://github.com/huggingface/transformers/pull/24629 merged first.

I could extend the work in https://github.com/huggingface/optimum/pull/1143 to allow arbitrary model type support when a custom ONNX config is passed.

**Comment by zacharyblank** [comment]
@fxmarty any idea on timing? I'm blocked by this and am incredibly grateful for the attention.

Thank you!

**Comment by fxmarty** [comment]
@zacharyblank In the coming days! An idea could be to upload custom ONNX configs as well to those models repo that have custom code.

**Comment by zacharyblank** [comment]
@fxmarty not sure I follow your suggestion. I tried creating a custom onnx config following these docs: https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/contribute but still ran into issues around MPT not being supported or text-generation-with-past not being an available task.

Maybe you're suggesting something else?
