### ISSUE TITLE
llama-7b inference report Failed to allocate memory for requested buffer of size 180355072

### ISSUE THREAD

**Issue by drxmy** [huggingface/optimum#1069]
### System Info

```shell
optimum 1.8.5, 32g v100
```

### Who can help?

@JingyaHuang

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
model_id = "my finetund llama-7b"
tokenizer = LlamaTokenizer.from_pretrained(model_id)
model = ORTModelForCausalLM.from_pretrained(model_id, export=True)

# Load the optimization configuration detailing the optimization we wish to apply
optimization_config = AutoOptimizationConfig.O3(for_gpu=True)
optimizer = ORTOptimizer.from_pretrained(model)
optimizer.optimize(save_dir=save_dir, optimization_config=optimization_config)

model = ORTModelForCausalLM.from_pretrained(save_dir,provider="CUDAExecutionProvider")
```

### Expected behavior

Successfully loaded and ready for generation. 
But it gives 
```
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: 
/onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:368 void* 
onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, 
onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 180355072
```
I guess this is actually OOM? It seems that fp16 onnx conversion has some issue. But with fp32, two llama-7b model(normal and with_past) is too big for a single card. Is there any solution for this? i don'y see any multi-gpu inference in optimum's doc.

`model = ORTModelForCausalLM.from_pretrained(model_id, export=True)`
I think this model is fp32? Is there a way to make this model fp16? Then maybe I don't need onnx to convert to fp16.

Thank you!

**Comment by fxmarty** [comment]
When is the OOM occuring?

@drxmy Could you give a try to:

```
optimum-cli export onnx --model my-finetund-llama-7b --optimize O3 --task text-generation-with-past llama_7b_onnx
```

and then

```python
from optimum.onnxruntime import ORTModelForCausalLM

model = ORTModelForCausalLM.from_pretrained("llama_7b_onnx")
```

**Comment by drxmy** [comment]
> 
It occurs when i call model.generate.

I try you commend, it gives
```
Exception: An error occured during validation, but the model was saved nonetheless at llama_7b_onnx.
Detailed error: [ONNXRuntimeError] : 1 : FAIL : Load model from
llama_7b_onnx/decoder_model_merged.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:145
onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const
IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const
onnxruntime::ModelOptions&) Unsupported model IR version: 9, max supported IR version: 8

```
Maybe because i update onnxruntime to 1.15? Because last week i saw in this issue (https://github.com/huggingface/optimum/issues/901 )which says onnxruntime 1.15 may fix the fp16 convertion problem.

**Comment by drxmy** [comment]
> @drxmy Could you check the version of the `onnx` Python package in your environment with `pip show onnx` please? It looks like you have version 1.14. If yes, downgrade it to 1.13 with `pip install "onnx<1.14.0"` and let us know if you still have the same error.

I downgraded onnx to 1.131 and the command successed, the conversion and loading. But i want to do inference with gpu. 
Maybe i should try the newest optimum? I saw this pr(https://github.com/huggingface/optimum/pull/1079) has been merged

**Comment by regisss** [comment]
@drxmy Sure, you can have the latest changes installing Optimum with:
```bash
pip install git+https://github.com/huggingface/optimum.git
```

You will just have to make sure that ONNX 1.14 is not installed.

**Comment by fxmarty** [comment]
Hi @drxmy , I am quite sure `model = ORTModelForCausalLM.from_pretrained(model_id, export=True)` by default exports as fp32 even if  `"torch_dtype": "float16"` is specified in the model config.json. This is on par with transformers that loads by default in fp32 unless the user specifies `torch_dtype="auto"` or `torch_dtype=torch.float16`.

Thus, if you'd like to export directly in fp16, you need to first use the command line:

```
optimum-cli export onnx --model my-finetund-llama-7b --device cuda --fp16 --task text-generation-with-past llama_7b_onnx
```

I recommend you to use pytorch nightly that includes some critical bug fixes https://github.com/pytorch/pytorch/pull/101134 & https://github.com/pytorch/pytorch/pull/101148 in the memory allocation of `torch.onnx.export`. I recommend as well to use optimum main branch that includes fixes in the memory use of the export (https://github.com/huggingface/optimum/pull/1115 https://github.com/huggingface/optimum/pull/1112 https://github.com/huggingface/optimum/pull/1111), before we do a release soon.

Then, once the model is exported, you can load the local ONNX model directly: https://huggingface.co/docs/optimum/main/en/onnxruntime/package_reference/modeling_ort#optimum.onnxruntime.ORTModel.from_pretrained

Feel free to reopen if you still hit any issue.
