### ISSUE TITLE
ValueError: ..set the option `trust_remote_code=True` to remove this error

### ISSUE THREAD

**Issue by diptenduLF** [huggingface/optimum#1134]
### System Info

```shell
- `optimum` version: 1.8.8
- `transformers` version: 4.30.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.3
- Huggingface_hub version: 0.15.1
- PyTorch version (GPU?): 2.0.1+cpu (cuda availabe: False)
- Tensorflow version (GPU?): not installed (cuda availabe: NA)
```

### Who can help?

Hello,

I am running the optimum cli command 

`optimum-cli export onnx --model mosaicml/mpt-7b-chat --task text-generation  mpt-7b-chat\`

when I am getting this error:

```
File "C:\Users\dutta\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dynamic_module_utils.py", line 553, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading mosaicml/mpt-7b-chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

How to deal with this error?  @michaelbenayoun

Thanks

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the same command replacing the output directory name to a name of your choice

### Expected behavior

I expect the command to run without error and product the ONNX model and other files in the output directory

**Comment by fxmarty** [comment]
Hi, you can try `optimum-cli export onnx --help`, where the option `--trust-remote-code` is available. However, `mpt` is not an architecture officially supported in the ONNX export, as it is not available in transformers yet (see: https://github.com/huggingface/transformers/issues/23174).

One possibility would be to add an argument to the ONNX export that would allow to "mimic" an ONNX config (e.g. use gpt-neo ONNX config for MPT), although there is no guarantee that this will work. Would that help?

**Comment by aunwesha** [comment]
Thanks for your offer to add an argument to ONNX export. However, as you have mentioned, it might not work. So  shall wait for the feature request to be addressed.

Meanwhile, some folks have provided the ONNX model for gpt-j-6B-int8-static
https://huggingface.co/Intel/gpt-j-6B-int8-static/tree/main

I am working in Java. Can you give me some pointers as to how to handle the required tokenization for this model in Java?

**Comment by xenova** [comment]
> Maybe @xenova you have some idea? 

I recently added support for tokenization for mpt models to transformers.js, so if OP wants to re-implement it, feel free to use Transformers.js as inspiration. mpt-7b uses a Byte-Level BPE tokenizer, which is quite a popular approach, so you can probably find some Java implementation out there already.

**Comment by fxmarty** [comment]
@diptenduLF Fixed in https://github.com/huggingface/optimum/pull/1166, feel free to refer to https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models for the usage!
