### ISSUE TITLE
Unpin onnx version to allow using v1.14

### ISSUE THREAD

**Issue by cody-moveworks** [huggingface/optimum#1140]
### Feature request

Remove the version constraint on onnx package to allow using onnx==1.14.

### Motivation

- The latest version of onnxruntime (v1.15 at the time of writing) supports onnx==1.14.
- onnx==1.14 introduces support for protobuf v4, which is also useful.

### Your contribution

Seems removing the pin from setup.py would be all that is needed as long as the existing tests provide enough validation.

**Comment by regisss** [comment]
Sounds good to me @cody-moveworks ! Would you like to open a PR with this change?

**Comment by cody-moveworks** [comment]
@regisss I'll try to put up a PR with this change.
