### ISSUE TITLE
 BetterTransforer not Support Marian

### ISSUE THREAD

**Issue by Dhaizei** [huggingface/optimum#1142]
### System Info

```shell
model_name = "Helsinki-NLP/opus-mt-en-zh"
model_hf = AutoModelForSeq2SeqLM.from_pretrained(model_name)
model = BetterTransformer.transform(model_hf, keep_original_model=True)

ValueError: Activation function swish not supported for `BetterTransformer` integration.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

model_name = "Helsinki-NLP/opus-mt-en-zh"
model_hf = AutoModelForSeq2SeqLM.from_pretrained(model_name)
model = BetterTransformer.transform(model_hf, keep_original_model=True)

### Expected behavior

ValueError: Activation function swish not supported for `BetterTransformer` integration.

**Comment by fxmarty** [comment]
Hi, for reference we are upstreaming SDPA in Transformers https://github.com/huggingface/transformers/issues/28005
