### ISSUE TITLE
ORTModelForCausalLM - ONNX - Merge model fails to run

### ISSUE THREAD

**Issue by claeyzre** [huggingface/optimum#1150]
### System Info

```shell
System: Windows 11
Optimum Version: 1.9 (tried in 1.8.x as well and didn't work)
Onnxruntime Version: 1.15.1 (tried in 1.13.x as well and didn't work)
Onnx Version: 1.13.1
Pytorch Version:2.0.0 (tried in 1.X as well and didn't work)
```

### Who can help?

@fxmarty as I saw you working a lot of these kind of models in the previous issues

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have an onnx error while trying to execute this small script
```
text = "I want my money and"
model_id = "hf-internal-testing/tiny-random-BloomForCausalLM"
tokenizer = AutoTokenizer.from_pretrained(model_id)

model = ORTModelForCausalLM.from_pretrained(model_id, from_transformers=True, use_merged=True)
input_ids = tokenizer(text, return_tensors="pt").input_ids
results_hf = model.generate(inputs=input_ids,
                            num_beams=2,
                            do_sample=False,
```

I have the following onnx error
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running If node. Name:'optimum::if' Status Message: Non-zero status code returned while running Concat node. Name:'/transformer/h.0/self_attention/Concat_4' Status Message: concat.cc:159 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 8 and 2
```

Note that this error arises with num_beams = 2 but not with num_beams=1 so this occurs only when the decoder takes a "batched" input.

### Expected behavior

The generation runs smoothly

**Comment by fxmarty** [comment]
Thank you! Interestingly I can reproduce the issue on bloom but not gpt2 / gpt-neo archs. But indeed the CI tests only `num_beams=1`, I'll fix for bloom and extend our tests.
