### ISSUE TITLE
`provider="CUDAExecutionProvider"` in `ORTModelForSeq2SeqLM` is not working.

### ISSUE THREAD

**Issue by soocheolnoh** [huggingface/optimum#1158]
### System Info

```shell
optimum==1.9.0
transformers==4.30.2
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have been using `ORTModelForSeq2SeqLM` to deploy the mT5 model. However, it appears that the `provider="CUDAExecutionProvider"` argument is not functioning properly at the moment.

Here is a simple script:
```python
from optimum.onnxruntime import ORTModelForSeq2SeqLM
from transformers import T5Tokenizer

if __name__ == "__main__":
    tokenizer = T5Tokenizer.from_pretrained("lewtun/tiny-random-mt5")
    model = ORTModelForSeq2SeqLM.from_pretrained(
        "lewtun/tiny-random-mt5", provider="CUDAExecutionProvider", export=True
    )

    inputs = tokenizer("I'm", return_tensors="pt")
    inputs = {k: v.to(device="cuda") for k, v in inputs.items()}
    gen_tokens = model.generate(**inputs, num_beams=2)
    outputs = tokenizer.batch_decode(gen_tokens, skip_special_tokens=True)
    print(outputs[0])
```

When I executed the above code, I received the following error:
```
Exception has occurred: RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Error in execution: Invalid rank for input: encoder_hidden_states Got: 2 Expected: 3 Please fix either the inputs or the model.

RuntimeError: Error in execution: Invalid rank for input: encoder_hidden_states Got: 2 Expected: 3 Please fix either the inputs or the model.
```

I think this part might be causing the error.

https://github.com/huggingface/optimum/blob/6162d5f7addac5f48e5db34b7737dd7950f0584d/optimum/onnxruntime/base.py#L534-L558

The order of `self._ordered_input_names` is ['input_ids', 'encoder_hidden_states', 'encoder_attention_mask'], but the order of `model_inputs` is ['input_ids', 'encoder_attention_mask', 'encoder_hidden_states'].

Simply changing it like
```python
if "encoder_hidden_states" in self.input_names:
    model_inputs.append(encoder_hidden_states)

if "encoder_attention_mask" in self.input_names:
    model_inputs.append(encoder_attention_mask)
```
seems to work, but I'm not sure if this change is appropriate or not because I don't have extensive knowledge about ONNX. Could you fix this? If my usage is incorrect, I would appreciate any suggestions. Thank you!

### Expected behavior

Everything is explained in the Reproduction section.

**Comment by fxmarty** [comment]
Thank you for the report, fixed in https://github.com/huggingface/optimum/pull/1181. We have a CI for GPU tests, but it seems it stopped running so I'll make sure it runs again!

**Comment by fxmarty** [comment]
@soocheolnoh The GPU CI runs again and I'll check it more often, this issue was indeed catched by it as well! Thank you!
