### ISSUE TITLE
Degraded predictions after conversion to ONNX

### ISSUE THREAD

**Issue by ingo-m** [huggingface/optimum#1171]
Issue previously reported on PEFT repo: https://github.com/huggingface/peft/issues/670

### System Info

- Platform: Google Colab with T4 GPU
- Python version: 3.10
- Library versions:
  ```  
  accelerate                       0.20.3
  exporters                        0.7.0
  onnx                             1.14.0
  onnxconverter-common             1.13.0
  onnxruntime                      1.15.1
  onnxruntime-tools                1.7.0
  optimum                          1.9.1.dev0
  peft                             0.3.0
  torch                            2.0.1+cu118
  transformers                     4.30.2
  ```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm trying to export a PEFT / LoRA model to ONNX. The base model is `bigscience/bloom-560m`.

I merge the LoRA weights into the base model after finetuning, and then try to convert the resulting merged model to ONNX. When I'm using `optimum.onnxruntime.ORTModelForCausalLM`, the export works, and I can run inference with the ONNX model, but the model outputs are degraded.

Alternatively, using the lower-level `torch.onnx.export()` approach, I get an error.

Here's a reproducible example showing both approaches (`optimum.onnxruntime.ORTModelForCausalLM` and `torch.onnx.export()`): https://colab.research.google.com/drive/1ImNLTJ11JBeaSn-76eAejf5Pjk0ahPTY?usp=sharing

(The colab example can run on a free T4 instance.)

### Expected behavior

I expect the model outputs to be similar before & after conversion to ONNX (apart from small differences due to numerical precision). In the minimal example I shared, the difference might look small (nonsensical output either way). But in a real-life use case (involving finetuning) a model that performs very well on a given task has completely degraded performance after ONNX conversion. I also observed this with a larger model (`bigscience/bloom-3b`), but that doesn't run in free tier google colab.

**Comment by ingo-m** [comment]
Possibly related?
- https://github.com/huggingface/optimum/issues/1150
- https://github.com/huggingface/optimum/issues/720
- https://github.com/huggingface/optimum/issues/692
- https://github.com/huggingface/optimum/pull/647#discussion_r1106123673

**Comment by ingo-m** [comment]
Sorry I had overlooked something in my original bug report:

This issue is not specific to PEFT / LoRA models.

Here's a minimal example where a vanilla-flavor "bigscience/bloom-560m" model, without any modifications, generates degraded predictions after conversion to ONNX with `ORTModelForCausalLM.from_pretrained()`: https://colab.research.google.com/drive/1XF2jy0WGHgqxQjfOH01t8Grof0SAfgJ-?usp=sharing

**Comment by ingo-m** [comment]
@fxmarty thanks a lot, and sorry for the erroneous bug report. I didn't know that I could use the `generate()` method on the ORT model. I can confirm that using the `generate()` method, float32 datatype, on GPU, for both the pytorch and the ONNX model, I get consistent results. ✅

For future reference / in case anyone else is interested, I tried to replicate the fixed version (using GPU) in a colab notebook, but unfortunately that doesn't work because of conflicting onnxruntime dependencies. Anyway, it does work on a regular GPU VM using pipenv for dependencies. https://colab.research.google.com/drive/1jutl6zhxhc3KfpHfcR0AuyOzi4U3FCzZ?usp=sharing

Just out of curiosity, is it possible to convert a bfloat16 pytorch transformer model to a bfloat16 ONNX model for inference on GPU? Would a performance improvement be expected?

**Comment by fxmarty** [comment]
@ingo-m No worries, always good for us to double-check! There's an example here in the doc, but it's true it is a bit hidden: https://huggingface.co/docs/optimum/main/en/onnxruntime/package_reference/modeling_ort#optimum.onnxruntime.ORTModelForCausalLM.forward.example. I'll add an example in https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/models.

I have not tried to export models as bfloat16, the optimum export CLI (`optimum-cli export onnx --help`) only supports an `--fp16` option. But at least some ONNX operators support bfloat16: https://github.com/onnx/onnx/blob/main/docs/Operators.md#matmul & similarly, ORT has some support: https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md

However, ORT support seems to be (for some reason) only in the C/C++/C# API https://github.com/microsoft/onnxruntime/issues/13001#issuecomment-1315752206
