### ISSUE TITLE
Add support for Falcon model to export to ONNX

### ISSUE THREAD

**Issue by mindest** [huggingface/optimum#1172]
### Feature request

Add support so that we can export Falcon model to ONNX format using `optimum-cli`, like

    optimum-cli export onnx -m tiiuae/falcon-7b falcon_7b --trust-remote-code

### Motivation

Wanted to run Falcon model using ONNXRuntime. Currently error will be raised when exporting Falcon model to ONNX, using the above command:
`KeyError: "refinedwebmodel is not supported yet. Only {'electra', 'mt5', ...} are supported. If you want to support refinedwebmodel please propose a PR or open up an issue."`

### Your contribution

Support may be dependent on updates in transformers, like huggingface/transformers#24523.

**Comment by Johnno1011** [comment]
Yo, just curious, why do we have to wait for a proper release (IE: pip etc) before this can be resolved? I was able to build from source and it works just fine.
Thanks.

**Comment by fxmarty** [comment]
Our CI relies on transformers latest release.

**Comment by Pradipve2011** [comment]
> 

Hey John,

I am looking for solution on this. Can you please share how do you able to convert it?

**Comment by WilliamTambellini** [comment]
up

**Comment by fxmarty** [comment]
Hi, the support is added in https://github.com/huggingface/optimum/pull/1391
