### ISSUE TITLE
BetterTransformer support for BLOOM

### ISSUE THREAD

**Issue by Hukongtao** [huggingface/optimum#1175]
### Feature request

Can you please consider adding BetterTransformer support for BLOOM?

Thanks

### Motivation

Definitely this support will be of great help for people working with BLOOM.

### Your contribution

model = AutoModelForCausalLM.from_pretrained(hugg_path)      
model = BetterTransformer.transform(model)

**Comment by fxmarty** [comment]
Hi @Hukongtao, this is done with #1221.
