### ISSUE TITLE
Running optimum/examples/onnxruntime/training/language-modeling fails

### ISSUE THREAD

**Issue by pks** [huggingface/optimum#1184]
### System Info

```shell
> pip freeze | grep -P "(optimum|transformers|onnxruntime|deepspeed)"
deepspeed==0.9.5
onnxruntime==1.15.1
onnxruntime-gpu==1.15.1
onnxruntime-training==1.15.1
optimum==1.9.1
transformers==4.30.2
> python --version
Python 3.9.16
```

I also tried the latest version from github for `transformers` and `optimum`, resulting in the exact same error.

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install optimum and other dependencies (I also noted that `pytest` is missing from the `requirements.txt` file.
2. Run:
```
torchrun --nproc_per_node=4 run_clm.py \
    --model_name_or_path gpt2 \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --do_train \
    --output_dir test-clm \
    --fp16
```
3. Observe stacktrace:
```
Traceback (most recent call last):
  File "[redacted]/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 593, in <module>
    main()
  File "[redacted]/optimum/examples/onnxruntime/training/language-modeling/run_clm.py", line 519, in main
    trainer = ORTTrainer(
  File "[redacted]/venv/lib/python3.9/site-packages/optimum/onnxruntime/trainer.py", line 304, in __init__
    super().__init__(
  File "[redacted]/venv/lib/python3.9/site-packages/transformers/trainer.py", line 336, in __init__
    self.create_accelerator_and_postprocess()
  File "[redacted]/venv/lib/python3.9/site-packages/transformers/trainer.py", line 3842, in create_accelerator_and_postprocess
    deepspeed_plugin=self.args.deepspeed_plugin, gradient_accumulation_plugin=gradient_accumulation_plugin
AttributeError: 'ORTTrainingArguments' object has no attribute 'deepspeed_plugin'
```

### Expected behavior

I'd expect to train a language model from scratch using `onnxruntime-training`.

**Comment by JingyaHuang** [comment]
Hi @pks, the issue you encountered is the same as #1133. Currently the `ORTTrainer` needs to be updated to the lastest transformers version. I will open a PR to fix this, meanwhile you can try to downgrade your transformers version.
