### ISSUE TITLE
Cuda Executions showed better results than Tensorrt of Onnx model of FlanT5-large

### ISSUE THREAD

**Issue by AparnaAgrawal02** [huggingface/optimum#1185]
### System Info

```shell
1. Name: optimum  Version: 1.9.1.dev0   
2. Name: torch  Version: 2.0.1+cu118  
3. Name: transformers Version: 4.29.2
4. Name: protobuf Version: 4.23.1

System
Ubuntu 20.04.5 LTS \n \l  
GPU 0: NVIDIA GeForce GTX 1080 Ti   

nvcc: NVIDIA (R) Cuda compiler driver  
Copyright (c) 2005-2021 NVIDIA Corporation  
Built on Mon_Sep_13_19:13:29_PDT_2021  
Cuda compilation tools, release 11.5, V11.5.50  
Build cuda_11.5.r11.5/compiler.30411180_0  
Python 3.9.16  
ii  cudnn-local-repo-ubuntu2004-8.3.2.44                        1.0-1                                      amd64        cudnn-local repository configuration files  
ii  libcudnn8                                                   8.3.2.44-1+cuda11.5                        amd64        cuDNN runtime libraries  
ii  libcudnn8-dev                                               8.3.2.44-1+cuda11.5                        amd64        cuDNN development libraries and headers  
ii  libcudnn8-samples                                           8.3.2.44-1+cuda11.5                        amd64        cuDNN samples
```

### Who can help?

@JingyaHuang, @echarlaix

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I used https://github.com/AparnaAgrawal02/Flan-T5-inference-optimisation/blob/main/onnx_tensorrt_optimum.ipynb code to compare onnx model of Flant5 in cuda and Tensorrt execution.

output MAX len → 5
For FlanT5 large: onnx - Cuda

seq_len:  8 time:  0.0640825286056056
seq_len: 32 time:  0.06121446869590066   
seq_len: 128 time: 0.0765363568007344
seq_len: 512 time: 0.12337033435551807
seq_len: 1024 time: 0.22687000939340302 
ONNX + Tensorrt
output MAX len → 5
For FlanT5 large: onnx - tensorRt 

seq_len:  8 time:   0.06368    
seq_len: 32 time:  0.07280   
seq_len: 128 time: 0.1131  
seq_len: 512 time:  0.2668  
seq_len: 1024 time: 0.4750   

But tensorrt should work better right? 
more detailed results : https://understood-casquette-cdf.notion.site/results-94e3e9f59e9d4fa8926ee13755bc2c88?pvs=4

### Expected behavior

Tensorrt should work better than CUDA

**Comment by fxmarty** [comment]
Hi @AparnaAgrawal02, have you tried doing warmup first for the model using TRT Provider?

**Comment by AparnaAgrawal02** [comment]
Hi @fxmarty  
code i used :
  `from transformers import AutoTokenizer, pipeline
from optimum.onnxruntime import ORTModelForSeq2SeqLM
import numpy as np 
import onnx

model_name = "google/flan-t5-large"
model = ORTModelForSeq2SeqLM.from_pretrained(model_name,export =True, provider="TensorrtExecutionProvider")

export_dir='/home/meeami/aparna/onnx_model/'
model.save_pretrained(export_dir)
tokenizer = AutoTokenizer.from_pretrained(model_name)

text = "He never went out without a book under his arm, and he often came back with two."
#result = onnx_translation(text,max_length=520)
[{'translation_text': "Il n'est jamais sorti sans un livre sous son bras, et il est souvent revenu avec deux."}]
print(model.providers)
import tqdm
import time
seq_len = [ 512,1048]
for i in range(4):
    start = time.time()
    for j in tqdm.tqdm(range(100)):
        start1  = time.time()
        input_text =  "house "* seq_len[i]
        input = tokenizer(input_text, return_tensors='pt').input_ids.cuda()

        outputs =model.generate(input, max_length=5)

        result = tokenizer.decode(outputs[0], skip_special_tokens=True)
        end1= time.time()
        print(end1-start1)
    print("For Flan-T5 large: onnx:")
    end = time.time()
    print("seq_len: ", seq_len[i], "time: ", (end - start)/100)`


can you let me know how to use TRT Provider?

**Comment by fxmarty** [comment]
Hi, you can refer to: https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/gpu#tensorrt-engine-build-and-warmup. We don't actively support TRT execution provider for now, but welcome PRs that would improve its support.
