### ISSUE TITLE
Separate CLIP image & text models

### ISSUE THREAD

**Issue by josephrocca** [huggingface/optimum#1186]
### Feature request

I was informed in [this Transformer.js issue](https://github.com/xenova/transformers.js/issues/148#issuecomment-1593077177) by @xenova that there's possibly a limitation of Optimum that prevents the separation of the image and text CLIP models.

I'm not exactly sure what's going on here, but it was suggested that I create an issue for this.

### Motivation

I'd like to use the CLIP image model separately as a feature extractor via Transformers.js - i.e. just turning an image into an embedding vector. I've done this [outside of](https://github.com/josephrocca/openai-clip-js) Transformers.js, but would like to try standardizing my processes around Transformers.js if possible.

### Your contribution

I'm probably not going to be very useful here, unfortunately.

**Comment by xenova** [comment]
This might actually now be possible with the new custom configuration options (cc @fxmarty? 👀). If so, would it be possible for you to give some example code to get this working?

**Comment by regisss** [comment]
If I understood correctly, you would like to export [CLIPTextModelWithProjection](https://github.com/huggingface/transformers/blob/91d7df58b6537d385e90578dac40204cb550f706/src/transformers/models/clip/modeling_clip.py#L1181C7-L1181C34) and [CLIPVisionModelWithProjection](https://github.com/huggingface/transformers/blob/91d7df58b6537d385e90578dac40204cb550f706/src/transformers/models/clip/modeling_clip.py#L1262) models right?

**Comment by josephrocca** [comment]
Hey @regisss, yep I'm pretty sure that's correct (although @xenova might have to confirm this just to be sure).

**Comment by xenova** [comment]
Yep that looks right! 👍 Just a follow-up question, how do those models tie into the `AutoModelForXXX` paradigm (or are they their own things, basically just feature-extraction models?). Either way, if we can export them separately... it will be HUGE 🤯

**Comment by regisss** [comment]
This is non-trivial as the model type `clip_text_model` can correspond to a [`CLIPTextTransformer`](https://github.com/huggingface/transformers/blob/50726f9ea7afc6113da617f8f4ca1ab264a5e28a/src/transformers/models/clip/modeling_clip.py#L695) or to a [`CLIPTextModelWithProjection`](https://github.com/huggingface/transformers/blob/50726f9ea7afc6113da617f8f4ca1ab264a5e28a/src/transformers/models/clip/modeling_clip.py#L1181C7-L1181C34) (same confusion with `clip_vision_model`).
So we cannot use the CLI or [this example](https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model#customize-the-export-of-official-transformers-models) provided in the doc for custom ONNX configs.

Here is a code snippet that works for `CLIPTextModelWithProjection`:
```py
# 1. Define a custom config
from optimum.exporters.onnx.model_configs import CLIPTextOnnxConfig
from typing import Dict


class CLIPTextModelWithProjectionOnnxConfig(CLIPTextOnnxConfig):
    @property
    def outputs(self) -> Dict[str, Dict[int, str]]:
        return {
            "text_embeds": {0: "batch_size"},
            "last_hidden_state": {0: "batch_size", 1: "sequence_length"},
        }


# 2. Export to ONNX
from transformers.models.clip import CLIPTextModelWithProjection
from pathlib import Path
from optimum.exporters.onnx import export

model = CLIPTextModelWithProjection.from_pretrained("openai/clip-vit-base-patch32")

export(
    model=model,
    config=CLIPTextModelWithProjectionOnnxConfig(model.config),
    output=Path("my_clip_text_model_with_projection/model.onnx"),
    device="cpu",
)
```

**Comment by regisss** [comment]
You could do the same for `CLIPVisionModelWithProjection` but you'll have to do a couple of things:
- Add a `clip_vision_model_type` [here](https://github.com/huggingface/optimum/blob/c4750f6014d8ac39bca780e1e4381b15eaab9197/optimum/exporters/tasks.py#L389). Would any of you like to open a PR to add this to Optimum? :slightly_smiling_face: 
- Define a `CLIPVisionModelWithProjectionOnnxConfig` similarly to `CLIPTextModelWithProjectionOnnxConfig` in the code snippet above, it can probably inherit from `ViTOnnxConfig`.

**Comment by lithdew** [comment]
Inheriting from `ViTOnnxConfig` works as expected.

```python
# 1. Define a custom config

from optimum.exporters.onnx import export_models
from transformers.models.clip import CLIPTextModelWithProjection, CLIPVisionModelWithProjection
from optimum.exporters.onnx.model_configs import CLIPTextOnnxConfig, ViTOnnxConfig
from typing import Dict


class CLIPVisionOnnxConfig(ViTOnnxConfig):
    pass


class CLIPTextModelWithProjectionOnnxConfig(CLIPTextOnnxConfig):
    @property
    def outputs(self) -> Dict[str, Dict[int, str]]:
        return {
            "text_embeds": {0: "batch_size"},
        }


class CLIPVisionModelWithProjectionOnnxConfig(CLIPVisionOnnxConfig):
    @property
    def outputs(self) -> Dict[str, Dict[int, str]]:
        return {
            "image_embeds": {0: "batch_size"},
        }


# 2. Export to ONNX

text_model = CLIPTextModelWithProjection.from_pretrained(
    "openai/clip-vit-base-patch32")
vision_model = CLIPVisionModelWithProjection.from_pretrained(
    "openai/clip-vit-base-patch32")

export_models(
    models_and_onnx_configs={
        "text_model": (text_model, CLIPTextModelWithProjectionOnnxConfig(text_model.config)),
        "vision_model": (vision_model, CLIPVisionModelWithProjectionOnnxConfig(vision_model.config)),
    },
    output_dir="models",
)
```
