### ISSUE TITLE
ONNX Generation - Support for Donut

### ISSUE THREAD

**Issue by ghost** [huggingface/optimum#1191]
### Feature request

I have been trying to convert my custom Donut model to ONNX by using this specific command:
!python3 -m optimum.exporters.onnx --model={custom_model_id} --task=vision2seq-lm  ./models/onnx --optimize O4 --atol 1e-2 --opset=13

The following exception occurs at the end of the process, by which I understand the vision-encoder-decoder is not supported yet. Are there any plans to integrate  vision-encoder-decoder for optimum.exporters.onnx soon?

Error observed:

File "/usr/local/lib/python3.10/dist-packages/optimum/onnxruntime/utils.py", line 162, in check_optimization_supported_model
    raise NotImplementedError(
NotImplementedError: ONNX Runtime doesn't support the graph optimization of vision-encoder-decoder yet. Only ['albert', 'bart', 'bert', 'big_bird', 'blenderbot', 'bloom', 'camembert', 'codegen', 'deberta', 'deberta-v2', 'distilbert', 'electra', 'gpt2', 'gpt_neo', 'gpt_neox', 'gptj', 'longt5', 'llama', 'marian', 'mbart', 'mt5', 'm2m_100', 'nystromformer', 'pegasus', 'roberta', 't5', 'vit', 'whisper', 'xlm-roberta'] are supported. If you want to support vision-encoder-decoder please propose a PR or open up an issue in ONNX Runtime: https://github.com/microsoft/onnxruntime.

### Motivation

Use  optimum.exporters.onnx  to convert custom Donut model to ONNX to improve inference performance.

### Your contribution

Still looking at the links and getting familiar how to proceed with change. will be grateful if someone can point me to resources where I can get started. thanks.

**Comment by dneemuth** [comment]
The following libraries needs to be imported first:
!pip3 install onnxruntime-gpu==1.15.1 onnx transformers===4.30.1 optimum[onnxruntime-gpu]==1.9.1 evaluate datasets onnxoptimizer optimum[exporters]

**Comment by fxmarty** [comment]
Hi @dneemuth, for now you can try to remove the `--optimize O4` and it should work as expected.

**Comment by ivarflakstad** [comment]
Solution provided and github user has been deleted
