### ISSUE TITLE
Converted Vision Encoder Decoder onnx model seems like doesn't use past key values

### ISSUE THREAD

**Issue by kyle-bong** [huggingface/optimum#1192]
### System Info

optimum = 1.9.1
python = 3.10
device = cpu
OS = linux

I made a vision encoder decoder model using huggingface transformers library. And I converted the model to onnx using this code:

```python
from optimum.onnxruntime import ORTModelForVision2SeqORTQuantizer
from transformers import PreTrainedTokenizerFast
model_checkpoint = "../checkpoint"
save_directory = "../onnx/"
# Load a model from transformers and export it to ONNX
ort_model = ORTModelForVision2Seq.from_pretrained(model_checkpoint, 
                                                  export=True, 
                                                  from_transformers=True,
                                                  use_cache=True)
tokenizer = PreTrainedTokenizerFast.from_pretrained(model_checkpoint)
# Save the onnx model and tokenizer
ort_model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)
```
```
The argument `from_transformers` is deprecated, and will be removed in optimum 2.0.  Use `export` instead
Framework not specified. Using pt to export to ONNX.
Using framework PyTorch: 2.0.1+cu117
Overriding 1 configuration item(s)
	- use_cache -> False
/home/bs/anaconda3/envs/text_rec/lib/python3.8/site-packages/transformers/models/deit/modeling_deit.py:126: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_channels != self.num_channels:
/home/bs/anaconda3/envs/text_rec/lib/python3.8/site-packages/transformers/models/deit/modeling_deit.py:130: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if height != self.image_size[0] or width != self.image_size[1]:
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Using framework PyTorch: 2.0.1+cu117
Overriding 1 configuration item(s)
	- use_cache -> True
Using framework PyTorch: 2.0.1+cu117
Overriding 1 configuration item(s)
	- use_cache -> True
Asked a sequence length of 16, but a sequence length of 1 will be used with use_past == True for `decoder_input_ids`.
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
```

And I load the onnx model, and tried to inference. 
But the result was so bad. And inference time was slower than before conversion.

```python
s = time.time()
result = ort_model.generate(pixel_values, 
                            use_cache=True,
                            max_length=256)
print(time.time()-s)
result = tokenizer.batch_decode(result)
print(result)
```
This code print out weird sequence. 

I tried to write generate code manually. 
As a result, I can generate right and natural sequence what I wanted. 
But inference speed is stil slow.
I think model doesn't use `use_cache` or `past_key_values` even though I set `use_cache=True` and `use_cache_branch=True`.

```python
outputs = [2] # start token id
output = None
start = time.time()
for _ in range(256):
    # print(outputs)
    start1 = time.time()
    if output is not None:
        output = ort_model.decoder(
            input_ids=torch.tensor(outputs).unsqueeze(0),
            past_key_values = output.past_key_values,
            use_cache_branch =True,
            encoder_hidden_states=encoder_outputs,
        )
    else:
        output = ort_model.decoder(input_ids=torch.tensor(outputs).unsqueeze(0),
                            encoder_hidden_states=encoder_outputs,
                            use_cache_branch =True,
                            )
        
    next_id = int(torch.argmax(output.logits, dim=-1)[0][-1])
    if _ < 10 or _>150:
        print('#', _, time.time()-start1)

    if next_id == 3 or next_id == 0:
        outputs.append(next_id)
        break
    outputs.append(next_id)

end = time.time()

generated_text = tokenizer.decode(outputs, skip_special_tokens=False)
```

Is this a bug?
How can I fix this issue?
How can I generate sequence faster than non-onnx model?

### Who can help?

@JingyaHuang 
@echarlaix
@michaelbenayoun

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Convert transformer vision encoder decoder model to onnx model using `optimum.onnxruntime.ORTModelForVision2Seq`
2. Load the converted model and try `model.generate` to get a text. You will get weird sequence or it would be very slow.
3. If manually write generate code, you can get right sequence, but it is still slow.

### Expected behavior

- Use past key value for caching.
- faster generateion

**Comment by fxmarty** [comment]
Hi, @kyle-bong, thank you for the report! It would help if you provide a reproducible example where the ORT output does not match the pytorch one.

**Comment by kyle-bong** [comment]
> Hi, @kyle-bong, thank you for the report! It would help if you provide a reproducible example where the ORT output does not match the pytorch one.

Using this code which recommended by huggingface document, I got
```python
result = ort_model.generate(pixel_values, 
                            use_cache=True,
                            max_length=256)
```
```
S \\sigma \\sigma \\sigma \\sigmarotarrr}{{ \\dot \\pindot \\prot \\protabinomab \\sharr}{ \\eparorr}{ \\! \\, \\, \\, \\, \\; \\;;56234600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
inference time: 3.42s

The expected generation(=the generation of original model) is like this (LaTex):
```
S \sim \tilde { \psi }Q_{o} \tilde { \psi }+g_{s}^{1/2} \tilde { \psi }^{3}+ \tilde { \phi }Q_{c} \tilde { \phi }+g_{s} \tilde { \phi }^{3}+ \tilde { \phi }B(g_{s}^{1/2} \tilde { \psi })+ \cdots.
```
inference time: 1.29s

The above one, which is generated by ORT model, is currupted. 
But it is not problem of the model. Because, when I implement the generation function manually, I got
```
S \sim \tilde { \psi }Q_{o} \tilde { \psi }+g_{s}^{1/2} \tilde { \psi }^{3}+ \tilde { \phi }Q_{c} \tilde { \phi }+g_{s} \tilde { \phi }^{3}+ \tilde { \phi }B(g_{s}^{1/2} \tilde { \psi })+ \cdots.
```
inference time: 3.42s

The ORT model can generate right sequence by manually implemented generation function, but it still very slow. 
I suspect that even though I set `use_cache=True` or `use_cache_branch=True`, the caching function doesn't act. 

Can you confirm about this?

**Comment by fxmarty** [comment]
Thank you, I can reproduce the issue.

**Comment by fxmarty** [comment]
@kyle-bong Could you confirm to me the architecture of the decoder in your vision-encoder-decoder model?

**Comment by kyle-bong** [comment]
> 
OK. It is my configuration of decoder.
I made initialized the model by 
```
encoder_config = DeiTConfig(
        hidden_size=cfg.encoder.hidden_size,
        intermediate_size=cfg.encoder.intermediate_size,
        num_attention_heads=cfg.encoder.num_attention_heads,
        num_hidden_layers=cfg.encoder.num_hidden_layers,
        image_size=cfg.encoder.image_size,
        patch_size=cfg.encoder.patch_size
    )
decoder_config = GPT2Config(
        vocab_size=len(tokenizer),
        n_positions = cfg.data.max_length,
        n_embd = cfg.decoder.embedding_size,
        n_layer = cfg.decoder.num_hidden_layers,
        n_head=cfg.decoder.num_attention_heads,
        n_inner = cfg.decoder.intermediate_size,
        use_cache=True,
    )
model_config = VisionEncoderDecoderConfig.from_encoder_decoder_configs(encoder_config, decoder_config)
    model = VisionEncoderDecoderModel(model_config)
```

And ORT model config is here:
```
ort_model.config.decoder
```

GPT2Config {
  "activation_function": "gelu_new",
  "add_cross_attention": true,
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "is_decoder": true,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 384,
  "n_head": 6,
  "n_inner": 1536,
  "n_layer": 6,
  "n_positions": 256,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.30.2",
  "use_cache": true,
  "vocab_size": 3581
}

**Comment by fxmarty** [comment]
@kyle-bong Thanks! This should be fixed on main.
