### ISSUE TITLE
Import bug when trying to export model to ONNX

### ISSUE THREAD

**Issue by nicoFerreira95** [huggingface/optimum#1203]
### System Info

```shell
Name: transformers
Version: 4.31.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /opt/conda/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: auto-gptq, optimum, sentence-transformers
---
Name: onnxruntime
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /opt/conda/lib/python3.10/site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by: chromadb
Note: you may need to restart the kernel to use updated packages.

Running on GCP - Vertex AI Workbench with A100 84GB GPUs.
```

### Who can help?

Export of transformers model to ONNX/TFLite: @michaelbenayoun

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from optimum.onnxruntime import ORTModelForCausalLM
from transformers import AutoTokenizer

model_checkpoint = "TheBloke/Vicuna-13B-1-3-SuperHOT-8K-GPTQ"
save_directory = "onnx/"

ort_model = ORTModelForCausalLM.from_pretrained(model_checkpoint, export=True)
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

ort_model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

### Expected behavior

Trying to export to ONNX a LLaMA-based Vicuna model that is supposed to be able to be exported according to: https://huggingface.co/docs/optimum/exporters/onnx/overview

I get library/dependencies errors when trying to run my code. Is there anything that I'm doing wrong or the errors that I'm getting are showing up because Vicuna model is not supported. Would appreciate any help I can get

**Comment by michaelbenayoun** [comment]
What's the error you get?

**Comment by fxmarty** [comment]
Hi @nicoFerreira95 , GPTQ uses custom CUDA/triton kernels from external libraries to handle the mixed int4/fp16 compute, it is expected that the ONNX export fails.
