### ISSUE TITLE
NotImplementedError: The model type falcon is not yet supported to be used with BetterTransformer

### ISSUE THREAD

**Issue by camillebrl** [huggingface/optimum#1208]
### Feature request

When I use model = model.to_bettertransformer() I got the error "The model type falcon is not yet supported to be used with BetterTransformer", would you please support falcon model type to optimum? Thanks!

### Motivation

Falcon model type is not currently listed among the supported models for BetterTransformer.

### Your contribution

.

**Comment by fxmarty** [comment]
Hi, transformers falcon uses PyTorch's SDPA natively - we're discussing internally on how to handle it.

**Comment by fxmarty** [comment]
fixed
