### ISSUE TITLE
io_binding_helper not in minimum onnxruntime required version

### ISSUE THREAD

**Issue by SantiagoMoreno-UdeA** [huggingface/optimum#1237]
### System Info

```shell
optimum == 1.10.1
onnxruntime == 1.10.0
python == 3.9.0
System == iMX8M 

The minimum onnxruntime version required is 1.9.0 but optimum uses io_binding_helper from transformers which was added to onnxruntime in the 1.11.? version. 

In needed to updated the minimum version of onnxruntime.
```

### Who can help?

@JingyaHuang, @echarlaix

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just import ORTModelForSpeechSeq2Seq using a version of onnxruntime undes 1.11.? like 1.10.0 

### Expected behavior

You will have the following error message: 
Traceback (most recent call last):
  File "/home/root/mobilenetv2-7/test.py", line 5, in <module>
    from optimum.onnxruntime import ORTModelForSpeechSeq2Seq
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnxruntime.modeling_seq2seq because of the following error (look up to see its traceback):
No module named 'onnxruntime.transformers.io_binding_helper'

**Comment by fxmarty** [comment]
Thank you for reporting, fixed in https://github.com/huggingface/optimum/pull/1244!
