### ISSUE TITLE
AttributeError: 'torch._C.Generator' object has no attribute 'randn'

### ISSUE THREAD

**Issue by NourEldin-Osama** [huggingface/optimum#1242]
### System Info

```shell
optimum (1.10.1)
Platform: Google colab
Python: 3.10.6

transformers (4.31.0)
torch (2.0.1+cu118)
diffusers
```

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
```shell
pip install optimum[onnxruntime] diffusers==0.19.2
```

```python
from optimum.onnxruntime import ORTStableDiffusionPipeline
import torch

pipeline = ORTStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", provider="CPUExecutionProvider", revision = "onnx"
)

seed = 1
generator = torch.Generator(device="cpu")
seed = seed or generator.seed()
generator = generator.manual_seed(seed)
images = pipeline(
    prompt="Red Car",
    width=512,
    height=512,
    num_inference_steps=25,
    guidance_scale=7.5,
    generator=generator,
).images[0]
images
```

### Expected behavior

the code generates an image with a specific seed 
however, the code works when removing the specific seed and the ```generator```

also when working without the ```generator``` and I pass ```num_inference_steps=25``` it actually treats it like ```num_inference_steps=26``` you can check tqdm to understand

**Comment by fxmarty** [comment]
Hi @NourEldin-Osama, thank you for the report! The pipelines for stable diffusion using ONNX Runtime rely completely on numpy (apart it appears from the scheduler @echarlaix?) and do not use PyTorch. For the generator, you need to use an `np.random.RandomState`. Example:

```python
from optimum.onnxruntime import ORTStableDiffusionPipeline
import numpy as np

pipeline = ORTStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", provider="CPUExecutionProvider", revision="onnx"
)

generator = np.random.RandomState(42)
images = pipeline(
    prompt="Red Car",
    width=512,
    height=512,
    num_inference_steps=25,
    guidance_scale=7.5,
    generator=generator,
).images[0]
images
```

It is true that the documentation is not very (not at all) informative, I'll do a PR to fix that: https://huggingface.co/docs/optimum/main/en/onnxruntime/package_reference/modeling_ort#stable-diffusion
