### ISSUE TITLE
WhisperForConditionalGeneration optimum onnxruntime CUDA slower than Vanilla CUDA Transformers

### ISSUE THREAD

**Issue by SantiagoMoreno-UdeA** [huggingface/optimum#1265]
### System Info

```shell
Optimum version == 1.11.0 
onnxruntime version == 1.12.1
python version == 3.8.8
```

### Who can help?

@JingyaHuang, @echarlaix

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Try WhisperForConditionalGeneration from Vanilla Transformers using CUDA and from Optimum/onnxruntime with CUDA Provider.

### Expected behavior

The inference using optimum/onnxruntime is near 2x slower than using vanilla transformers.

**Comment by fxmarty** [comment]
Hi @SantiagoMoreno-UdeA, feel free to provide a reproduction in this thread: https://github.com/huggingface/optimum/issues/869#issuecomment-1469667213
