### ISSUE TITLE
add `optimum` to conda-forge channel on `conda`

### ISSUE THREAD

**Issue by sugatoray** [huggingface/optimum#127]
:memo: It will be nice to have `optimum` on conda-forge for installation and for downstream applications that use `optimum` and want to make themselves available on conda-forge channel.

:point_right:  I have already started the work on this. The PR is very close to getting merged. :fire: 

- PR: https://github.com/conda-forge/staged-recipes/pull/18300

:information_source:  I will share updates on the availability of `optimum` on conda-forge, once it gets merged.

:zap: With this addition, users will be able to install `optimum` with:

```sh
conda install -c conda-forge optimum
```

**Comment by sugatoray** [comment]
cc: @echarlaix

**Comment by sugatoray** [comment]
`optimum` is now available on conda-forge.

```sh
$ conda search -c conda-forge optimum
Loading channels: done
# Name                       Version           Build  Channel             
optimum                        1.0.0    pyhd8ed1ab_0  conda-forge
```

**Comment by sugatoray** [comment]
![image](https://user-images.githubusercontent.com/10201242/161246879-fcae3f19-fa3f-49a9-94c0-225596054ff0.png)

**Comment by sugatoray** [comment]
@echarlaix Thank you, for bringing that (optional requirements) up. Yes, I observed yesterday that there are some optional requirements now introduced to optimum. This can be handled on conda-forge side with subpackages. Once I update the recipe again, I will try and adapt to these optional installations.

**Comment by echarlaix** [comment]
Awesome news @sugatoray ! And again, many thanks for your contribution.
