### ISSUE TITLE
Super slow Inference of llama2 models when Provider is TensorrtExecutionProvider (Unusable)

### ISSUE THREAD

**Issue by biswaroop1547** [huggingface/optimum#1278]
I am coming from issue #1248 which got resolved, now:

I am trying to convert Llama 2 HF model ->  ONNX -> TensorRT for faster inference.
Here's what I did:

- Took the [daryl149/llama-2-7b-chat-hf](https://huggingface.co/daryl149/llama-2-7b-chat-hf) model and used [optimum-cli](https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model#exporting-a-model-to-onnx-using-the-cli) to export to onnx format. :white_check_mark:
`optimum-cli export onnx --model daryl149/llama-2-7b-chat-hf --device cuda --fp16 --no-post-process llama2_onnx`

Now when I try to do inference using optimum.onnxruntime.ORTModelForCausalLM things work fine when provider is CPUExecutionProvider or CUDAExecutionProvider , but when provider is TensorrtExecutionProvider I get super slow inference, by super slow I mean 2-3 token generation can take ~30 mins.

code I am trying to run is:
```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("./llama2_onnx/")
model = ORTModelForCausalLM.from_pretrained("./llama2_onnx/", provider="CUDAExecutionProvider")
inputs = tokenizer("My name is Arthur and I live in", return_tensors="pt").to("cuda")
gen_tokens = model.generate(**inputs, max_length=16)
assert model.providers == ['CUDAExecutionProvider', 'CPUExecutionProvider']
print(tokenizer.batch_decode(gen_tokens)) # this works as expected
# >>> ['<s> My name is Arthur and I live in a small town in the countr']
```

But this takes super long (unusable) for generating anything:
```python

provider_options = {"trt_fp16_enable": True, "trt_engine_cache_enable": True, "trt_engine_cache_path": "trt_cache"}

model = ORTModelForCausalLM.from_pretrained("./llama2_onnx/", provider="TensorrtExecutionProvider", provider_options=provider_options)

inputs = tokenizer("My name is Arthur and I live in", return_tensors="pt").to("cuda")
gen_tokens = model.generate(**inputs) # this takes kind of forever (totally unusable)
```

I am using the following dockerfile to create a container and experiment inside it:
```
FROM nvcr.io/nvidia/tensorrt:22.12-py3

ENV CUDA_MODULE_LOADING=LAZY

RUN pip install -U pip
RUN pip install ipython transformers optimum[onnxruntime-gpu] onnx diffusers accelerate scipy safetensors composer
RUN pip uninstall torch -y
RUN pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
```

And I am using the following versions:
```
onnx==1.14.0
onnxruntime-gpu==1.15.1
optimum==1.11.1

nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
```

Also I am using a 40GB A100 GPU and 80GB CPU RAM

Any pointers to figure out what's happening would highly help!

**Comment by biswaroop1547** [comment]
cc @fxmarty 🙏🏻

**Comment by IlyasMoutawwakil** [comment]
hi @biswaroop1547 , [this section from the docs](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/gpu#tensorrt-engine-build-and-warmup) answers how to correct this behavior.
The engine is rebuilt with each sequence length in the generation pass, to avoid this, **first build the TensorRT engine with an input of small shape, and then with an input of large shape to have an engine valid for all shapes inbetween**.

**Comment by biswaroop1547** [comment]
thank you @IlyasMoutawwakil I actually went through the doc before, but the issue here is even with an input of small shape it never generates an engine (hence I wrote it takes forever 😓)

**Comment by whk6688** [comment]
i also have same issue
