### ISSUE TITLE
Merge patch into autogptq

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/optimum#1285]
### Feature request

Currently, there is a patch to get GPTQ quantization working:
```
# !pip install -q git+https://github.com/fxmarty/AutoGPTQ.git@patch-act-order-exllama
```

Is there a plan to try and merge that into the autogptq repo?

### Motivation

autogptq is slow to install. This is easily solved by using wheels, but I don't have wheels for this patch. Easiest would be for the patch to be released.

### Your contribution

Seems like the patch is a few tens of commits behind autogptq, so the first step would be to check whether doing a pr would create conflicts.

**Comment by RonanKMcGovern** [comment]
OK that's really great, thanks @fxmarty

**Comment by fxmarty** [comment]
It's in the works for the integration with transformers, hopefully this week!

**Comment by fxmarty** [comment]
Hi @RonanKMcGovern, the release is done, see: https://github.com/PanQiWei/AutoGPTQ#quick-installation

**Comment by RonanKMcGovern** [comment]
Beautiful, thanks @fxmarty , I'll try it out.
