### ISSUE TITLE
onnxruntime support for pix2struct using ORT class

### ISSUE THREAD

**Issue by krathul** [huggingface/optimum#1288]
### Feature request

It will be great to have an ORT class for pix2struct. The export of the model using optimum was supported in #937 but no onnxruntime support have been implemented.

### Motivation

Currently there is no onnxruntime support for pix2struct in optimum. An ORTModel class will help in applying optimizations and exporting.

### Your contribution

I can help with the ORT class, I currently have a working implementation of an ORT class for supporting pix2struct. I used the same decoder used for all classes in [modeling_seq2seq.py](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/modeling_seq2seq.py) with an additional decoder_attention_mask argument and an encoder and a main class written by referencing the `ORTModelForSpeechSeq2Seq` and `transformers.Pix2StructForConditionalGeneration`.

**Comment by fxmarty** [comment]
Will do this week

**Comment by fxmarty** [comment]
Fixed by https://github.com/huggingface/optimum/pull/1296
