### ISSUE TITLE
ImportError: cannot import name 'repeat_kv' from 'transformers.models.llama.modeling_llama' when importing BetterTransformer

### ISSUE THREAD

**Issue by hugocool** [huggingface/optimum#1300]
### System Info

```shell
Optimum Version: 1.11.2
Transformers Version: 4.31.0

Python: 3.9.10
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

from optimum.bettertransformer import BetterTransformer

### Expected behavior

it should work

**Comment by chunhualiu** [comment]
It's fixed. Upgrade transformers to latest version.
