### ISSUE TITLE
AttributeError: Can't pickle local object 'main.<locals>.train_transforms'

### ISSUE THREAD

**Issue by prathikr** [huggingface/optimum#1327]
### System Info

```shell
python==3.8

accelerate==0.22.0
evaluate==0.4.0
optimum==1.12.0
scikit-learn==1.3.0
transformers==4.32.1

onnx==1.14.0
onnxruntime-training==1.15.0+cu118
```

### Who can help?

@JingyaHuang @echarlai

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Environment:
```Dockerfile
FROM mcr.microsoft.com/aifx/acpt/stable-ubuntu2004-cu118-py38-torch200
RUN pip install accelerate evaluate optimum transformers
RUN pip install scikit-learn

RUN pip list
```

Run Command:
```bash
torchrun run_image_classification.py \
                        --model_name_or_path google/vit-base-patch16-224 \
                        --do_train --do_eval \
                        --dataset_name beans \
                        --fp16 True --num_train_epochs 1 \
                        --per_device_train_batch_size 8 --per_device_eval_batch_size 8 \
                        --remove_unused_columns False --ignore_mismatched_sizes True \
                        --output_dir output_dir --overwrite_output_dir \
                        --dataloader_num_workers 1
```

Error:
```
Traceback (most recent call last):
  File "run_image_classification_ort.py", line 423, in <module>
    main()
  File "run_image_classification_ort.py", line 397, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum/onnxruntime/trainer.py", line 462, in train
    return inner_training_loop(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/optimum/onnxruntime/trainer.py", line 739, in _inner_training_loop
    for step, inputs in enumerate(train_dataloader):
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/accelerate/data_loader.py", line 381, in __iter__
    dataloader_iter = super().__iter__()
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1043, in __init__
    w.start()
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/envs/ptca/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.train_transforms'
```

### Expected behavior

The script is expected to train `google/vit-base-patch16-224` for image-classification task.

The error occurs only when using `--dataloader_num_workers` parameter. The error callstack never passes through any onnxruntime code and seems to be isolated to the dataloader. I believe some update to the accelerate package is causing this issue with optimum. There is no error when I use `ORTModule` directly from `onnxruntime.training.ortmodule` library, only an issue when I use `ORTTrainer` from `optimum.onnxruntime` library.

Related links from the web:
- https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857/9
- https://stackoverflow.com/questions/62186218/python-multiprocessing-attributeerror-cant-pickle-local-object

This is URGENT as the AzureML Vision Team is in the final steps of releasing finetuning components for image-classification to production. Thank you in advance for any help!

**Comment by muellerzr** [comment]
@prathikr can you try via transformers v4.33.0? And is `run_image_classification.py` any different than the one in `examples/pytorch/run_image_classification.py`? Running on two GPUs I saw no issue here.

**Comment by prathikr** [comment]
@muellerzr it is meant to be the same, though I don't think the example script in optimum has been updated in a while. For this particular issue, I copied the code from `transformers/examples/pytorch/run_image_classification.py` and swapped Trainer/TrainingArguments with ORTTrainer/ORTTrainingArguments manually. 

I see the same issue when using transformers==4.33.0

**Comment by shubhamiit** [comment]
Having the same issue without ORT also with num_workers>1:

datasets==2.14.5
transformers==4.33.0
optimum==1.13.1
accelerate==0.22.0
diffusers==0.20.2

Can this issue be prioritized?

**Comment by prathikr** [comment]
@muellerzr @JingyaHuang any updates?

**Comment by fxmarty** [comment]
The same issue exists with

```
torch==2.0.1
transformers==4.28.1
optimum==1.10.0
accelerate uninstalled
```

so I doubt the issue is related to accelerate, and it is likely a longstanding one.

**Comment by fxmarty** [comment]
This issue was introduced in https://github.com/huggingface/optimum/pull/1115, specifically: https://github.com/huggingface/optimum/blob/c63138778c0c08b96ee49ea35f6346ff42a21437/optimum/exporters/onnx/convert.py#L57

It appears that the onnxruntime-training uses multiprocessing at some point, and `spawn` is not working. Fork is.

The above PR launches validation of the exported ONNX models in subprocesses avoiding reported memory leaks in ORT InferenceSession destruction on CUDA EP (that [does not support fork](https://github.com/microsoft/onnxruntime/issues/7846#issuecomment-850217402)). I'll put some guards and publish a patch, thank you for the notice.
