### ISSUE TITLE
Does this support zero shot classification

### ISSUE THREAD

**Issue by gr8nishan** [huggingface/optimum#136]
Wanted to know if it supports zero shot classification as when I give feature as zero shot classification it gives error.

**Comment by echarlaix** [comment]
Hi @gr8nishan, 

The feature you select enables you to export your model to the ONNX format for a given topology. You can find [here](https://huggingface.co/docs/transformers/serialization#selecting-features-for-different-model-topologies) the list of the features you can use. In your case, you should use the `"sequence-classification"` feature.
