### ISSUE TITLE
bug: Failed to load GPTQ model from local path from `transformers.PreTrainedModel`

### ISSUE THREAD

**Issue by aarnphm** [huggingface/optimum#1360]
### System Info

```shell
optimum 0.12.0
CPython 3.11.4
Ubuntu 20
```

### Who can help?

I'm not sure who to tag here, but cc @SunMarc since you add support for GPTQ to optimum

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

First save the GPTQ model from local path

```python
model = transformers.AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-13B-chat-GPTQ", device_map='cuda')
model.save_pretrained("./local-gptq")
```

When trying to load from this path, the following bug is encountered:

```python
from accelerate import init_empty_weights
from optimum.gptq import load_quantized_model
# disable exllama if gptq is loaded on CPU
disable_exllama = not torch.cuda.is_available()
with init_empty_weights():
  empty = transformers.AutoModelForCausalLM.from_pretrained('TheBloke/Llama-2-13B-chat-GPTQ', torch_dtype=torch.float16, device_map='auto')
empty.tie_weights()
model = load_quantized_model(empty, save_folder="/home/ubuntu/local-gptq", device_map='auto', disable_exllama=disable_exllama)
```

```prolog
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 8
      6   empty = transformers.AutoModelForCausalLM.from_pretrained('TheBloke/Llama-2-13B-chat-GPTQ', torch_dtype=torch.float16, device_map='auto')
      7 empty.tie_weights()
----> 8 model = load_quantized_model(empty, save_folder="./gptq-local", device_map='auto', disable_exllama=disable_exllama)

File ~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/optimum/gptq/quantizer.py:614, in load_quantized_model(model, save_folder, quant_config_name, state_dict_name, device_map, max_memory, no_split_module_classes, offload_folder, offload_buffers, offload_state_dict, disable_exllama)
    611     device_map = {"": torch.cuda.current_device()}
    612     logger.info("The device_map was not initialized." "Setting device_map to `{'':torch.cuda.current_device()}`.")
--> 614 with open(os.path.join(save_folder, quant_config_name), "r", encoding="utf-8") as f:
    615     quantize_config_dict = json.load(f)
    616 quantizer = GPTQQuantizer.from_dict(quantize_config_dict)

FileNotFoundError: [Errno 2] No such file or directory: './gptq-local/quantization_config.json'
```

Since transformers.AutoModelForCausalLM can load quantisation from config.json, most of the GPTQ model on the Hub will just include `quantization_config` under here.

Though I do believe that having a separate `quantization_config.json` should be the expected behaviour, would it makes sense to provide a compat layer to check for config.json?

If this makes sense lmk if I can make a PR for this.

### Expected behavior

It can support `quantization_config` from `config.json`

**Comment by aarnphm** [comment]
Current workaround is just using `transformers.AutoModelForCausalLM.from_pretrained` from this custom path, which works, but I was trying the instruction from the docs.

**Comment by SunMarc** [comment]
Hi @aarnphm, `load_quantized_model` is supposed to be used with models saved with the optimum api `GPTQQuantizer.save(model)`. We did that so that people with non transformers model could also quantize their model. As you saw, the right way to load a quantized transformers model is by using `transformers.AutoModelForCausalLM.from_pretrained`. However, if you want to make it work, you can just dump a json file of `quantization_config` from `config.json`. Happy to review your PR if you want to add support !

**Comment by aarnphm** [comment]
Hi @SunMarc, PTAL here https://github.com/huggingface/optimum/pull/1363

Looking forward to hear your feedback

**Comment by aarnphm** [comment]
Another solution is to document this behaviour for people who come from transformers, and people can manually do this instead of having this logic in here.

Since I think this is pretty easy to do as well
