### ISSUE TITLE
Unable to load huggingface models with intel neural compressor's IncQuantizer.

### ISSUE THREAD

**Issue by nirmal2k** [huggingface/optimum#140]
```
from optimum.intel.neural_compressor.quantization import IncQuantizerForSequenceClassification
quantizer = IncQuantizerForSequenceClassification.from_config('typeform/distilbert-base-uncased-mnli')
```
The above code gives
`HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/typeform/distilbert-base-uncased-mnli/resolve/main/best_configure.yaml`

**Comment by echarlaix** [comment]
Hi @nirmal2k , 

You need to provide a configuration file containing all the information related to the quantization you want to apply (see [here](https://huggingface.co/echarlaix/bert-base-dynamic-quant-test/blob/main/quantization.yml)).

To apply dynamic quantization, you can for example try :

```python
quantizer = IncQuantizerForSequenceClassification.from_config(
    "typeform/distilbert-base-uncased-mnli", 
    inc_config="echarlaix/bert-base-dynamic-quant-test", 
    config_name="quantization.yml"
)
```
