### ISSUE TITLE
Weirdness when ONNX optimize/exporting and quantizing Llama2 - fails on both, have tried python and CLI approaches

### ISSUE THREAD

**Issue by gidzr** [huggingface/optimum#1409]
### System Info

```shell
latest version optimum / onnx / runtime
python 3.10
running on CPU server Debian 11 with apache, 32G RAM, 60G swapram, 320G HDD, 8 threads
```

### Who can help?

@michaelbenayoun, @JingyaHuang, @echarlaix

Hey peeps, been struggling with Llama2 re optimize quantize, and a couple of weird things happening.

Failure to recognise pth filetype
1. When running from meta/llama2 repository (meta-llama/Llama-2-7b), onnx doesn't recognise the 13GB consolidated.pth file. It just straight up fails to recognise the type. Paraphrased error message = "Please use pytorch or other recognised format"

Failure to optimise correctly or quantize on HF respository files
1. When running from meta/llama2 HF respository (meta-llama/Llama-2-7b-hf), instead of resulting in an optimized model.onnx file of 13G (which is the total size of the either the 2 safetensor files, OR the 2 pytorch files), I get two files being a 3Meg model.onnx, and a 26G model.onnx_data file. It looks like the optimizer is combining the safetensor and pytorch files
2. Instead of resulting in the expected model.onnx, it has this onnx_data file

When quantizing
1. It could be an offshoot of the above issue from optimization, but when I try to quantize the optimised result, I get: 
--->
Creating dynamic quantizer: QOperator (mode: IntegerOps, schema: u8/s8, channel-wise: False)
Quantizing model...
WARNING:root:Failed to infer data type of tensor: /model/layers.0/self_attn/Concat_4. Please add data type info for this tensor if your model has customized operators.
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "/usr/local/lib/python3.10/site-packages/optimum/commands/onnxruntime/quantize.py", line 102, in run
    q.quantize(save_dir=save_dir, quantization_config=qconfig)
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/quantization.py", line 416, in quantize
    quantizer.quantize_model()
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/quantization/onnx_quantizer.py", line 306, in quantize_model
    node = self.quantize_node_with_sub_graph(node)  # noqa: PLW2901
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/quantization/onnx_quantizer.py", line 217, in quantize_node_with_sub_graph
    kv = {attr.name: self.quantize_subgraph(attr.g, f"{node_name}:{attr.name}")}
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/quantization/onnx_quantizer.py", line 182, in quantize_subgraph
    sub_quantizer = ONNXQuantizer(
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/quantization/onnx_quantizer.py", line 115, in __init__
    self.activation_qType = activation_qType.tensor_type
AttributeError: 'int' object has no attribute 'tensor_type'

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

$   nohup sudo optimum-cli export onnx --model /home/admin/LLAMA2HF/Llama-2-7b-hf --task text-generation --optimize O3 /home/admin/LLAMA2HF/optimized

$  nohup sudo optimum-cli onnxruntime quantize --onnx_model /home/admin/LLAMA2HF/optimized --arm64 -o /home/admin/LLAMA2HF/quantized && touch finishedQuant.txt

### Expected behavior

Was hoping to crunch the 13G Llama into a 5G optimized model.onnx, then quantize it and get a 1G model.onnx

That would be sweet. :)

Wishful thinking I know.. but at any rate, the optimization and quantization don't seem to be working at all.

I'm going to try another approach, downloading everything to local, deleting / hiding the safetensor files, and running again with only the py.bin files in the folder.. 

I'll post my results.. to see if this is a viable workaround.

**Comment by fxmarty** [comment]
Hi @gidzr thank you for the report! This a bug in ONNX Runtime 1.16.0 https://github.com/microsoft/onnxruntime/pull/17651  (& llama ONNX export that adds subgraphs https://github.com/huggingface/transformers/pull/26162 https://github.com/pytorch/pytorch/issues/109292). The easiest (temporary) solution would be to downgrade to ONNX Runtime 1.15.

By the way, I don't think you will be able to shrink https://huggingface.co/meta-llama/Llama-2-7b/tree/main (25 GB fp32) to 1 GB using ONNX Runtime. ORT would allow you to shrink it down to ~6-7 GB with int8 quantization, but you would have to be careful about the prediction quality of the quantized model.

**Comment by gidzr** [comment]
@fxmarty awesome, thanks for the steer on the downgrade... and absolutely re 6-7GB .. the 1GB target is nice dreamz :P lolz

**Comment by gidzr** [comment]
Hi @fxmarty , just a quick addition tying into a related issue, Llama needs 1.15 to be quantized, but using the Xenova convert script which I need to use for the per_chanel reduce_range flags, has to be 1.16 for inferencing (https://github.com/huggingface/optimum/issues/1385). I think that means having one version for quanting and one version for infer'ing. If the results differ I'll come back and update.

**Comment by fxmarty** [comment]
cc @xenova Have you seen the same issue https://github.com/microsoft/onnxruntime/pull/17651 for models with subgraphs?

**Comment by xenova** [comment]
> cc @xenova Have you seen the same issue [microsoft/onnxruntime#17651](https://github.com/microsoft/onnxruntime/pull/17651) for models with subgraphs?

I have not... 👀 Unless this was introduced in onnxruntime > 1.14 (as Transformers.js is still using v1.14).

**Comment by fxmarty** [comment]
Yes the issue was introduced in 1.16.
