### ISSUE TITLE
support for Tapas model

### ISSUE THREAD

**Issue by sujit420** [huggingface/optimum#141]
Hi,
When I try to quantize the tapas model, it gives me an error. Is it supported?
Wehn I try below:
tapas_model = "google/tapas-base-finetuned-wtq"
qconfig = AutoQuantizationConfig.arm64(is_static=False, per_channel=False)
quantizer = ORTQuantizer.from_pretrained(tapas_model, feature="question-answering")

quantizer.export(
    onnx_model_path="model.onnx",
    onnx_quantized_model_output_path="tapas_model-quantized.onnx",
    quantization_config=qconfig,
)
I get, 
ValueError: Unrecognized configuration class <class 'transformers.models.tapas.configuration_tapas.TapasConfig'> for this kind of AutoModel: AutoModelForQuestionAnswering.
Model type should be one of YosoConfig, NystromformerConfig, QDQBertConfig, FNetConfig, GPTJConfig, LayoutLMv2Config, RemBertConfig, CanineConfig, RoFormerConfig, BigBirdPegasusConfig, BigBirdConfig, ConvBertConfig, LEDConfig, IBertConfig, MobileBertConfig, DistilBertConfig, AlbertConfig, CamembertConfig, XLMRobertaXLConfig, XLMRobertaConfig, MBartConfig, MegatronBertConfig, MPNetConfig, BartConfig, ReformerConfig, LongformerConfig, RobertaConfig, DebertaV2Config, DebertaConfig, FlaubertConfig, SqueezeBertConfig, BertConfig, XLNetConfig, XLMConfig, ElectraConfig, FunnelConfig, LxmertConfig, SplinterConfig, Data2VecTextConfig.

When I use "table-question-answering" as the feature, then there is a key error.

Please let me know if it can be supported.

**Comment by echarlaix** [comment]
Hi @sujit420, 

Currently TAPAS models are not supported for the export to the ONNX format, [here](https://github.com/huggingface/transformers/issues/16308) is the list of the supported architectures. If you wish to export a model whose architecture is not natively supported, [here](https://huggingface.co/docs/transformers/serialization#exporting-a-model-for-an-unsupported-architecture) are the three main steps to follow.

The feature you select enables you to export your model to the ONNX format for a given topology. You can find [here](https://huggingface.co/docs/transformers/serialization#selecting-features-for-different-model-topologies) the list of the features you can use.

**Comment by ChainYo** [comment]
Hi @sujit420 would love to see if you managed to implement the ONNX conversion for TAPAS. If yes it could be awesome to add it to Transformers lib. I oculd help to do so!
