### ISSUE TITLE
Forward greatly change after BetterTransformer.transform application with CLIP

### ISSUE THREAD

**Issue by jyangliu** [huggingface/optimum#1435]
### System Info

```shell
optimum:1.13.2
transformers:4.33.3
win10/CUDA 11.7/pytorch 2.0.0
```

### Who can help?

@fxmarty @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

[https://github.com/jyangliu/bettertransformer_test/blob/main/test_forward.py](url)

### Expected behavior

The forward image features of samples for models with and without BetterTransformer transformation should be nearly identical, but are in practice often very different.

**Comment by fxmarty** [comment]
Thank you @jyangliu, what was the issue?

**Comment by fxmarty** [comment]
nevermind found https://github.com/huggingface/optimum/issues/1437

**Comment by jyangliu** [comment]
Thanks for your reply. I have been tested BetterTransformer.transform with CLIP model, but I got different outputs for models&nbsp;&nbsp;with and without BetterTransformer transformation.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huggingface/optimum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 下午5:38
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [huggingface/optimum] Forward greatly change after BetterTransformer.transform application with CLIP (Issue #1435)





 
Thank you @jyangliu, what was the issue?
