### ISSUE TITLE
Deprecating SharedDDP caused failure on Optimum.

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/optimum#1441]
### System Info

```shell
optimum nightly
transformers nightly
```

### Problem:
SharedDDP has been deprecated in the transformers library, but it is still being used in the optimum examples. This is causing failures in the examples, and we need to address this issue.

### Question:
Are you actively working on fixing this problem, or should I go ahead and create a PR to resolve this issue?

### Additional Inquiry:
In the interest of maintaining compatibility and preventing future issues, can you provide insight into how changes in the transformers library are being tested to ensure they do not impact optimum examples going forward?

@JingyaHuang 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

run any optimum example.

### Expected behavior

Getting these errors.

AttributeError: 'Trainer' object has no attribute 'use_cuda_amp'
or 
is_fairscale_available failed to be imported from transformers.integration.

**Comment by JingyaHuang** [comment]
Close as it's fixed via https://github.com/huggingface/optimum/pull/1443, thanks again for fixing it @AdamLouly !
