### ISSUE TITLE
ONNX Runtime-GPU not working inside the docker

### ISSUE THREAD

**Issue by OleksandrKorovii** [huggingface/optimum#1444]
### System Info

```shell
Python Version: 3.10

torch==2.1.0
fastapi==0.103.2
transformers==4.34.0
uvicorn==0.23.2
loguru==0.7.2
websockets==11.0.3
bitsandbytes==0.41.1
optimum[onnxruntime-gpu]==1.13.2
```

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

I use optimum to export my finetuned GPT2.

    optimum-cli export onnx --task causal-lm-with-past --model medium-mail/ --optimize O4 --device cuda medium-onnx/

After this, I run it via next code 

````python
from transformers import GPT2Tokenizer
from optimum.onnxruntime import ORTModelForCausalLM

tokenizer = GPT2Tokenizer.from_pretrained("medium-onnx")
model = ORTModelForCausalLM.from_pretrained('medium-onnx', provider='CUDAExecutionProvider')
````

And locally it runs okay, everything fine. 

But when I run inside the docker container i get the error.

````
 self.gpt_model = ORTModelForCausalLM.from_pretrained(path, provider="CUDAExecutionProvider")
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 647, in from_pretrained
    return super().from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_decoder.py", line 711, in _from_pretrained
    return super()._from_pretrained(model_id, config, init_cls=ORTModelForCausalLM, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_decoder.py", line 486, in _from_pretrained
    ort_inference_sessions = cls.load_model(
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_decoder.py", line 280, in load_model
    decoder_session = ORTModel.load_model(decoder_path, provider, session_options, provider_options)
  File "/usr/local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 369, in load_model
    return ort.InferenceSession(
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for MemcpyFromHost(1) (node Memcpy). Kernel not found


````

```Dockerfile
FROM python:3.10

RUN apt-get update \
    && apt-get -y upgrade

WORKDIR /app
COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . /app
```

### Expected behavior

Everything will work in docker fine.

**Comment by OleksandrKorovii** [comment]
I solved it by downgrading the `torch` version from `2.1.0` -> `2.0.1`, because on the server I have installed Cuda version 11.8 but dependences of `torch==2.1.0` required `cuda >= 12.0`

**Comment by mbuet2ner** [comment]
@fxmarty maybe it makes sense to restraint the `torch` version to < `2.10` in [setup.py](https://github.com/huggingface/optimum/blob/main/setup.py) then? Because at least for `onnxruntime-gpu` the export is broken otherwise. Just stumbled upon the error myself.

Sure, it is possible to simply downgrade `torch`. But since `onnxruntime` is still stick with CUDA 11.8, it is very likely that more users will face the error. What do you think?

**Comment by fxmarty** [comment]
Thank you, PyTorch 2.1 can be installed for CUDA 11.8: https://pytorch.org/get-started/locally/
