### ISSUE TITLE
Llama 2 BetterTransformer Broken

### ISSUE THREAD

**Issue by AjayP13** [huggingface/optimum#1446]
### System Info

On `transformers==4.34.0`, patching `meta-llama/Llama-2-7b-chat-hf` with `BetterTransformer` and then running results in the error:

```shell
Error: TypeError: llama_forward() got an unexpected keyword argument 'padding_mask'
```

### Who can help?

@younesbelkada 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

N/A

### Expected behavior

N/A

**Comment by younesbelkada** [comment]
Thanks for reporting, this should be already fixed on the main branch of transformers, can you try to install optimum from source? 
We are also migrating `BetterTransformer` to transformers core. Check out this PR: https://github.com/huggingface/transformers/pull/26572 for more details

**Comment by fxmarty** [comment]
Hi @AjayP13, thank you. Transformers added an argument `padding_mask` that broke BetterTransformer. The bug is fixed on the main branch, but we still did not do a pypi release.

**Comment by hengqujushi** [comment]
Same here, looking forward to this fix PR being merged into the main branch soon.

**Comment by fxmarty** [comment]
The fix PR is already in main!

**Comment by fxmarty** [comment]
https://github.com/huggingface/optimum/pull/1421
