### ISSUE TITLE
nougat to onnx

### ISSUE THREAD

**Issue by arvisioncode** [huggingface/optimum#1459]
### Feature request

I would like to do the transformation of the [nougat](https://huggingface.co/facebook/nougat-base) model to onnx, is it possible to do it through optimum?

### Motivation

Nougat is a [Donut](https://huggingface.co/docs/transformers/model_doc/donut) model trained to transcribe scientific PDFs into an easy-to-use markdown format.

**Comment by fxmarty** [comment]
Thank you @arvisioncode. I tried `optimum-cli export onnx -m facebook/nougat-base nougat_onnx` and the export appear to be successful:

![image](https://github.com/huggingface/optimum/assets/9808326/62b18492-1af3-4332-a2d9-2fd2a9f2f715)

**Comment by arvisioncode** [comment]
Thank you @fxmarty !!

**Comment by XCD4P** [comment]
@fxmarty could show how to use the converted nougat onnx model to do referencing?
