### ISSUE TITLE
Not compatible with transformer llama_modeling forward

### ISSUE THREAD

**Issue by wangxg666** [huggingface/optimum#1464]
https://github.com/huggingface/optimum/blob/e7bd60dd2c1e295263ba57a4e468a62ab5b179e8/optimum/bettertransformer/models/attention.py#L581

with transformer 
https://github.com/huggingface/transformers/blob/b71f20a7c9f3716d30f6738501559acf863e2c5c/src/transformers/models/llama/modeling_llama.py#L925

new params `padding_mask`

**Comment by fxmarty** [comment]
Thank you @wangxg666, this is fixed on the main branch and will be added in the next release. Please install from source in the meanwhile, apology for the inconvenience.
