### ISSUE TITLE
Support for electra model

### ISSUE THREAD

**Issue by OriAlpha** [huggingface/optimum#147]
I came across this tool and it looks very interesting but i am trying to use electra model and i can see this is not supported. By this 
`"electra is not supported yet. Only ['albert', 'bart', 'mbart', 'bert', 'ibert', 'camembert', 'distilbert', 'longformer', 'marian', 'roberta', 't5', 'xlm-roberta', 'gpt2', 'gpt-neo', 'layoutlm'] are supported. If you want to support electra please propose a PR or open up an issue`. 
is any plans for electra models in future. 
Example of models https://huggingface.co/german-nlp-group/electra-base-german-uncased

**Comment by echarlaix** [comment]
Hi @OriAlpha, 

Thanks for your interest in optimum ! 
We added the support of electra models in the [PR#150](https://github.com/huggingface/optimum/pull/150)
