### ISSUE TITLE
Request to incorporate Mistral into BetterTransformers

### ISSUE THREAD

**Issue by cassianlewis** [huggingface/optimum#1476]
### Feature request

Not much more to it :)

### Motivation

NA

### Your contribution

NA

**Comment by Astropulse** [comment]
I would also like this, the Mistral based Zephyr-7B-alpha and Zephyr-7B-beta are very useful text models.

**Comment by MarkWijkhuizen** [comment]
I would also like to emphasize the importance of Mistral support.

**Comment by fxmarty** [comment]
Hi, we are upstreaming the usage of PyTorch scaled_dot_product_attention in Transformers directly, adding Mistral support would be great https://github.com/huggingface/transformers/issues/28005.

We won't be extending BetterTransformer for it, so let's move to the issue I linked.

For reference: https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-and-memory-efficient-attention-through-pytorchs-scaleddotproductattention

See also https://github.com/huggingface/transformers/releases/tag/v4.36.0
