### ISSUE TITLE
about LCM onnx model

### ISSUE THREAD

**Issue by Amin456789** [huggingface/optimum#1497]
Hi!

can someone please tell how we can use the LCM model in onnx? i see u guys made an script to run it in onnx, but what about the model? can we simply use the normal stable diffusion script onnx conversation for lcm model too? or we have to wait someone make an conversation script?

or could someone upload onnx converted of LCM model on huggingface and share it with us please?

kind regards

### Who can help?

@echarlaix

**Comment by echarlaix** [comment]
Hi @Amin456789, 

To export latent consistency models you can either use the [CLI](https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model) :

```bash
optimum-cli export onnx --model SimianLuo/LCM_Dreamshaper_v7 lcm_onnx/
```

or directly load the model with [`ORTLatentConsistencyModelPipeline`](https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/models#latent-consistency-models) and convert it to ONNX on-the-fly by setting `export=True`
```python
from optimum.onnxruntime import ORTLatentConsistencyModelPipeline

pipeline = ORTLatentConsistencyModelPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", export=True)
prompt = "sailing ship in storm by Leonardo da Vinci"
images = pipeline (prompt=prompt, num_inference_steps=4, guidance_scale=8.0).images
```

**Comment by Amin456789** [comment]
thank u so much!

**Comment by nbertagnolli** [comment]
Thanks for working on the support for latent consistency models! : ). When I run the above code I get the following error:

```
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'unet', 'safety_checker', 'scheduler', 'text_encoder', 'tokenizer', 'vae', 'feature_extractor'}, but only {'unet', 'safety_checker', 'text_encoder', 'tokenizer', 'vae', 'feature_extractor'} were passed.
```

It looks like it can't find the scheduler. I've installed everything from source and when I load in the model using vanilla transformers I see that it has an associated scheulder:

```

from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_txt2img", custom_revision="main")
print(pipe.scheduler)
```

I get:

```
LCMScheduler {
  "_class_name": "LCMScheduler",
  "_diffusers_version": "0.22.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": false,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "steps_offset": 0,
  "thresholding": false,
  "timestep_spacing": "leading",
  "trained_betas": null
}
```
Any thoughts on why the ORTLatentConsistencyModelPipeline can't find the scheduler in this case?

**Comment by NeusZimmer** [comment]
Hi... i tried the option for converting, but currently looks like it only works downloading models from HuggingFace, I'm trying to convert a downloaded LCM model in safetensor and I'm struggling, currently i was able to load it using a normal pipeline and then initializing the LCM pipeline with the loaded submodels, and saving them to disk. but the above instruction does not work for already on disk models.
 `
from diffusers.pipelines.stable_diffusion.convert_from_ckpt import download_from_original_stable_diffusion_ckpt 
loaded_model =download_from_original_stable_diffusion_ckpt(
            checkpoint_path_or_dict=model,
            device=device,
            load_safety_checker=False,
            from_safetensors= safetensors,
            local_files_only=True)

from diffusers.pipelines  import LatentConsistencyModelPipeline
loaded_model2=LatentConsistencyModelPipeline(unet=loaded_model.unet,
                                                vae=loaded_model.vae,
                                                text_encoder=loaded_model.text_encoder,
                                                tokenizer=loaded_model.tokenizer,
                                                scheduler=loaded_model.scheduler,
                                                requires_safety_checker=loaded_model.requires_safety_checker,
                                                safety_checker=loaded_model.safety_checker,
                                                feature_extractor= loaded_model.feature_extractor)

loaded_model.save_pretrained(path_to_savedmodel)
`
optimum-cli export onnx --model model_name onnx_model_output
gives this error: RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.

**Comment by NeusZimmer** [comment]
> @echarlaix another question, does this version of LCM run on CPU too? can this onnx model be fp16 or quantized to int8?

I've converted it to fp16 with no issues and run ok, will upload to civitai if allowed by the owner of the model

**Comment by echarlaix** [comment]
@nbertagnolli, do you still have this issue with `diffusers` v0.22.0 or higher ? If yes could you open a new issue describing the error you are getting and ping me there?

Great news, thanks for sharing @NeusZimmer !
