### ISSUE TITLE
Support exporting text-generation models for sequence classification to ONNX

### ISSUE THREAD

**Issue by dwyatte** [huggingface/optimum#1527]
### Feature request

Exporting text-generation models (e.g., LlamaForSequenceClassification) was disabled in https://github.com/huggingface/optimum/pull/1308

Given https://arxiv.org/abs/2310.01208, these models can outperform typical encoder models for sequence classification (I can confirm this on my own datasets)

What would it take to support this in transformers? CC @fxmarty since it was mentioned specifically in the PR above

### Motivation

I would like to export fine-tuned sequence classification models that use a decoder-only model as their base architecture to ONNX

### Your contribution

Happy to submit a PR to `transformers` with guidance on what would be needed

**Comment by dwyatte** [comment]
Ah, I see what's happening -- ONNX doesn't support int64 inputs to argmax which is how these models are computing the sequence lengths for pooling. Will open a PR over in `transformers` and leave this open until we can enable export in this repo

**Comment by fxmarty** [comment]
Thank you for the fix!

**Comment by dwyatte** [comment]
Requires one more fix in `transformers` to get output validation passing with the current dummy inputs: https://github.com/huggingface/transformers/pull/28144
