### ISSUE TITLE
🐛 OptimizationConfig missing disable_rotary_embeddings option

### ISSUE THREAD

**Issue by sparverius** [huggingface/optimum#1528]
microsoft/onnxruntime#18021 made some updates for Llama optimization a few weeks ago adding `disable_rotary_embeddings` option. see blame here [microsoft/onnxruntime/python/tools/transformers/fusion_options.py](https://github.com/microsoft/onnxruntime/blame/87744e55faa8c7570d17f29f54f2ffdb8b702d04/onnxruntime/python/tools/transformers/fusion_options.py#L86-L87)

OptimizationConfig in huggingface/optimum/optimum/onnxruntime/configuration.py is missing `disable_rotary_embeddings`

Arises from calling FusionOptions.parse() without option disable_rotary_embeddings
```
.../python3.10/dist-packages/onnxruntime/transformers/fusion_options.py in parse(args)
     84         if args.disable_layer_norm:
     85             options.enable_layer_norm = False
---> 86         if args.disable_rotary_embeddings:
     87             options.enable_rotary_embeddings = False
     88         if args.disable_attention:

AttributeError: 'Box' object has no attribute 'disable_rotary_embeddings'
```
see:
https://github.com/huggingface/optimum/blob/832f3b292b501c7ab920ecc7913de3c6b7894d60/optimum/onnxruntime/configuration.py#L785-L813

**Comment by filippo82** [comment]
I also bumped into this issue. As a workaround, I pinned `onnxruntime==1.16.1`.

**Comment by filippo82** [comment]
This PR should take care of it: #1535 💪🏻

**Comment by sparverius** [comment]
Closing as mentioned, #1535 resolves issue. 

btw, @filippo82 good luck with arxiv-insanity 🍀

**Comment by filippo82** [comment]
Thank you 😇

**Comment by filippo82** [comment]
@sparverius FYI the PR has been merged and the new release is already on pypi 🥳
