### ISSUE TITLE
ORT Models Failing because of the latest fsdp changes on transformers Trainer.

### ISSUE THREAD

**Issue by AdamLouly** [huggingface/optimum#1554]
### System Info

```shell
optimum from source
transformers from source
```

### Who can help?

@JingyaHuang 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

when trying to run training using ortmodule all models will fail due to latest changes on transformers trainer.
fsdp was removed as an attribute and it included other changes.

I can work on the fix if you guys don't have the bandwith.

@JingyaHuang 
We also been getting a lot of this types errors, can we work on some CI pipeline to spot these failures so we can fix them fast?

Thanks.

### Expected behavior

`AttributeError: 'ORTTrainer' object has no attribute 'fsdp'
`

**Comment by JingyaHuang** [comment]
Hi @AdamLouly , thanks a lot for reporting it. The contribution will be super helpful!

**Comment by prathikr** [comment]
@JingyaHuang any updates on this issue? I am also running into it.

**Comment by JingyaHuang** [comment]
Hi @prathikr , Adam has opened a PR for fixing it #1586 .

**Comment by nvijayrania** [comment]
Hi @JingyaHuang ,
Could you please confirm what is the last stable version which I can use with latest transformers(4.36.2) which doesn't have the fsdp issue? Tried 1.16.0, it throws the same error, or is there any plan to release the patch?

**Comment by JingyaHuang** [comment]
Hi @nvijayrania, I just merged the fix contributed by @AdamLouly, `ORTTrainer` shall work as expected if you build optimum from source. We will plan a patch release soon (but unfortunately not this week as team members are OOO this week.
