### ISSUE TITLE
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.

### ISSUE THREAD

**Issue by patientx** [huggingface/optimum#1556]
### System Info

windows 10 - ryzen 3600x - 16 gb ddr4-3000 - python  3.10 - latest optimum inside a venv

### Information

When I try to convert a model to openvino using 

optimum-cli export openvino -m "d:\sdxl\LCMphoton" "d:\sdxl\LCMphotonov"

I have this error : 
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.

I am converting standard sd1.5 models to lcm with lora locally and want to convert that to openvino. I have local models which are not present on huggingface and it takes forever for me to upload there (only 1-2 megabytes max) Can we somehow use local models that have the same directory structure as hf ?
```

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

optimum-cli export openvino -m "d:\sdxl\LCMphoton" "d:\sdxl\LCMphotonov"

### Expected behavior

I want to be able to convert local models without having to download from huggingface.

**Comment by chrisjudevine** [comment]
you need to add --task stable-diffusion
optimum-cli export openvino --task stable-diffusion -m "d:\sdxl\LCMphoton" "d:\sdxl\LCMphotonov"

**Comment by patientx** [comment]
thanks !
