### ISSUE TITLE
Add support for Chatglm2 & qwen onnx models

### ISSUE THREAD

**Issue by manishghop** [huggingface/optimum#1583]
### Feature request

Need to export ChatGLM2 & Qwen models to onnx using hf optimum.

ChatGLM2: model-card-> [https://huggingface.co/THUDM/chatglm2-6b](https://github.com/huggingface/optimum/issues/url)
Qwen: model-card-> [https://huggingface.co/Qwen/Qwen-7B-Chat](https://github.com/huggingface/optimum/issues/url)

### Motivation

I would like to make the process of exporting llm models to onnx simpler. There should be a generic boilerplate code which can export the models to onnx by simply passing hugging_face model_id.

### Your contribution

I have this piece of code for the export: I'm using this code to export chatglm2: [https://gist.github.com/manishghop/9be5aee6ed3d7551c751cc5d9f7eb8c3](https://github.com/huggingface/optimum/issues/url)
i use it for both chatglm2 & qwen by simply updating model_id.

Is there a way to run the inference of these onnx models?

**Comment by MingkangW** [comment]
I used your file to convert Qwen-7B-Chat and MindChat Qwen-7B-v2, but failed. Qwen-7B-Chat reported an error of "Unsupported type for attn_mask: 15" during the conversion phase. MindChat Qwen 7B-v2 reported an error during the validation phase as "INVALID ARGUENT: Invalid Feed Input Name: attention_mask.". I mainly want to convert MindChat Qwen 7B-v2, but I am a beginner and don't know how to do it. Can you help me?

**Comment by manishghop** [comment]
@MingkangW , I haven't tried running qwen-7b-chat model.

**Comment by manishghop** [comment]
closing as its resolved.

**Comment by Lavrikov** [comment]
Hi, how it was resolved? I have same problem with llama3
