### ISSUE TITLE
Table Transformer to ONNX

### ISSUE THREAD

**Issue by balajiChundi** [huggingface/optimum#1604]
### Feature request

Hi all,
I am trying to convert Table-transformer model from transformers(pretrained) to ONNX. Error reads something like " 'table-transformer' is not a supported format.

Is there any way to convert table-transformer (TATR) to ONNX model. Any help would be cherished.
Thanks. 

### Motivation

Motivation for this is, I am working on developing a light weight table structure recognition model, ONNX model would help me in that regard.

### Your contribution

None

**Comment by fxmarty** [comment]
Thank you, `table-transformer` model is supported in Transformers (https://huggingface.co/docs/transformers/main/en/model_doc/table-transformer) but not yet in the ONNX export. Adding it to my todo :)

**Comment by liebkne** [comment]
+1

**Comment by fxmarty** [comment]
Hi @balajiChundi, @liebkne the support was added in https://github.com/huggingface/optimum/pull/1616
