### ISSUE TITLE
XENOVA conversion issues

### ISSUE THREAD

**Issue by gidzr** [huggingface/optimum#1608]
### System Info

```shell
using the requirements.txt in Xenova for environment. 

https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt
```

### Who can help?

@xenova 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

"Error while initializing BPE: Token `_</w>` out of vocabulary"

### Expected behavior

Been trying to run blenderbot90, 400, 1b distilled.

Have had lots of issues, but I'll start with this one.

version 1 attempt, and loading from local after git-large file from HF repo.

   tokenizer = AutoTokenizer.from_pretrained(model)
   model = ORTModelForSeq2SeqLM.from_pretrained(model)
   inputs = tokenizer("what is a black hole", return_tensors="pt")
   gen_tokens = model.generate(**inputs)
   response = tokenizer.batch_decode(gen_tokens)

version 2 attempt, directly repo using pipeline

   from transformers import AutoTokenizer, pipeline
   from optimum.onnxruntime import ORTModelForSeq2SeqLM
   tokenizer = AutoTokenizer.from_pretrained("Xenova/blenderbot_small-90M")
   model = ORTModelForSeq2SeqLM.from_pretrained("Xenova/blenderbot_small-90M")
   onnx_pipe = pipeline("conversational", model=model, tokenizer=tokenizer)
   text = "what is a black hole"
   response = onnx_pipe (text)
   
   
Both cases getting this error: "Error while initializing BPE: Token `_</w>` out of vocabulary"

**Comment by xenova** [comment]
Hi there 👋 You can get around this by using the slow tokenizer with:
```py
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("Xenova/blenderbot_small-90M", use_fast=False)
```

**Comment by gidzr** [comment]
Awesome, thanks!.. will test this out shortly..

Also, was also trying to run the non-pipeline ORT approach using repo, but getting this error, which I'm sure is a basic one but can't find anything in the docs.

What is the correct approach to reference the model from repo, in the onnx folder where there are multiple versions?

model ="Xenova/blenderbot_small-90M" from the repo, and getting error: "Too many ONNX model files were found in Xenova/blenderbot-400M-distill, specify which one to load by using the encoder_file_name argument."

   tokenizer = AutoTokenizer.from_pretrained(model )
   model = ORTModelForSeq2SeqLM.from_pretrained(model )
   inputs = tokenizer("My name is Arthur and I live in", return_tensors="pt")
   gen_tokens = model.generate(**inputs,do_sample=True,temperature=0.9, min_length=20,max_length=20)
   response = tokenizer.batch_decode(gen_tokens)


I have tried adding "encoder_file_name=encoder_model_quantized.onnx", and "encoder_file_name=onnx/encoder_model_quantized.onnx" and trying to use the subfolder="onnx".. but none of these are working for me.

**Comment by gidzr** [comment]
Found it:
   model = ORTModelForSeq2SeqLM.from_pretrained(mname, subfolder="onnx", decoder_file_name="decoder_model_quantized.onnx", encoder_file_name="encoder_model_quantized.onnx")
