### ISSUE TITLE
AttributeError: 'ORTModelForCausalLM' object has no attribute 'to' - when running in GPU

### ISSUE THREAD

**Issue by axsaucedo** [huggingface/optimum#161]
Following [this unit test](https://github.com/huggingface/optimum/blob/81b85fa656730b3e0fb7b792781ff072d3f702cb/tests/onnxruntime/test_modeling_ort.py#L458-L463) I was able to successfully run the text-generation with the dummy model, however when I run it with the actual GPT2 model I get an inconsistency of GPU / CPU resources - namely I run:
```python
model_id = "gpt2"
onnx_model = ORTModelForCausalLM.from_pretrained(model_id, from_transformers=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)

pp = pipeline("text-generation", model=onnx_model, tokenizer=tokenizer)
text = "My Name is Philipp and i live"
outputs = pp(text)
```

However I get the following GPU/CPU error:

```
File ~/miniconda3/envs/optimum-mlserver/lib/python3.8/site-packages/transformers/generation_utils.py:587, in GenerationMixin._expand_inputs_for_generation(input_ids, expand_size, is_encoder_decoder, attention_mask, encoder_outputs, **model_kwargs)
    584     model_kwargs["token_type_ids"] = token_type_ids.index_select(0, expanded_return_idx)
    586 if attention_mask is not None:
--> 587     model_kwargs["attention_mask"] = attention_mask.index_select(0, expanded_return_idx)
    589 if is_encoder_decoder:
    590     if encoder_outputs is None:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

```

When I change the pipeline unfortunately I get an error where the ORT model does not support the to function (and then if that is circumvented there are other issues like the ORT function does not support config param, etc. Namely if I upate the pipeline to `pp = pipeline("text-generation", model=onnx_model, tokenizer=tokenizer, device=0)` - then the error is:
```
File ~/miniconda3/envs/optimum-mlserver/lib/python3.8/site-packages/transformers/pipelines/base.py:757, in Pipeline.__init__(self, model, tokenizer, feature_extractor, modelcard, framework, task, args_parser, device, binary_output, **kwargs)
    755 # Special handling
    756 if self.framework == "pt" and self.device.type == "cuda":
--> 757     self.model = self.model.to(self.device)
    759 # Update config with task specific parameters
    760 task_specific_params = self.model.config.task_specific_params

AttributeError: 'ORTModelForCausalLM' object has no attribute 'to'
```
For completeness I am getting the notice The model 'ORTModelForCausalLM' is not supported for text-generation.  - is that expected or does that suggest my transformers/hugging-face library is also not compatible with the latest live branch of optimum? I am using the following dependencies:
```
optimum (from main)
huggingface==0.0.1
huggingface-hub==0.5.1
transformers==4.18.0
```

**Comment by lewtun** [comment]
> I still cannot define `device=X` in the pipeline parametres, however I can confirm that it runs automatically in GPU, so it's not necessary. Would it still be required to ensure that the ORT models support the `to(...)` as well as other params like `config`? It's not currently a blocker from our side but just wanted to highlight.

Yes, currently the `device` arg can't be set in the `pipeline()` function for `ORTModelForXxx` classes - it's on our TODO list and will hopefully be added soon :)

And thanks for opening a new issue about the warning - that really helps for tracking!
