### ISSUE TITLE
KeyError: 'phi model type is not supported yet in NormalizedConfig.

### ISSUE THREAD

**Issue by eaidova** [huggingface/optimum#1614]
### System Info

```shell
optimum 1.16.1
platform ubuntu-20
python python3.8
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

due to missing NormalizedConfig registration for phi model, I can not load model using optimum.intel.openvino.OVModelForCausalLM:

```python
from optimum.intel.openvino import OVModelForCausalLM

model_id = "susnato/phi-1_5_dev"
ov_model = OVModelForCausalLM.from_pretrained(model_id, export=True, compile=False)
```
as a workaround, if I add before creating the model these lines:

```python
from optimum.utils import NormalizedTextConfig, NormalizedConfigManager

NormalizedConfigManager._conf['phi'] = NormalizedTextConfig
```
it can be successfully loaded.
I suppose that these lines missed in 
https://github.com/huggingface/optimum/blob/main/optimum/utils/normalized_config.py#L210
as it defined in OnnxExportConfig https://github.com/huggingface/optimum/blob/main/optimum/exporters/onnx/model_configs.py#L253 https://github.com/huggingface/optimum/blob/main/optimum/exporters/tasks.py#L816

### Expected behavior

model converted and loaded without errors

**Comment by fxmarty** [comment]
Hi @eaidova, this should be fixed with https://github.com/huggingface/optimum/pull/1625
