### ISSUE TITLE
Cannot convert sentence transformer model properly

### ISSUE THREAD

**Issue by leodalcin** [huggingface/optimum#1621]
### System Info

```shell
Optimum Version = 1.16.1
```

### Who can help?

@michaelbenayoun 
@fxmarty

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

When running:
`optimum-cli export onnx -m sentence-transformers/distiluse-base-multilingual-cased-v2 --task feature-extraction ./models/distiluse-base-multilingual-cased-v2`

I get:
```
...
The ONNX export succeeded with the warning: The exported ONNX model does not have the exact same outputs as what is provided in SentenceTransformersTransformerOnnxConfig. Difference: onnx::Shape_530, onnx::Shape_233, onnx::Shape_332, onnx::Shape_431, onnx::Shape_629, 764.
...
```

And afterwards when i try running the inference session with the generated .onnx model i get:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Expand node. Name:'/1/Expand' Status Message: invalid expand shape
```

It seems like the model is not being properly converted. I'm currently trying to figure out why exactly.

### Extra context:
- This pr seems to have added support to sentence-transformers models, maybe something is missing: https://github.com/huggingface/optimum/pull/1589
- To generate the runtime session error I used this script and changed the model names and exported model path: https://github.com/huggingface/optimum/issues/1519#issuecomment-1854780869
- The same error occurs using node.js onnx runtime, so I assume the model is not exported properly.

### Expected behavior

The model is exported properly and generates the same results as using Sentence transformers directly.

**Comment by xenova** [comment]
Could you try remove `--task feature-extraction` from the conversion command?

**Comment by xenova** [comment]
I can confirm this is also an issue with [aiknowyou/all-mpnet-base-questions-clustering-en](https://huggingface.co/aiknowyou/all-mpnet-base-questions-clustering-en) too, which produces this error:
```
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 551, in main_export
    _, onnx_outputs = export_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 753, in export_models
    export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/convert.py", line 884, in export
    config.fix_dynamic_axes(output, device=device, input_shapes=input_shapes, dtype=dtype)
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/base.py", line 306, in fix_dynamic_axes
    session = InferenceSession(model_path.as_posix(), providers=providers, sess_options=session_options)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from models/aiknowyou/all-mpnet-base-questions-clustering-en/model.onnx failed:This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (/0/auto_model/encoder/Add_1_output_0) of operator (Min) in node (/0/auto_model/encoder/Min) is invalid.
```

 cc @fxmarty @tomaarsen

**Comment by fxmarty** [comment]
Hi @leodalcin, this is fixed in https://github.com/huggingface/optimum/pull/1632.

@xenova your issue seem different, having a look

**Comment by techthiyanes** [comment]
@leodalcin you should be able to use ORTModelForCustomTasks to export sbert models as ONNX. And kindly use below article to create mean embeddings as similar as sbert: 
https://www.philschmid.de/optimize-sentence-transformers
