### ISSUE TITLE
LayoutLMV3 usage

### ISSUE THREAD

**Issue by techthiyanes** [huggingface/optimum#1626]
### Feature request

Kindly include LayoutLMV3 usage for token classification tasks.

### Motivation

Kindly include LayoutLMV3 usage for token classification tasks.

### Your contribution

NA

**Comment by fxmarty** [comment]
Hi @techthiyanes, do you mean ONNX export and inference?

**Comment by techthiyanes** [comment]
> Hi @techthiyanes, do you mean ONNX export and inference?

Hi @fxmarty  Thank you for your response. I'm able to export the model in ONNX using ORTModelForTokenClassification but I'm unable to make successful inference using the same. Could you please share the code snipper for the inference using ORTModelForTokenClassification for LayoutLMV3 model on token classification? 
At the same time. I'm able to make successful inference using InferenceSession.run()

**Comment by fxmarty** [comment]
I see. Indeed `ORTModelForTokenClassification` is currently not tested for layoutlmv3 (see https://github.com/huggingface/optimum/blob/8c6b6b602e8a458a67372a175dd027a4546c2fa0/tests/onnxruntime/test_modeling.py#L1815-L1817).

Instead, you can use for now [ORTModelForCustomTasks](https://huggingface.co/docs/optimum/main/en/onnxruntime/package_reference/modeling_ort#optimum.onnxruntime.ORTModelForCustomTasks) that is able to handle ONNX modes with arbitrary inputs/outputs.


```python
from transformers import AutoProcessor, AutoModelForTokenClassification
from datasets import load_dataset
from optimum.onnxruntime import ORTModelForCustomTasks

processor = AutoProcessor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=False)
model = AutoModelForTokenClassification.from_pretrained("microsoft/layoutlmv3-base", num_labels=7)

dataset = load_dataset("nielsr/funsd-layoutlmv3", split="train")
example = dataset[0]
image = example["image"]
words = example["tokens"]
boxes = example["bboxes"]
word_labels = example["ner_tags"]

encoding = processor(image, words, boxes=boxes, word_labels=word_labels, return_tensors="pt")

outputs = model(**encoding)

# Using ONNX Runtime:
ort_model = ORTModelForCustomTasks.from_pretrained("/home/fxmarty/hf_internship/optimum/layoutlmv3_onnx", num_labels=7)

outputs = ort_model(**encoding)
```

**Comment by techthiyanes** [comment]
@fxmarty  Thank you for your kindly response. I'm able to create the successful inference using custom tasks. Hence closing the issue.

**Comment by rubenaros** [comment]
Hi @techthiyanes , @fxmarty Thanks for your answers. Can you share the the code for save the LayoutlmV3 in ONNX format?  I have troubles with that.  I think is a problem with library version.

Thanks in advance

**Comment by fxmarty** [comment]
Hi @rubenaros, feel free to open an other issue with a reproduction & details about your environment (optimum, torch, ort, transformers versions, etc.).

Here's an end to end working code (using https://huggingface.co/nielsr/layoutlmv3-finetuned-funsd):

```
optimum-cli export onnx -m nielsr/layoutlmv3-finetuned-funsd layoutlm_v3_onnx
```

and

```python
from transformers import AutoProcessor, AutoModelForTokenClassification
from datasets import load_dataset
from optimum.onnxruntime import ORTModelForCustomTasks
import torch

processor = AutoProcessor.from_pretrained("nielsr/layoutlmv3-finetuned-funsd", apply_ocr=False)
model = AutoModelForTokenClassification.from_pretrained("nielsr/layoutlmv3-finetuned-funsd")

dataset = load_dataset("nielsr/funsd-layoutlmv3", split="train")
example = dataset[0]
image = example["image"]
words = example["tokens"]
boxes = example["bboxes"]
word_labels = example["ner_tags"]

encoding = processor(image, words, boxes=boxes, word_labels=word_labels, return_tensors="pt")

outputs = model(**encoding)

# Using ONNX Runtime:
ort_model = ORTModelForCustomTasks.from_pretrained("/path/to/layoutlm_v3_onnx")

ort_outputs = ort_model(**encoding)

assert torch.allclose(outputs.logits, ort_outputs["logits"], atol=1e-4)
```
