### ISSUE TITLE
Clarity on the convert.py for a model to ONNX.py.. documentation issue

### ISSUE THREAD

**Issue by gidzr** [huggingface/optimum#1657]
### Feature request

I need some help understanding how this script is supposed to be run / implemented?

https://github.com/huggingface/optimum/blob/main/optimum/exporters/onnx/convert.py

Questions:
1. is this already included when I pip install optimum? .. which is implemented using the instructions at:
https://huggingface.co/docs/optimum/onnxruntime/usage_guides/quantization#quantizing-a-model-to-be-used-with-optimums-cli
2. or is it the script that's called on from the modal.save when inferencing/calling onnx model?
3. or is this a separate script that can be called independently like the convert.py that xenova has?

Also, in order to run the optimum/exporters/onnx/convert.py script, do I need to download the full exporters folder, just the onnx folder, or can I just copy-paste the script and run that indepdently?

Much appreciated

### Motivation

Deeper understanding to use the resources in this github

### Your contribution

None

**Comment by fxmarty** [comment]
Hi @gidzr, you should be able just to do `pip install optimum` and use `optimum-cli export onnx --help`. More details here: https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model

I believe @xenova relies on Optimum ONNX export but has its own quantization script.

> Also, in order to run the optimum/exporters/onnx/convert.py script, do I need to download the full exporters folder, just the onnx folder, or can I just copy-paste the script and run that indepdently?

Normally you don't need to copy anything - if you install through `pip` you can just run the command above. Of course you would like do to an editable install you can clone the repo and use `pip install -e .`.

**Comment by gidzr** [comment]
Hi @fxmarty, thanks kindly for that.

Yep re xenova's own export. I'll drop him a line on that. I'm currently running it as a standalone script as xenova's version includes params for --per_channel true --reduce_range true, which made a big difference on the quantisation reliability. I've had the best results with his script.

I'm sure it's on the roadmap, but would be great to see a unified package that incorporates a consistent set of arguments with all the good stuff from optimum and xenova's approaches available a separate pip module or online at https://huggingface.co/spaces/onnx/export would be great. But there's definitely few different flavours at the moment, including in-inference model.save version. Probably a full-time project to consolidate all of that.
