### ISSUE TITLE
Non-pinned Transformers Version Incompatability

### ISSUE THREAD

**Issue by hakan458** [huggingface/optimum#1675]
### System Info

```shell
Optimum version 1.11.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Using optimum version 1.11.0 - since the dependencies specify `transformers[sentencepiece]>=4.26.0`, the recent release to transformers, `4.37.0`, removed support for Torch 1.10, which now causes issues when running Optimum 1.11.0

```
RuntimeError: Failed to import optimum.exporters.onnx.__main__ because of the following error (look up to see its traceback):
cannot import name 'is_torch_less_than_1_11' from 'transformers.pytorch_utils' (/opt/conda/default/lib/python3.10/site-packages/transformers/pytorch_utils.py)
```

https://github.com/huggingface/transformers/pull/28207/files#diff-dba11d4c8294d6ccc1f120918ba0921738444244db666e0bbde15dc9eb212128L36
This PR was included in transformers 4.37.0 as can be seen in the release notes 

I'm sure there are multiple issues similar to this due to unpinned deps. 

### Expected behavior

Able to run any version of Optimum without unpinned deps breaking compatibility completely

**Comment by tomaarsen** [comment]
I am experiencing the same issue.

**Comment by fxmarty** [comment]
Hi @hakan458 @tomaarsen, could you try Optimum 1.16.2 that includes https://github.com/huggingface/optimum/pull/1641?

**Comment by pakelley** [comment]
Using 1.16.2 seemed to fix this for me (and I work with @hakan458 and am pretty sure this is for the same job he was seeing this on 🙂)
