### ISSUE TITLE
Issue converting owlv2 model to ONNX format

### ISSUE THREAD

**Issue by n9s8a** [huggingface/optimum#1713]
Hi Team,

I hope this message finds you well.

I've been working with the owlv2 model and have encountered an issue while attempting to convert it into ONNX format using the provided command:
`! optimum-cli export onnx -m google/owlv2-base-patch16 --task 'zero-shot-object-detection' --framework 'pt' owlv2_onnx`

Unfortunately, I'm facing the following error:

`ValueError: Trying to export a owlv2 model, that is a custom or unsupported architecture, but no custom onnx configuration was passed as `custom_onnx_configs`.`

As I am relatively new to this process, I'm unsure about the necessity and usage of custom ONNX configuration. Could you please provide some guidance on how to address this issue? Any assistance or insights would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by fxmarty** [comment]
Hi @n9s8a the message `ValueError: Trying to export a owlv2 model, that is a custom or unsupported architecture, but no custom onnx configuration was passed as `custom_onnx_configs`. Please refer to https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models for an example on how to export custom models. Please open an issue at https://github.com/huggingface/optimum/issues if you would like the model type owlv2 to be supported natively in the ONNX export.`

means that owlv2 ONNX export is not yet supported in Optimum. I'll add it to my todo

**Comment by n9s8a** [comment]
Hi @fxmarty, Thankyou for your response and for clarifying the situation regarding the owlv2 ONNX export. I'm using owlv2 model in my project. Could you please provide an estimated timeline for when this support might be available?

Additionally, in the meantime, would it be feasible to use any external methods or workarounds to achieve ONNX conversion for the owlv2 model?

Your insights on these matters would be greatly appreciated.

**Comment by fxmarty** [comment]
Hi @n9s8a, https://github.com/huggingface/optimum/pull/1689 is merged. I also recommend you to use Transformers from source for now as https://github.com/huggingface/transformers/pull/29326 fixed a bug in the ONNX export of owlvit/owlv2 and is not yet in a release.

```
optimum-cli export onnx -m google/owlv2-base-patch16 --task 'zero-shot-object-detection' --framework 'pt' owlv2_onnx
```
now works.

**Comment by SlowMonk** [comment]
(Where) bound to different types (tensor(double) and tensor(float) in node (/class_head/Where).

I faced this issue
