### ISSUE TITLE
Expose a SUPPORTED_OPTIMUM_TASKS analogous to SUPPORTED_TASKS

### ISSUE THREAD

**Issue by axsaucedo** [huggingface/optimum#172]
Currently having access to the `transformers.pipelines.SUPPORTED_TASKS` is quite useful for application development to ensure access to the respective classes based on relevant tasks is done correctly.

For explicitness the structure of the `SUPPORTED_TASKS` object is:

```python
SUPPORTED_TASKS = {
    "audio-classification": {
        "impl": AudioClassificationPipeline,
        "tf": (),
        "pt": (AutoModelForAudioClassification,) if is_torch_available() else (),
        "default": {"model": {"pt": "superb/wav2vec2-base-superb-ks"}},
        "type": "audio",
    },
    "automatic-speech-recognition": {
        "impl": AutomaticSpeechRecognitionPipeline,
        "tf": (),
   # ...etc
```

At the moment we had to create our own `SUPPORTED_OPTIMUM_TASKS` to map each respective task to their relevant class, as below. However it would be more robust if we are able to have access to an Optimum object that we can rely on to ensure we are providing access to the relevant classes in a robust way.

```python
SUPPORTED_OPTIMUM_TASKS = {
    "feature-extraction": ORTModelForFeatureExtraction,
    "sentiment-analysis": ORTModelForSequenceClassification,
    "ner": ORTModelForTokenClassification,
    "question-answering": ORTModelForQuestionAnswering,
    "text-generation": ORTModelForCausalLM,
}
```

**Comment by philschmid** [comment]
Hey @axsaucedo, 

We already have a `SUPPORTED_TASKS` map available in `optimum`. See [optimum.pipelines](https://github.com/huggingface/optimum/blob/6aa47f96be4644acdfbaa2a006b891ae1bad5474/optimum/pipelines.py#L32)
You should be able to access it with. 

```python
from optimum.pipelines import SUPPORTED_TASKS
```

P.S. You can also use directly the `pipeline` class from `optimum` which checks and makes sure that the model and task are supported. Just switch your import.
```diff
- from transformers import pipeline
+ from optimum.pipelines import pipeline
```

**Comment by axsaucedo** [comment]
Thank you for pointing this out, that's exactly what we were looking for - closing this issue as we'll be able to use this one instead
