### ISSUE TITLE
'gemma is not supported yet with the onnx backend' - Exporting on-the-fly to onnx

### ISSUE THREAD

**Issue by RYangData** [huggingface/optimum#1724]
### Feature request

![image](https://github.com/huggingface/optimum/assets/53895743/1267e66b-aba4-4d19-9763-b3a05d2ef854)

### Motivation

I'm new to optimising for inference, this would benefit me other beginners greatly in evaluating runtimes and costs expected for many models. 

### Your contribution

- I could given time and more familiarity going forward - but would like this to be integrated quickly !

**Comment by fxmarty** [comment]
Hi @RYangData thank you, Gemma ONNX support was added in https://github.com/huggingface/optimum/pull/1714 only available from the `main` branch for now: `pip install git+https://github.com/huggingface/optimum.git`

**Comment by RYangData** [comment]
Thanks - this on collab GPU instance (T4) this is exactly what happened. So did the below on CPU instance:
![image](https://github.com/huggingface/optimum/assets/53895743/028f7356-3200-4213-b688-d7211aa87a09)

Then i get 
![image](https://github.com/huggingface/optimum/assets/53895743/fa8ffdd5-ef05-4e7d-b601-836d8128e288)


when i do:
![image](https://github.com/huggingface/optimum/assets/53895743/8745399c-3680-46f1-b9ba-d0ae0763d09e)

I remove this and i think it goes to CPU as inference using takes forever. 
also the eblow happens:
![image](https://github.com/huggingface/optimum/assets/53895743/4abacbc2-86cc-45fe-a645-1cf18eb8a2e7)

Thanks for your help so far!!

**Comment by fxmarty** [comment]
Are you installing `onnxruntime-gpu` on colab? To be fair, I never tested ONNX Runtime on colab with GPU, maybe @merveenoyan that's the same issue you had?

**Comment by merveenoyan** [comment]
@RYangData I also had the same problem, try to check ONNX Runtime providers: 
```python
import onnxruntime

providers = onnxruntime.get_available_providers()
print(providers)
```
If you see CUDA there, yet still have the above error, try to adjust CUDA and CuDNN version to the compatible ONNX versions. Sometimes ONNX can't access to CUDA due to dependency incompatibility, hence the problem.
Moreover, if this doesn't work, uninstall `onnx` and the library for ONNX Runtime, and only install `onnxruntime-gpu` **first** and then `onnx`. 
Unfortunately this is quite tricky to get right and I wish you good luck 🍀

**Comment by RYangData** [comment]
Hey @merveenoyan, thanks for assistance. 

I looked at https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements to find the compatible onnxruntime-gpu. I checked colab and found CUDA 12.2 so installed onnx-runtime-gpu as:
```python
!pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
!pip install onnx
!pip install git+https://github.com/huggingface/optimum.git
```
I know get "CUDAExecutionProvider" as an option when i run :
```python
import onnxruntime

providers = onnxruntime.get_available_providers()
print(providers)

#['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
```
I try to load the model with:
```python
ONNX_MODEL_DIR = "/content/drive/MyDrive/2024_01_Illum_LLM_Jan_v1.0/onnx/model_3_25_02_24_512_1999_10_epochs_torch"

ort_model = ORTModelForCausalLM.from_pretrained(
  ONNX_MODEL_DIR,
  provider="CUDAExecutionProvider",
)
```
And I'm met with this error:
![image](https://github.com/huggingface/optimum/assets/53895743/abfbbfe5-3b2b-493c-9fbc-2a824a7c9be9)

So I run:
```python
ort_model = ORTModelForCausalLM.from_pretrained(
  ONNX_MODEL_DIR,
  use_cache=False,
  use_io_binding=False,
  # export=True,
  provider="CUDAExecutionProvider",
)

ort_model.device
#device(type='cpu')

ort_model.to("cuda")
# use_io_binding was set to False, setting it to True because it can provide a huge speedup on GPUs. It is possible to disable this feature manually by setting the use_io_binding attribute back to False <optimum.onnxruntime.modeling_decoder.ORTModelForCausalLM at 0x7c7de8faf1c0>

ort_model.device
#use_io_binding was set to False, setting it to True because it can provide a huge speedup on GPUs. It is possible to disable this feature manually by setting the use_io_binding attribute back to False. device(type='cuda', index=0)
```
Finally I try to use the model for inference:
```python
inputs = tokenizer([example_article], return_tensors="pt").to(ort_model.device)
outputs = ort_model.generate(**inputs, max_length=1000)
```
In which I'm met with this error:
![image](https://github.com/huggingface/optimum/assets/53895743/7bf24bd2-7362-4bbd-a63d-ec1ffaa282eb)

It seems like the model isnt being loaded onto GPU..
![image](https://github.com/huggingface/optimum/assets/53895743/75c97518-ae1f-4f2d-8ce5-a82fe915ec7d)

Any additional help will be helpful!

**Comment by RYangData** [comment]
![image](https://github.com/huggingface/optimum/assets/53895743/0866ae61-733a-489b-81d7-a40cbea2ef9f)

@fxmarty  i get met with this atm. Thanks for the help so far though

**Comment by fxmarty** [comment]
@ryangdata oh right, gemma was not included in https://github.com/huggingface/optimum/releases/tag/v1.17.0. You need to install optimum from source.
