### ISSUE TITLE
Gemma Onnx suuport 

### ISSUE THREAD

**Issue by Kaya-P** [huggingface/optimum#1728]
### System Info

```shell
My system currently is 
python = 3.8 
optimum-intel : optimum-1.18.0.dev0
```

### Who can help?

@JingyaHuang  @echarlaix 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

I am following the provided examples on #1714 but am running into some issues.
when I run 
`optimum-cli export onnx -m google/gemma-2b gemma_onnx`

I get the following error 
![image](https://github.com/huggingface/optimum/assets/61036085/054916e1-5087-4d7b-a5ee-c90a9865d288)

When I execute the python script provided I get the following error

![image](https://github.com/huggingface/optimum/assets/61036085/a7231029-c984-4267-8b82-5a7b59455e2b)

### Expected behavior

The expected behavior is for the model to compile and be stored in onnx form

**Comment by fxmarty** [comment]
Answered on the other thread

**Comment by tchen48** [comment]
@fxmarty can you give me your version of optimum and transformers? I am running in the latest version and still have the error:

ValueError: Trying to export a gemma model, that is a custom or unsupported architecture, but no custom onnx configuration was passed as `custom_onnx_configs`. Please refer to https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models for an example on how to export custom models. Please open an issue at https://github.com/huggingface/optimum/issues if you would like the model type gemma to be supported natively in the ONNX export.

I am using the same command that you are using

**Comment by andyyeh75** [comment]
@fxmarty I encountered the same issue with this project as well while adding 'google/gemma-2b-it' as a LLM option.
[openvino-llm-chatbot-rag](https://github.com/yas-sim/openvino-llm-chatbot-rag)

cc @tchen48

**Comment by IlyasMoutawwakil** [comment]
you'll need to install from main `pip install optimum@git+https://github.com/huggingface/optimum.git` for gemma support

**Comment by fxmarty** [comment]
Closing as supported on main.
