### ISSUE TITLE
Cannot download ONNX external data file from Hugging Face Hub

### ISSUE THREAD

**Issue by kazssym** [huggingface/optimum#1736]
### System Info

```shell
Optimum 1.17.1, Windows 11, Python 3.11.8
```

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```python
from optimum.onnxruntime import ORTModelForCausalLM
model = ORTModelForCausalLM.from_pretrained(
    "kazssym/stablelm-3b-4e1t-onnx-fp32@test-optimum",  # model.onnx_data (downloaded but not found)
    #"kazssym/stablelm-3b-4e1t-onnx-fp32",  # model.onnx.data (not downloaded)
    cache_dir="cache/",
    force_download=True,
)
```

### Expected behavior

The ONNX model is downloaded but stop with an error:

KeyError: 'stablelm model type is not supported yet in NormalizedConfig. Only albert, bart, bert, blenderbot, blenderbot-small, bloom, falcon, camembert, codegen, cvt, deberta, deberta-v2, deit, distilbert, donut-swin, electra, encoder-decoder, gpt2, gpt-bigcode, gpt-neo, gpt-neox, llama, gptj, imagegpt, longt5, marian, mbart, mistral, mixtral, mt5, m2m-100, nystromformer, opt, pegasus, pix2struct, phi, poolformer, regnet, resnet, roberta, speech-to-text, splinter, t5, trocr, whisper, vision-encoder-decoder, vit, xlm-roberta, yolos, mpt are supported. If you want to support stablelm please propose a PR or open up an issue.'

**Comment by kazssym** [comment]
Error log
```
Traceback (most recent call last):
  File "E:\temp\stablelm-study-2\test_onnxruntime copy.py", line 5, in <module>
    model = ORTModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 662, in from_pretrained
    return super().from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\optimum\modeling_base.py", line 399, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\optimum\onnxruntime\modeling_decoder.py", line 514, in _from_pretrained
    onnx_model = onnx.load(str(model_cache_path), load_external_data=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\onnx\__init__.py", line 214, in load_model
    load_external_data_for_model(model, base_dir)
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\onnx\external_data_helper.py", line 65, in load_external_data_for_model
    load_external_data_for_tensor(tensor, base_dir)
  File "E:\temp\stablelm-study-2\.venv\Lib\site-packages\onnx\external_data_helper.py", line 45, in load_external_data_for_tensor
    with open(external_data_file_path, "rb") as data_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kazssym\\.cache\\huggingface\\hub\\models--kazssym--stablelm-3b-4e1t-onnx-fp32\\snapshots\\b9c9eecad782f82dbb163448019a7d2ea1c3f2f2\\model.onnx.data'
```

**Comment by fxmarty** [comment]
@kazssym I am not sure to understand the issue. The issue is not about downloading ONNX models with external data bot about stablelm not being supported, is that not? Would https://github.com/huggingface/optimum/pull/1719 fix this issue?

```python
from optimum.onnxruntime import ORTModelForCausalLM

model = ORTModelForCausalLM.from_pretrained("fxmarty/dummy-llama-1b-onnx")
```

works perfectly fine for me (https://huggingface.co/fxmarty/dummy-llama-1b-onnx/tree/main).

**Comment by kazssym** [comment]
> ```python
> from optimum.onnxruntime import ORTModelForCausalLM
> 
> model = ORTModelForCausalLM.from_pretrained("fxmarty/dummy-llama-1b-onnx")
> ```

Thank you for the information. I now understand that I failed to export my ONNX model with `optimum export onnx` and should add code to store the `.onnx_data` suffix somewhere in the exporter.

**Comment by kazssym** [comment]
> > ```python
> > from optimum.onnxruntime import ORTModelForCausalLM
> > 
> > model = ORTModelForCausalLM.from_pretrained("fxmarty/dummy-llama-1b-onnx")
> > ```
> 
> Thank you for the information. I now understand that I failed to export my ONNX model with `optimum export onnx` and should add code to store the `.onnx_data` suffix somewhere in the exporter.

I found a TODO comment here stating that we get the `.onnx.data` suffix when we use the optimizer:
https://github.com/huggingface/optimum/blob/fd47a73267c3a71ea4e3c02f92260ae61c5ae372/optimum/onnxruntime/optimization.py#L225
