### ISSUE TITLE
Performance with ORTModelForSequenceClassification is worse than with the original model

### ISSUE THREAD

**Issue by akepa** [huggingface/optimum#1756]
Hello,

I'm trying to optimize a model for production with optimum.onnxruntime and I'm getting a worse performance than with the original model. My original model is a fine tuned version of bert-base-multilingual-uncased, but I've been able to reproduce the same with a simpler example.

[performance.zip](https://github.com/huggingface/optimum/files/14585883/performance.zip)

In the example attached, I've compared three cases:
1. Inference using distilbert-base-uncased-finetuned-sst-2-english model "as is".
2. Inference using the model by exporting it with ORTModelForSequenceClassification
3. Inference with an optimized model using AutoOptimizationConfig.O2() configuration. 

And I've got the following inference times:
1. 50.8 ms ± 741 µs per loop (mean ± std. dev. of 7 runs, 200 loops each)
2. 73.3 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 200 loops each)
3. 66 ms ± 526 µs per loop (mean ± std. dev. of 7 runs, 200 loops each)

I've checked both optimum and ONNXRuntime documentation and I didn't see anything that could explain this performance degradation. 

I'm running the example in a containerized Jupyter Notebook with 2cpu and 16GB of RAM, on top of a g5.2xlarge EC2 instance with the following library versions.

onnx==1.15.0
onnxruntime==1.17.1
optimum==1.17.1
transformers==4.38.2

Has anyone faced a similar issue?

**Comment by fxmarty** [comment]
Hi @akepa, I can have a look. Did you close because you fixed the issue on you hand, or you gave up using ORT?

cc @IlyasMoutawwakil as you had good benchmark results with ORT I recall?

**Comment by IlyasMoutawwakil** [comment]
using the same script on a colab notebook I'm getting 20% faster inference with ORT
https://colab.research.google.com/drive/1Eu6vXkWDYk6N47exqXWYZXXyw45DIsPS?usp=sharing
