### ISSUE TITLE
Bettertransformers not working with TFAutomodelforsequenceclassification model

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/optimum#1794]
### System Info

```shell
python 3.8
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

I have the Tensorflow model object of ```TFAutomodelforsequenceclassification``` class

I want to convert it into Bettertransformers format via

```
model_name = "roberta-large"
model = TFAutomodelforsequenceclassification.from_pretrained(model_name).to(0)
from optimum.bettertransformer import BetterTransformer
bt_model = BetterTransformer.transform(model, keep_original_model=True)
```
But it is not working. Showing error
```
AttributeError: 'TFRobertaForSequenceClassification' object has no attribute 'training'
```
so is optimum bettertransformer is not compatible with TFAutomodelforsequenceclassification models?

### Expected behavior

I have the Tensorflow model object of ```TFAutomodelforsequenceclassification``` class

I want to convert it into Bettertransformers format via

```
model_name = "roberta-large"
model = TFAutomodelforsequenceclassification.from_pretrained(model_name).to(0)
from optimum.bettertransformer import BetterTransformer
bt_model = BetterTransformer.transform(model, keep_original_model=True)
```
But it is not working. Showing error
```
AttributeError: 'TFRobertaForSequenceClassification' object has no attribute 'training'
```
so is optimum bettertransformer is not compatible with TFAutomodelforsequenceclassification models?

**Comment by fxmarty** [comment]
Hi @pradeepdev-1995, BetterTransformer is specific to PyTorch models.

**Comment by pradeepdev-1995** [comment]
@fxmarty 
okay so can BetterTransformer improve inference speed in all kind of pytorch models
encoder models(bert family),decoder models(gpt,llama,mistral,falcon...) and encoder-decoder models(t5 family)?
