### ISSUE TITLE
Support Transformers >=4.40.0

### ISSUE THREAD

**Issue by saattrupdan** [huggingface/optimum#1822]
### The Issue

I would like to be able to load GPTQ models with the newest `transformers` version. This requires `optimum`, but `optimum` is not compatible with the newest `transformers` version.

### System Info

```shell
Linux, Python 3.11, Optimum 1.19.0
```

### Who can help?

@SunMarc 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```shell
pip install "transformers>=4.40.0" "optimum>=1.19.0"
```

### Expected behavior

No dependency conflict.

**Comment by SunMarc** [comment]
Hi @saattrupdan, transformers version have been pinned in the latest version of optimum. See PR [here](https://github.com/huggingface/optimum/pull/1764). I guess the easier solution for now is installing `optimum==1.18.0` in order to use gptq with transformers.

**Comment by saattrupdan** [comment]
> Hi @saattrupdan, transformers version have been pinned in the latest version of optimum. See PR [here](https://github.com/huggingface/optimum/pull/1764). I guess the easier solution for now is installing `optimum==1.18.0` in order to use gptq with transformers.

Thanks @SunMarc! I found that 1.18.0 still has the upper bound requirement, but 1.17.1 works. Thanks for that hotfix 🙂
