### ISSUE TITLE
how to change optimum temporary path ?

### ISSUE THREAD

**Issue by neonarc4** [huggingface/optimum#1855]
### Feature request

c drive less space

### Motivation

help to solve many issue

### Your contribution

dont know

**Comment by IlyasMoutawwakil** [comment]
Hi ! 
If I understand correctly you want to change the temporary directory used by `optimum` (through `tempfile`)
you can try [this solution](https://stackoverflow.com/a/59523396) to change python `tempfile`'s default temporary directory

**Comment by ivarflakstad** [comment]
Closing since you provided a solution and there hasn't been any further comments. Feel free to reopen if you disagree @IlyasMoutawwakil :)
