### ISSUE TITLE
Support for `torch.export.export`

### ISSUE THREAD

**Issue by kilianyp** [huggingface/optimum#1893]
### Feature request

torch has been pushing [`torch.export.export`](https://pytorch.org/docs/stable/export.html#torch-export) recently. Are there any plans to support that as alternative format to ONNX?

### Motivation

Not all users will want to export to onnx but to an `ExportedProgram`.

### Your contribution

first would like to clarify if this was even an option, but if yes, I could look into it.

**Comment by fxmarty** [comment]
@kilianyp Thank you. No it is not an option yet. Yes it should happen, I have no timeline though. This would be very useful.

**Comment by fxmarty** [comment]
If you would like to contribute this, happy to help review!
