### ISSUE TITLE
Not possible to configure GPU in pipelines nor leveraging batch_size parallelisation

### ISSUE THREAD

**Issue by axsaucedo** [huggingface/optimum#191]
When setting the `device` variable in the `pipeline` function/class to `>= 0`, an error appears `AttributeError: 'ORTModelForCausalLM' object has no attribute 'to' - when running in GPU`. This was initially reported in #161 so opening this issue to encompass supporting the `device` parameter in the ORT classes. This is important as otherwise it won't be possible to allow configuration of CPU/GPU similar to normal transformer libraries.

Is there currently a workaround to ensure that the class is run on GPU? By default it seems this woudl eb set in CPU even when GPU is available:
```python
>>> m = ORTModelForCausalLM.from_pretrained("gpt2", from_transformers=True)
>>> t = AutoTokenizer.from_pretrained("gpt2")
>>> pp = pipeline("text-generation", model=m, tokenizer=t)
>>> pp.device

device(type='cpu')
```

This is still the case even with the `optimum[onnxruntime-gpu]` package. I have validated by testing against a normal transformer with `batch_size=X` (ie `pp = pipeline("text-generation", model=m, tokenizer=t, batch_size=128)`) and it seems there is no optimization with parallel processing with optimum, whereas normal transformer is orders of magnitude faster (which is most likely as it's not utilizing the parallelism)

I can confirm that the model is loaded with GPU correctly:

```python
>>> m.device

device(type='cuda', index=0)
```

And GPU is configured correctly:

```python
>>> from optimum.onnxruntime.utils import _is_gpu_available
>>> _is_gpu_available()

True
```

Is there a way to enable GPU for processing with batching in optimum?

**Comment by lewtun** [comment]
Thanks for reporting this issue @axsaucedo! 

By default, the ORT models are run on a `CUDAExecutionProvider` ([docs](https://huggingface.co/docs/optimum/main/en/onnxruntime/modeling_ort#optimum.onnxruntime.ORTModel.load_model)) if a GPU is available, and you can verify this by accessing the ORT inference session as follows:

```python
m = ORTModelForCausalLM.from_pretrained("gpt2", from_transformers=True)
t = AutoTokenizer.from_pretrained("gpt2")
pp = pipeline("text-generation", model=m, tokenizer=t)
# Returns ['CUDAExecutionProvider', 'CPUExecutionProvider'] on GPU
pp.model.model.get_providers()
```

As a workaround to switch between GPU/CPU, one can set the inference session as follows:

```python
pp.model.model.set_providers(["CPUExecutionProvider"])
# Returns ['CPUExecutionProvider']
pp.model.model.get_providers()
```

Having said that, you're right that these settings aren't being propagated through to the `device` attribute of the `pipeline()` object - this is something we'll need to fix.

I can also confirm that running generations with the ORT model on GPU are ~5x slower than the native `transformers` variant. It might be related to the device issue in the `pipeline()`, but I'll need to dig deeper to pinpoint the issue.

**Comment by axsaucedo** [comment]
Ok I see thank you for the details @lewtun - I have been able to try it and validate that the model indeed is running with the cuda provider, however it seems it still does not seem to be using the batch_size for GPU parallelisation (may indeed be due to the `device=cpu` from the pipeline). More specifically I ran:

```python
from transformers.models.auto.tokenization_auto import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
from transformers import pipeline

m = ORTModelForCausalLM.from_pretrained("gpt2", from_transformers=True)
t = AutoTokenizer.from_pretrained("gpt2")

BATCH_SIZE = 128

pp = pipeline("text-generation", model=m, tokenizer=t, batch_size=BATCH_SIZE)

m.model.get_providers()
# >>> ['CUDAExecutionProvider', 'CPUExecutionProvider']

pp.model.model.set_providers(["CUDAExecutionProvider"])

pp.tokenizer.pad_token_id = [str(pp.model.config.eos_token_id)]

p(["hello" for i in range(1)])
# Takes N seconds...

p(["hello" for i in range(BATCH_SIZE)])
# Takes N * BATCHS_SIZE seconds...
```

For completeness, the normal model / pipeline would indeed process these in parallel and would end up performing orders of magnitude faster. Hope this provides useful context.

**Comment by Amy234543** [comment]
@lewtun  I can also confirm that running generations with the ORT model on GPU are ~5x slower than the native transformers

I want to ask whether the problem that the running speed of GPU is slower than that of native transformers has been solved?

**Comment by lewtun** [comment]
Hi @Amy234543 to speed up generation in the ORT models we need to add support for [IOBinding](https://onnxruntime.ai/docs/api/python/api_summary.html#iobinding) and [ORTValue](https://onnxruntime.ai/docs/api/python/api_summary.html#ortvalue). This is currently on the roadmap and you can track the issue here: https://github.com/huggingface/optimum/issues/260
