### ISSUE TITLE
TypeError: _unmask_unattended_patched() missing 1 required positional argument: 'unmasked_value' during ONNX export LLaMa

### ISSUE THREAD

**Issue by nvluxiaoz** [huggingface/optimum#1952]
### System Info

```shell
version: latest main or release
system: any
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Take any LLaMa model, 
`from optimum.exporters.onnx import main_export`
`main_export(args.model_dir,task="text-generation-with-past",output=args.output_dir,opset=17,dtype=args.dtype,device="cuda",framework="pt")
`

### Expected behavior

ONNX exported, but the above error arises, due to HF removed the argument, but optimum did not.

**Comment by MatthewChang** [comment]
I am also seeing this.

**Comment by parsa-pico** [comment]
same here when running this code :

from optimum.onnxruntime import ORTModelForCausalLM
ORTModelForCausalLM.from_pretrained("./llama3-q", export=True, provider="CUDAExecutionProvider",)
