### ISSUE TITLE
Latest Optimum library does not compatible with latest Transformers

### ISSUE THREAD

**Issue by lanking520** [huggingface/optimum#1969]
### System Info

```shell
Any system that can install those libraries
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

Try to install transformers along with optimum

### Expected behavior

Fix here? https://github.com/huggingface/optimum/blob/main/setup.py#L18

**Comment by IlyasMoutawwakil** [comment]
will be merged soon #1971
