### ISSUE TITLE
BetterTransformer for florence2

### ISSUE THREAD

**Issue by ksooklall** [huggingface/optimum#1995]
### Feature request

NotImplementedError: The model type florence2 is not yet supported to be used with BetterTransformer. Feel free to open an issue at https://github.com/huggingface/optimum/issues if you would like this model type to be supported.

### Motivation

Florence-2 is a small (compared to other vLLM) and widely used model thus a speed up in inference will be very helpful for everyone

### Your contribution

I can help with a PR but I would need some guidance.

**Comment by lieding** [comment]
+1 to offering to support export own fine-tuned version
