### ISSUE TITLE
Is it possible convert decoder_model_merged.onnx to tensorrt via trtexec command ? 

### ISSUE THREAD

**Issue by rungrodkspeed** [huggingface/optimum#2013]
At the first I convert whisper-tiny to onnx via optimum-cli
`optimum-cli export onnx --model openai/whisper-tiny --task automatic-speech-recognition-with-past whisper-tiny-onnx`

I got the some config, encoder and decoder_merged model

then I brought encoder and decoder_merged to convert to tensorrt via NGC version 23.09-py3, encoder not problem but decoder_merged got problem while converting.
`trtexec --onnx=/workspace/models/whisper-tiny-onnx/decoder_model_merged.onnx --saveEngine=/workspace/models/whisper-tiny-onnx/decoder_model_merged.plan`
the error happen : 
`[5] Assertion failed: (node.output().size() <= static_cast<int32_t>(outputs.size())) && "Node has more output tensors than TRT expected."`

![สกรีนช็อต 2024-09-04 005124](https://github.com/user-attachments/assets/c289f1fa-2174-4d8a-af68-ee9758a77c54)

Can someone help me about this or Have another ways for good practice ? Please . . .

**Comment by IlyasMoutawwakil** [comment]
Hi ! I would say this is a problem on trt side, it's unable to convert the model even though it's a valid onnx model.
You can try doing it with an unmerged model, i.e. encoder.onnx, decoder.onnx and decoder_with_past.onnx

**Comment by rungrodkspeed** [comment]
@IlyasMoutawwakil Thank you for your responding, I will try your practice and I recently found out about tensorrt-llm, I will explore more for other ways.

**Comment by IlyasMoutawwakil** [comment]
for trt-llm you can check [`optimum-nvidia`](https://github.com/huggingface/optimum-nvidia) 🤗
