### ISSUE TITLE
TypeError: QDQQuantizer.__init__() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by blacker521** [huggingface/optimum#2019]
### System Info

```shell
optimum  1.22.0.dev0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```python
from functools import partial
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTQuantizer, ORTModelForSequenceClassification
from optimum.onnxruntime.configuration import AutoQuantizationConfig, AutoCalibrationConfig

model_id = "distilbert-base-uncased-finetuned-sst-2-english"

# onnx_model = ORTModelForSequenceClassification.from_pretrained(model_id, export=True)
tokenizer = AutoTokenizer.from_pretrained("/mnt/nas_new/plms/bce-embedding-base_v1")
quantizer = ORTQuantizer.from_pretrained("./fp32")
qconfig = AutoQuantizationConfig.tensorrt(per_channel=True)

def preprocess_fn(ex, tokenizer):
    return tokenizer(ex["sentence"])

calibration_dataset = quantizer.get_calibration_dataset(
    "glue",
    dataset_config_name="sst2",
    preprocess_function=partial(preprocess_fn, tokenizer=tokenizer),
    num_samples=50,
    dataset_split="train",
)

calibration_config = AutoCalibrationConfig.minmax(calibration_dataset)

ranges = quantizer.fit(
    dataset=calibration_dataset,
    calibration_config=calibration_config,
    operators_to_quantize=qconfig.operators_to_quantize,
)

model_quantized_path = quantizer.quantize(
    save_dir="./output_opt",
    calibration_tensors_range=ranges,
    quantization_config=qconfig,
)
```

### Expected behavior

Save a quantified model

**Comment by IlyasMoutawwakil** [comment]
Hi, I exported the model (with cli and opset > 13), ran your script and it worked as expected. 
Please report which onnxruntime version you are using, the `mode` argument is no longer part of `QDQQuantizer` signature https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/qdq_quantizer.py#L129

```python
from functools import partial

from transformers import AutoTokenizer

from optimum.onnxruntime import ORTModelForSequenceClassification, ORTQuantizer
from optimum.onnxruntime.configuration import AutoCalibrationConfig, AutoQuantizationConfig


model_id = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(model_id)
onnx_model = ORTModelForSequenceClassification.from_pretrained("./onnx_model")
quantizer = ORTQuantizer.from_pretrained(onnx_model)

qconfig = AutoQuantizationConfig.tensorrt(per_channel=True)


def preprocess_fn(ex, tokenizer):
    return tokenizer(ex["sentence"])


calibration_dataset = quantizer.get_calibration_dataset(
    "glue",
    dataset_config_name="sst2",
    preprocess_function=partial(preprocess_fn, tokenizer=tokenizer),
    num_samples=50,
    dataset_split="train",
)

calibration_config = AutoCalibrationConfig.minmax(calibration_dataset)

ranges = quantizer.fit(
    dataset=calibration_dataset,
    calibration_config=calibration_config,
    operators_to_quantize=qconfig.operators_to_quantize,
)

model_quantized_path = quantizer.quantize(
    save_dir="./output_opt",
    calibration_tensors_range=ranges,
    quantization_config=qconfig,
)
```

**Comment by blacker521** [comment]
Package                       Version
----------------------------- -----------------
absl-py                       2.1.0
accelerate                    0.21.0
addict                        2.4.0
aenum                         3.1.15
aiobotocore                   2.7.0
aiofiles                      23.2.1
aiohttp                       3.9.0
aioitertools                  0.7.1
aiosignal                     1.2.0
alabaster                     0.7.12
altair                        5.2.0
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.4
anaconda-navigator            2.5.0
anaconda-project              0.11.1
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
appdirs                       1.4.4
archspec                      0.2.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.3.4
asttokens                     2.0.5
async-lru                     2.0.4
atomicwrites                  1.4.0
attrs                         23.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.11.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.11.0
bleach                        4.1.0
blendmodes                    2022
blessed                       1.20.0
blis                          0.7.11
bokeh                         3.3.0
boltons                       23.0.0
botocore                      1.31.64
Bottleneck                    1.3.5
Brotli                        1.0.9
catalogue                     2.0.10
certifi                       2024.2.2
cffi                          1.16.0
chardet                       4.0.0
charset-normalizer            2.0.4
clean-fid                     0.1.35
click                         8.1.7
clip                          1.0
cloudpathlib                  0.16.0
cloudpickle                   2.2.1
clyent                        1.2.2
cmake                         3.28.3
colorama                      0.4.6
colorcet                      3.0.1
colored                       2.2.4
coloredlogs                   15.0.1
comm                          0.1.2
conda                         24.3.0
conda-build                   3.28.4
conda-content-trust           0.2.0
conda_index                   0.4.0
conda-libmamba-solver         24.1.0
conda-pack                    0.6.0
conda-package-handling        2.2.0
conda_package_streaming       0.9.0
conda-repo-cli                1.0.75
conda-token                   0.4.0
conda-verify                  3.4.2
confection                    0.1.4
constantly                    23.10.4
contourpy                     1.2.0
cookiecutter                  2.5.0
cryptography                  41.0.7
cssselect                     1.1.0
cycler                        0.12.1
cymem                         2.0.8
cytoolz                       0.12.2
daal4py                       2023.1.1
dask                          2023.11.0
dataclasses-json              0.5.14
datasets                      2.12.0
datashader                    0.16.0
debugpy                       1.6.7
decorator                     5.1.1
deepspeed                     0.13.2
defusedxml                    0.7.1
deprecation                   2.1.0
diff-match-patch              20200713
dill                          0.3.6
distributed                   2023.11.0
distro                        1.8.0
docstring-to-markdown         0.11
docutils                      0.18.1
einops                        0.7.0
en-core-web-sm                3.7.1
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
facexlib                      0.3.0
fastapi                       0.94.0
fastjsonschema                2.16.2
ffmpy                         0.3.2
filelock                      3.13.1
filterpy                      1.4.5
flake8                        6.0.0
Flask                         2.2.5
flatbuffers                   24.3.25
fonttools                     4.50.0
frozenlist                    1.4.0
fsspec                        2023.10.0
fst-pso                       1.8.1
ftfy                          6.2.0
future                        0.18.3
FuzzyTM                       2.0.5
gdown                         5.1.0
gensim                        4.3.0
gitdb                         4.0.11
GitPython                     3.1.32
gmpy2                         2.1.2
gpustat                       1.1.1
gradio                        3.47.1
gradio_client                 0.6.0
greenlet                      3.0.1
grpcio                        1.62.1
h11                           0.12.0
h5py                          3.9.0
HeapDict                      1.0.1
hjson                         3.1.0
holoviews                     1.18.1
httpcore                      0.15.0
httpx                         0.24.1
huggingface-hub               0.17.3
humanfriendly                 10.0
hvplot                        0.9.2
hyperlink                     21.0.0
idna                          3.4
imagecodecs                   2023.1.23
imageio                       2.31.4
imagesize                     1.4.1
imbalanced-learn              0.11.0
importlib-metadata            7.0.1
importlib_resources           6.4.0
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.8
intervaltree                  3.1.0
ipykernel                     6.28.0
ipython                       8.20.0
ipython-genutils              0.2.0
ipywidgets                    8.0.4
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jaraco.classes                3.2.1
jedi                          0.18.1
jeepney                       0.7.1
jellyfish                     1.0.1
Jinja2                        3.1.3
jmespath                      1.0.1
joblib                        1.2.0
json5                         0.9.6
jsonmerge                     1.8.0
jsonpatch                     1.32
jsonpointer                   2.1
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter                       1.0.0
jupyter_client                8.6.0
jupyter-console               6.6.3
jupyter_core                  5.5.0
jupyter-events                0.8.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.8
jupyterlab-pygments           0.1.2
jupyterlab_server             2.25.1
jupyterlab-widgets            3.0.9
kafka-python                  2.0.2
kaleido                       0.2.1
keyring                       23.13.1
kiwisolver                    1.4.5
kornia                        0.6.7
langchain                     0.0.279
langcodes                     3.3.0
langsmith                     0.0.92
lark                          1.1.2
lazy_loader                   0.3
lazy-object-proxy             1.6.0
libarchive-c                  2.9
libmambapy                    1.5.6
lightning-utilities           0.11.0
linkify-it-py                 2.0.0
lit                           17.0.6
llvmlite                      0.41.0
lmdb                          1.4.1
locket                        1.0.0
lpips                         0.1.4
lxml                          4.9.3
lz4                           4.3.2
Markdown                      3.4.1
markdown-it-py                2.2.0
MarkupSafe                    2.1.3
marshmallow                   3.21.3
matplotlib                    3.8.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mcu-rag-chunk-sdk             0.0.1
mdit-py-plugins               0.3.0
mdurl                         0.1.0
menuinst                      2.0.2
miniful                       0.0.6
mistune                       2.0.4
mkl-fft                       1.3.8
mkl-random                    1.2.4
mkl-service                   2.4.0
modelscope                    1.16.0
more-itertools                10.1.0
mpmath                        1.3.0
msgpack                       1.0.3
multidict                     6.0.4
multipledispatch              0.6.0
multiprocess                  0.70.14
munkres                       1.1.4
murmurhash                    1.0.10
mypy-extensions               1.0.0
navigator-updater             0.4.0
nbclient                      0.8.0
nbconvert                     7.10.0
nbformat                      5.9.2
nest-asyncio                  1.5.6
networkx                      3.1
ninja                         1.11.1.1
nltk                          3.8.1
notebook                      7.0.6
notebook_shim                 0.2.3
numba                         0.58.1
numexpr                       2.8.7
numpy                         1.23.5
numpydoc                      1.5.0
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu11             10.9.0.58
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu11            10.2.10.91
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu11          11.7.4.91
nvidia-cusparse-cu12          12.1.0.106
nvidia-ml-py                  12.555.43
nvidia-nccl-cu11              2.14.3
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu11              11.7.91
nvidia-nvtx-cu12              12.1.105
omegaconf                     2.2.3
onnx                          1.16.2
onnxconverter-common          1.14.0
onnxmltools                   1.12.0
onnxruntime-gpu               1.16.3
open-clip-torch               2.20.0
opencv-python                 4.9.0.80
openpyxl                      3.0.10
orjson                        3.9.15
overrides                     7.4.0
packaging                     24.0
pandas                        1.5.3
pandocfilters                 1.5.0
panel                         1.3.8
param                         2.0.2
parsel                        1.6.0
parso                         0.8.3
partd                         1.4.1
pathlib                       1.0.1
pathspec                      0.10.3
patsy                         0.5.3
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
piexif                        1.1.3
Pillow                        9.5.0
pip                           23.2.1
pkce                          1.0.3
pkginfo                       1.9.6
platformdirs                  3.10.0
plotly                        5.9.0
pluggy                        1.0.0
ply                           3.11
polygraphy                    0.49.9
portalocker                   2.8.2
poseidon                      1.0.0
preshed                       3.0.9
prometheus-client             0.14.1
prompt-toolkit                3.0.43
Protego                       0.1.16
protobuf                      3.20.2
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       11.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.12.0
pycodestyle                   2.10.0
pycosat                       0.6.6
pycparser                     2.21
pyct                          0.5.0
pycurl                        7.45.2
pydantic                      1.10.12
PyDispatcher                  2.0.5
pydocstyle                    6.3.0
pydub                         0.25.1
pyerfa                        2.0.0
pyflakes                      3.0.1
pyFUME                        0.3.1
Pygments                      2.15.1
PyJWT                         2.4.0
pylint                        2.16.2
pylint-venv                   2.3.0
pyls-spyder                   0.4.0
pynvml                        11.5.0
pyodbc                        5.0.1
pyOpenSSL                     23.2.0
pyparsing                     3.1.2
PyQt5                         5.15.10
PyQt5-sip                     12.13.0
PyQtWebEngine                 5.15.6
PySocks                       1.7.1
pytest                        7.4.0
python-dateutil               2.9.0.post0
python-dotenv                 0.21.0
python-json-logger            2.0.7
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.7.2
python-multipart              0.0.9
python-slugify                5.0.2
python-snappy                 0.6.1
pytoolconfig                  1.2.6
pytorch-lightning             1.9.4
pytz                          2023.3.post1
pyviz_comms                   3.0.0
pywavelets                    1.5.0
pyxdg                         0.27
PyYAML                        6.0.1
pyzmq                         25.1.2
QDarkStyle                    3.0.2
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.4.2
QtPy                          2.4.1
queuelib                      1.6.2
referencing                   0.30.2
regex                         2023.10.3
requests                      2.31.0
requests-file                 1.5.1
requests-mock                 1.11.0
requests-toolbelt             1.0.0
resize-right                  0.0.2
responses                     0.13.3
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.3.5
rope                          1.7.0
rpds-py                       0.10.6
Rtree                         1.0.1
ruamel.yaml                   0.17.21
ruamel-yaml-conda             0.17.21
s3fs                          2023.10.0
sacrebleu                     2.4.0
safetensors                   0.4.2
scikit-image                  0.21.0
scikit-learn                  1.2.2
scikit-learn-intelex          20230426.111612
scipy                         1.11.4
Scrapy                        2.8.0
seaborn                       0.12.2
SecretStorage                 3.3.1
semantic-version              2.10.0
semver                        2.13.0
Send2Trash                    1.8.2
sentencepiece                 0.2.0
service-identity              18.1.0
setuptools                    68.0.0
simpful                       2.12.0
sip                           6.7.12
six                           1.16.0
smart-open                    5.2.1
smmap                         5.0.1
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
spacy                         3.7.2
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
spandrel                      0.1.6
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.4.3
spyder-kernels                2.4.4
SQLAlchemy                    2.0.25
srsly                         2.4.8
stack-data                    0.2.0
starlette                     0.26.1
statsmodels                   0.14.0
sympy                         1.12
tables                        3.9.2
tabulate                      0.9.0
tb-nightly                    2.17.0a20240408
TBB                           0.2
tblib                         1.7.0
tenacity                      8.2.2
tensorboard-data-server       0.7.2
tensorrt                      9.3.0.post12.dev1
tensorrt-bindings             9.3.0.post12.dev1
tensorrt-libs                 9.3.0.post12.dev1
terminado                     0.17.1
text-unidecode                1.3
textdistance                  4.2.1
thinc                         8.2.2
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2023.4.12
tiktoken                      0.3.2
tiktoken-p50k-im              2.0.0
timm                          0.9.16
tinycss2                      1.2.1
tldextract                    3.2.0
tokenizers                    0.13.3
tomesd                        0.1.3
toml                          0.10.2
tomlkit                       0.11.1
toolz                         0.12.0
torch                         2.1.2
torchaudio                    2.2.2
torchdiffeq                   0.2.3
torchmetrics                  1.3.2
torchsde                      0.2.6
torchvision                   0.16.2+cu121
tornado                       6.3.3
tqdm                          4.65.0
traitlets                     5.7.1
trampoline                    0.1.2
transformers                  4.30.2
triton                        2.1.0
truststore                    0.8.0
Twisted                       22.10.0
typer                         0.9.0
typing_extensions             4.9.0
typing-inspect                0.9.0
tzdata                        2023.3
uc-micro-py                   1.0.1
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.18
uvicorn                       0.29.0
w3lib                         1.21.0
wasabi                        1.1.2
watchdog                      2.1.6
wcwidth                       0.2.13
weasel                        0.3.4
webencodings                  0.5.1
websocket-client              0.58.0
websockets                    11.0.3
Werkzeug                      2.2.3
whatthepatch                  1.0.2
wheel                         0.38.4
widgetsnbextension            4.0.5
wrapt                         1.14.1
wurlitzer                     3.0.2
xarray                        2023.6.0
xformers                      0.0.23.post1
xxhash                        2.0.2
xyzservices                   2022.9.0
yapf                          0.31.0
yarl                          1.9.3
zict                          3.0.0
zipp                          3.17.0
zope.interface                5.4.0
zstandard                     0.19.0

**Comment by blacker521** [comment]
I installed it the official way
python -m pip install git+https://github.com/huggingface/optimum.git
python -m pip install optimum[onnxruntime]@git+https://github.com/huggingface/optimum.git

**Comment by blacker521** [comment]
Package                  Version
------------------------ -----------
aiohappyeyeballs         2.4.0
aiohttp                  3.10.5
aiosignal                1.3.1
async-timeout            4.0.3
attrs                    24.2.0
certifi                  2024.8.30
charset-normalizer       3.3.2
coloredlogs              15.0.1
datasets                 3.0.0
dill                     0.3.8
evaluate                 0.4.3
filelock                 3.16.0
flatbuffers              24.3.25
frozenlist               1.4.1
fsspec                   2024.6.1
huggingface-hub          0.24.6
humanfriendly            10.0
idna                     3.8
Jinja2                   3.1.4
MarkupSafe               2.1.5
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.1
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.68
nvidia-nvtx-cu12         12.1.105
onnx                     1.16.2
onnxruntime              1.16.3
optimum                  1.23.0.dev0
packaging                24.1
pandas                   2.0.3
pip                      24.2
protobuf                 5.28.1
pyarrow                  17.0.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.9.11
requests                 2.32.3
safetensors              0.4.5
sentencepiece            0.2.0
setuptools               72.1.0
six                      1.16.0
sympy                    1.13.2
tokenizers               0.19.1
torch                    2.4.1
tqdm                     4.66.5
transformers             4.44.2
triton                   3.0.0
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
wheel                    0.43.0
xxhash                   3.5.0
yarl                     1.11.1

**Comment by IlyasMoutawwakil** [comment]
yeah we should probably pin a minimum onnxruntime version, please update onnxruntime with `pip install onnxruntime -U`
