### ISSUE TITLE
OPT (open pretrained transformers) not supported

### ISSUE THREAD

**Issue by ViktorThink** [huggingface/optimum#202]
I wanted to check if there are any plans to add support for OPT models to optimum?

**Comment by JingyaHuang** [comment]
Hi @ViktorThink ,

Thanks for reaching out! OPT is currently not supported, a custom `OnnxConfig` implementation needs to be done in transformers to enable ONNX export of OPT before applying Optimum functionalities. This could be done by following [these steps](https://huggingface.co/docs/transformers/serialization#exporting-a-model-for-an-unsupported-architecture).

Are you interested in opening a PR for that?

**Comment by ViktorThink** [comment]
Hi @JingyaHuang, thanks for the reply.

Yes, I should be able to do it next week.

**Comment by kargarisaac** [comment]
Is there any update on this?

**Comment by ViktorThink** [comment]
See: https://github.com/huggingface/transformers/pull/17771

We ran into some trouble when trying to export it to ONNX. It's working without past_key_values though.

**Comment by kargarisaac** [comment]
@ViktorThink Thank you for the quick response.

I try to follow the steps on colab:
```bash
!git clone https://github.com/rushic24/transformers.git
%cd transformers
!git checkout opt_onnx
!git status
!python setup.py install 
!pip install -e ".[dev]"
!pip install onnxruntime
```
I see an error during installation:
```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed APScheduler-3.9.1 Flask-2.1.3 GitPython-3.1.18 Jinja2-3.1.2 Mako-1.2.1 Pint-0.16.1 accelerate-0.11.0 aiohttp-3.8.1 aiosignal-1.2.0 alembic-1.8.1 arrow-1.2.2 async-timeout-4.0.2 asynctest-0.13.0 autopage-0.5.1 backoff-1.11.1 backports.zoneinfo-0.2.1 binaryornot-0.4.4 black-22.6.0 boto3-1.24.35 botocore-1.27.35 brotli-1.0.9 chex-0.1.3 click-8.0.4 cliff-3.10.1 clldutils-3.12.0 cmaes-0.8.2 cmd2-2.4.2 codecarbon-1.2.0 colorama-0.4.5 colorlog-6.6.0 commonmark-0.9.1 cookiecutter-1.7.3 cryptography-37.0.4 csvw-3.0.0 dash-2.6.0 dash-bootstrap-components-1.2.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 datasets-2.3.2 dill-0.3.4 distlib-0.3.5 dlinfo-1.2.1 docker-4.4.4 exceptiongroup-1.0.0rc8 execnet-1.9.0 faiss-cpu-1.7.2 fire-0.4.0 flake8-4.0.1 flask-compress-1.12 flatbuffers-1.12 flax-0.5.2 frozenlist-1.3.0 fsspec-2022.5.0 fugashi-1.1.2 gitdb-4.0.9 grpcio-1.43.0 hf-doc-builder-0.3.0 hypothesis-6.52.3 importlib-metadata-4.2.0 ipadic-1.0.0 isodate-0.6.1 isort-5.10.1 itsdangerous-2.1.2 jax-0.3.6 jaxlib-0.3.5 jinja2-time-0.2.0 jmespath-1.0.1 kubernetes-12.0.1 language-tags-1.1.0 markdown-3.3.4 mccabe-0.6.1 multidict-6.0.2 multiprocess-0.70.12.2 mypy-extensions-0.4.3 onnxconverter-common-1.9.0 optax-0.1.3 optuna-2.10.1 parameterized-0.8.1 pathspec-0.9.0 pbr-5.9.0 phonemizer-3.2.1 plac-1.3.5 platformdirs-2.5.2 portalocker-2.0.0 poyo-0.5.0 pyOpenSSL-22.0.0 pycodestyle-2.8.0 pyctcdecode-0.4.0 pyflakes-2.4.0 pygtrie-2.5.0 pynvml-11.4.1 pyperclip-1.8.2 pypng-0.20220715.0 pytest-4.3.1 pytest-forked-1.4.0 pytest-timeout-1.4.2 pytest-xdist-1.27.0 pytz-deprecation-shim-0.1.0.post0 pyyaml-5.4.1 ray-1.13.0 rdflib-6.1.1 requests-2.28.1 responses-0.18.0 rfc3986-1.5.0 rich-11.2.0 rjieba-0.1.11 rouge-score-0.0.4 s3transfer-0.6.0 sacrebleu-1.5.1 sacremoses-0.0.53 segments-2.2.1 sentencepiece-0.1.96 sigopt-8.5.1 smmap-5.0.0 stevedore-3.5.0 tensorboardX-2.5.1 tf2onnx-1.11.1 timeout-decorator-0.5.0 timm-0.6.5 torch-1.12.0 torchvision-0.13.0 transformers-4.21.0.dev0 typed-ast-1.5.4 tzdata-2022.1 tzlocal-4.2 unidic-1.1.0 unidic-lite-1.0.8 urllib3-1.25.11 virtualenv-20.15.1 websocket-client-1.3.3 werkzeug-2.1.2 xxhash-3.0.0 yarl-1.7.2
WARNING: The following packages were previously imported in this runtime:
  [dill,flatbuffers,grpc,importlib_metadata,jax,jaxlib,requests,torch,urllib3,yaml]
You must restart the runtime in order to use newly installed versions.
```

And then 
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
model = AutoModelForCausalLM.from_pretrained("facebook/opt-125m", torch_dtype=torch.float32)
# the fast tokenizer currently does not work correctly
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-125m", use_fast=False)
prompt = "Hello, I'm am conscious and"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
generated_ids = model.generate(input_ids)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
```

```bash
!python -m transformers.onnx --model=facebook/opt-125m onnx/opt-125m/
```
which gives me:
```bash
2022-07-21 19:32:24.531588: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Some weights of the model checkpoint at facebook/opt-125m were not used when initializing OPTModel: ['lm_head.weight']
- This IS expected if you are initializing OPTModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing OPTModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Using framework PyTorch: 1.12.0+cu102
Overriding 1 configuration item(s)
	- use_cache -> False
/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/modeling_opt.py:520: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1:
/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/modeling_opt.py:64: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min))
/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/modeling_opt.py:203: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/modeling_opt.py:210: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, tgt_len, src_len):
/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/modeling_opt.py:242: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
Validating ONNX model...
	-[✓] ONNX model output names match reference model ({'last_hidden_state'})
	- Validating ONNX Model output "last_hidden_state":
		-[✓] (2, 8, 768) matches (2, 8, 768)
		-[x] values not close enough (atol: 1e-05)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/__main__.py", line 107, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/__main__.py", line 100, in main
    validate_model_outputs(onnx_config, preprocessor, model, args.output, onnx_outputs, args.atol)
  File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/convert.py", line 441, in validate_model_outputs
    "Outputs values doesn't match between reference model and ONNX exported model: "
ValueError: Outputs values doesn't match between reference model and ONNX exported model: Got max absolute difference of: 5.2094459533691406e-05
```

what am I doing wrong? Where should I change `past_key_values `?

**Comment by ViktorThink** [comment]
You exported the model without the past_key_values, which works fine.

If you want to export the model with past_key_values, you have to set --feature=causal-lm-with-past

Like this:

`!python -m transformers.onnx  --model=facebook/opt-125m onnx/opt-125m/  --feature=causal-lm-with-past
`

**Comment by kargarisaac** [comment]
> You exported the model without the past_key_values, which works fine.
> 
> If you want to export the model with past_key_values, you have to set --feature=causal-lm-with-past
> 
> Like this:
> 
> `!python -m transformers.onnx --model=facebook/opt-125m onnx/opt-125m/ --feature=causal-lm-with-past ` Then you will get this error:
> 
> ```
> 2022-07-21 20:11:50.019936: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
> Using framework PyTorch: 1.12.0+cu113
> Overriding 1 configuration item(s)
> 	- use_cache -> True
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/__main__.py", line 107, in <module>
>     main()
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/__main__.py", line 94, in main
>     args.output,
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/convert.py", line 335, in export
>     return export_pytorch(preprocessor, model, config, opset, output, tokenizer=tokenizer, device=device)
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/onnx/convert.py", line 142, in export_pytorch
>     model_inputs = config.generate_dummy_inputs(preprocessor, framework=TensorType.PYTORCH)
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/configuration_opt.py", line 213, in generate_dummy_inputs
>     self.num_attention_heads,
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/models/opt/configuration_opt.py", line 184, in num_attention_heads
>     return self._config.n_head
>   File "/usr/local/lib/python3.7/dist-packages/transformers-4.21.0.dev0-py3.7.egg/transformers/configuration_utils.py", line 253, in __getattribute__
>     return super().__getattribute__(key)
> AttributeError: 'OPTConfig' object has no attribute 'n_head'
> ```

Thanks. What about the error I get then?

```
ValueError: Outputs values doesn't match between reference model and ONNX exported model: Got max absolute difference of: 5.2094459533691406e-05
```

What is the difference when I export the model w/wo `past_key_values`?

**Comment by kargarisaac** [comment]
clear. Thanks for the explanation.

**Comment by kargarisaac** [comment]
@ViktorThink  One more question. It seems after converting the model to onnx, optimum does not support OPT for quantization, right?

**Comment by ViktorThink** [comment]
I'm not really sure about how it works with optimum, but in general just a few lines of code are needed to quantize any onnx model with supported operations: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/README.md

**Comment by kargarisaac** [comment]
Thank you. I did the quantization. One problem that I have is that the generated output of the onnx model (even before quantization and just after converting the transformer model to onnx using the mentioned PR), I see ugly outputs:

```python
from transformers import AutoTokenizer
from onnxruntime import InferenceSession
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-125m")
session = InferenceSession("onnx/opt-125m/model.onnx")
inputs = tokenizer(prompt, return_tensors="np")
inputs = dict(inputs)
inputs['input_ids'] = inputs['input_ids'].astype(np.int64)
inputs['attention_mask'] = inputs['attention_mask'].astype(np.int64)
outputs = session.run(output_names=["last_hidden_state"], input_feed=inputs)[0]
generated_ids = np.argmax(outputs, axis=-1)
print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True))
## output: [' days school school school school school']
```

while the opt-125m model itself gives a reasonable output:
```python
model_name = "facebook/opt-125m"
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float32)
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)
prompt = "Hello, I'm am conscious and"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
generated_ids = model.generate(input_ids)
print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True))
## output: ["Hello, I'm am conscious and I'm not sure if I'm a good person or not"]
```
Am I doing something wrong in decoding the `last_hidden_state` tensor or sth else is wrong? The `last_hidden_state` shape is `[1, 8, 768]`.

**Comment by ViktorThink** [comment]
I made a Colab demonstrate how you should decode: https://colab.research.google.com/drive/1nNucXKVsrxFdVWqQv0XumJJT7D55yYkC?usp=sharing

There are better scripts for generation, but I just wanted to see if the model works, which it seems to do since it gave the same output as when you tried the torch model.

You decoded the last hidden states of the first eight words, you had to decode the logits.

**Comment by kargarisaac** [comment]
@ViktorThink Thanks. That's great :)

**Comment by kargarisaac** [comment]
The for loop is the bottleneck here. It is slower than the pytorch model with `.generate()` method. Is there a way to accelerate that?

**Comment by ViktorThink** [comment]
Yes, exactly, that's why we need past_key_values. Right now it has to all of the previous text every time in the loop.

With past_key_values, you could save the previous values and just process the last word.

As stated before, I don't know how to fix the past_key_values issue.

**Comment by kargarisaac** [comment]
Got it. thanks.

**Comment by kargarisaac** [comment]
I managed to run the onnx model without the for loop and using optimum. Now, when I try to convert `facebook/opt-13b` mode to onnx, it gives me the following error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/transformers/onnx/utils.py", line 88, in get_preprocessor
    return AutoProcessor.from_pretrained(model_name)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/processing_auto.py", line 250, in from_pretrained
    f"Unrecognized processor in {pretrained_model_name_or_path}. Should have a `processor_type` key in "
ValueError: Unrecognized processor in facebook/opt-13b. Should have a `processor_type` key in its preprocessor_config.json, or one of the following `model_type` keys in its config.json: clip, flava, layoutlmv2, layoutlmv3, layoutxlm, sew, sew-d, speech_to_text, speech_to_text_2, trocr, unispeech, unispeech-sat, vilt, vision-text-dual-encoder, wav2vec2, wav2vec2-conformer, wav2vec2_with_lm, wavlm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/transformers/onnx/__main__.py", line 107, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/transformers/onnx/__main__.py", line 62, in main
    preprocessor = get_preprocessor(args.model)
  File "/opt/conda/lib/python3.7/site-packages/transformers/onnx/utils.py", line 92, in get_preprocessor
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 580, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1810, in from_pretrained
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1948, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 152, in __init__
    "Currenty GPT2's fast tokenizer does NOT support adding a BOS token."
ValueError: Currenty GPT2's fast tokenizer does NOT support adding a BOS token.Instead you should use GPT2's slow tokenizer class `GPT2Tokenizer` as follows: 
`GPT2Tokenizer.from_pretrained('facebook/opt-13b')`
or
`AutoTokenizer.from_pretrained('facebook/opt-13b', use_fast=False)`
This issue will be fixed soon, see: https://github.com/huggingface/tokenizers/pull/1005. so that the fast tokenizer works correctly.
```

I see the items of this list [here](https://github.com/rushic24/transformers/blob/opt_onnx/src/transformers/models/auto/processing_auto.py), but it doesn't seem to be the problem. It works for all opt models before 13b. Do you have any idea where is the problem?

**Comment by ViktorThink** [comment]
It's as it says, the fast tokenizer isn't supported for OPT models, however I have no idea why it should try to use the fast one for the 13b version and not the previous versions.

You can fork the repository and add code to specify that the slow tokenizer can be used, I did the same when running into the problem during debugging.

**Comment by kargarisaac** [comment]
Sorry for a lot of questions @ViktorThink. 
I solved the problem. I try to use the above procedure to convert a fine-tuned version of opt-13b which is saved locally. The folder contents are the same as what I see on huggingface: https://huggingface.co/facebook/opt-13b/tree/main

How should I now load the model from local folder and do the conversion to onnx?  What would be the command?
This doesn't work. It looks for `model.onnx` there which doesn't exist. I just have `pytorch_model-00001-of-00003.bin`, `pytorch_model-00002-of-00003.bin` , and `pytorch_model-00003-of-00003.bin` in the `finetuned` folder.

```
python -m transformers.onnx --model=./finetuned/ onnx/ --feature=causal-lm 
```

**Comment by ViktorThink** [comment]
You mean you changed to using the slow tokenizer? As I wrote here: https://github.com/huggingface/transformers/pull/17771#issuecomment-1173494670


You should then be able to use this code:

```

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name="facebook/opt-13b"
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)
pt_model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer.save_pretrained("local-pt-checkpoint")
pt_model.save_pretrained("local-pt-checkpoint")
```

To save the model, and then use:

`python -m transformers.onnx --model=local-pt-checkpoint --preprocessor=tokenizer onnx/opt-13b/
`

Was that what you were looking for?

**Comment by kargarisaac** [comment]
I think not. I got opt-13, finetuned it on a custome dataset and saved it locally. The model is saved in 3 parts: `pytorch_model-00001-of-00003.bin`, `pytorch_model-00002-of-00003.bin` , and `pytorch_model-00003-of-00003.bin`.

![image](https://user-images.githubusercontent.com/24753756/180838890-e90b1be6-b97e-4870-ab57-e2d5cee9b964.png)

Now I want to convert it to onnx using `python -m transformers.onnx --model=facebook/opt-13b onnx/ --feature=causal-lm` but use the local saved model and not facebook/opt-13b from huggingfacehub.

I use the code you sent. The first code to save the model in `local-pt-checkpoint` works. But again I see a new problem:
```
Using framework PyTorch: 1.12.0
Overriding 1 configuration item(s)
	- use_cache -> False
```

**Comment by ViktorThink** [comment]
Sorry, I'm not sure how to help with that...
