### ISSUE TITLE
High CUDA Memory Usage in ONNX Runtime with Inconsistent Memory Release

### ISSUE THREAD

**Issue by niyathimariya** [huggingface/optimum#2069]
### System Info

```shell
Optimum version: 1.22.0
Platform: Linux (Ubuntu 22.04.4 LTS)
Python version: 3.12.2
ONNX Runtime Version: 1.19.2
CUDA Version: 12.1
CUDA Execution Provider: Yes (CUDA 12.1)
```

### Who can help?

@JingyaHuang @echarlaix 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```python
def load_model(self, model_name):
    session_options = ort.SessionOptions()
    session_options.add_session_config_entry('cudnn_conv_use_max_workspace', '0')
    session_options.enable_mem_pattern = False
    session_options.arena_extend_strategy = "kSameAsRequested"
    session_options.gpu_mem_limit = 10 * 1024 * 1024 * 1024
    
    model = ORTModelForSeq2SeqLM.from_pretrained(model_name, provider="CUDAExecutionProvider", session_options=session_options)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return tokenizer, model

def inference(self, batch, doc_id='-1'):
    responses, status = '', False
    try:
        encodings = self.tokenizer(batch, padding=True, truncation=True, max_length=8192, return_tensors="pt").to(self.device)
        with torch.no_grad():
            generated_ids = self.model.generate(
                encodings.input_ids,
                max_new_tokens=1024
            )
            responses = self.tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
            status = True  
    except Exception as e:
        logger.error(f"Failed to do inference on LLM, error: {e}")

    torch.cuda.empty_cache()
    return status, responses
```

### Expected behavior

I expect the CUDA memory to decrease and be released after processing smaller inputs, optimizing memory usage for subsequent inputs.
![Picture1](https://github.com/user-attachments/assets/a188ede0-2287-4603-a84e-ba62d309a940)

**Comment by IlyasMoutawwakil** [comment]
Hi, the code you provided doesn't explain how you got the chart in you issue, what is "sample number" in this case ?

**Comment by niyathimariya** [comment]
Hi @IlyasMoutawwakil, the code I’ve provided shows how I’m loading the model and performing inference. I’ve also included a graph to demonstrate that the model, which I’ve converted to ONNX using the save_pretrained() method, is not releasing memory when it encounters a lower input sequence after processing a higher input sequence, whereas the PyTorch model is releasing the memory in such cases.

**Comment by IlyasMoutawwakil** [comment]
and, I assume, "sample number" is supposed to mean sequence length ?
either ways, this doesn't seem like an optimum issue, but rather on onnxruntime side (the inference session), since it's the part that handles memory allocation and release.

**Comment by niyathimariya** [comment]
Thanks, @IlyasMoutawwakil. Do you think this is normal behavior for ONNX Runtime?

**Comment by kkluonaitis** [comment]
There is definitely a bug. In production I run long-t5 model, but most processes kinda freeze after gradual GPU memory increase. I rolled back onnxruntime to 1.18.0, which works fine.

**Comment by IlyasMoutawwakil** [comment]
must be an issue in onnxruntime memory arena/allocation, please open an issue there 🤗
