### ISSUE TITLE
Flux Pipeline doesn't work 

### ISSUE THREAD

**Issue by clintg6** [huggingface/optimum#2103]
### System Info

```shell
GPU: MI300X
Library versions:
diffusers                         0.31
onnx                              1.17.0
onnxruntime-rocm                  1.21.0
optimum                           1.24.0.dev0
torch                             2.6.0a0+git713ca1b
transformers                      4.46.2
```

### Who can help?

@IlyasMoutawwakil

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

from optimum.onnxruntime import ORTFluxPipeline

model_id = "optimum-internal-testing/tiny-random-flux" # Replace with the appropriate model ID for Flux
pipeline_rocm = ORTFluxPipeline.from_pretrained(
    model_id,
    export=False,
)

Error output:
File /opt/conda/envs/py_3.9/lib/python3.9/site-packages/diffusers/pipelines/flux/pipeline_flux.py:198, in FluxPipeline.__init__(self, scheduler, vae, text_encoder, tokenizer, text_encoder_2, tokenizer_2, transformer)
    186 super().__init__()
    188 self.register_modules(
    189     vae=vae,
    190     text_encoder=text_encoder,
   (...)
    195     scheduler=scheduler,
    196 )
    197 self.vae_scale_factor = (
--> 198     2 ** (len(self.vae.config.block_out_channels) - 1) if hasattr(self, "vae") and self.vae is not None else 8
    199 )
    200 # Flux latents are turned into 2x2 patches and packed. This means the latent width and height has to be divisible
    201 # by the patch size. So the vae scale factor is multiplied by the patch size to account for this
    202 self.image_processor = VaeImageProcessor(vae_scale_factor=self.vae_scale_factor * 2)

File /opt/conda/envs/py_3.9/lib/python3.9/site-packages/diffusers/configuration_utils.py:143, in ConfigMixin.__getattr__(self, name)
    140     deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
    141     return self._internal_dict[name]
--> 143 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'ORTWrapperVae' object has no attribute 'config'

### Expected behavior

I expect it to load the pipeline.

**Comment by IlyasMoutawwakil** [comment]
you're disabling export.. pipeline should either be exported using the `optimum-cli` or with `export=True`

**Comment by clintg6** [comment]
It crashes when export=True is set as well but throws a different error when I don't use the tiny test model. Have you actually tested with the full Flux model because it doesnt work whether export is set to true or not? The cli command also fails with the same error looking for a dummy input.

`optimum-cli export onnx --model black-forest-labs/FLUX.1-dev --task 'text-to-image' ./flux`

```
from optimum.onnxruntime import ORTFluxPipeline

model_id = "black-forest-labs/FLUX.1-dev" # Replace with the appropriate model ID for Flux
pipeline_rocm = ORTFluxPipeline.from_pretrained(
model_id,
export=True,
)
```

File /opt/conda/envs/py_3.9/lib/python3.9/site-packages/optimum/exporters/onnx/base.py:476, in OnnxConfig.generate_dummy_inputs(self, framework, **kwargs)
    474             break
    475     if not input_was_inserted:
--> 476         raise RuntimeError(
    477             f'Could not generate dummy input for "{input_name}". Try adding a proper dummy input generator to '
    478             "the model ONNX config."
    479         )
    480 return dummy_inputs

RuntimeError: Could not generate dummy input for "guidance". Try adding a proper dummy input generator to the model ONNX config.

**Comment by IlyasMoutawwakil** [comment]
Hi ! I experimented with sd3 but not flux sine their components are the same and the tiny models generally simulate the constraints of exporting/inferencing with the big ones, I will try running an export job on our machines and report back (it's a big model so it's gonna take a while). Also thanks for testing this new integration !

**Comment by IlyasMoutawwakil** [comment]
yes you're right it seems that I forgot to add the `guidance` input generator for the case when the architecture requires it (not always) https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/flux/pipeline_flux.py#L723 i'm fixing it in #2104. 
I just ran the branch with guidance generation:
`optimum-cli export onnx --model black-forest-labs/FLUX.1-dev --task 'text-to-image' /raid/ilyas/flux-onnx`
and then:
`ort_pipe = ORTFluxPipeline.from_pretrained("/raid/ilyas/flux-onnx/")`
I also uploaded the exported model to https://huggingface.co/IlyasMoutawwakil/flux-onnx-optimum which you can use directly without going through the export (requires a big machine with lots of ram).
PS: onnx doesn't support bf16 so the export had to be done in fp32, see https://github.com/comfyanonymous/ComfyUI_TensorRT/issues/57

**Comment by IlyasMoutawwakil** [comment]
Also changed `guidance_embeds` to `true` in the tiny flux transformer config so that this case is tested:
https://huggingface.co/optimum-internal-testing/tiny-random-flux/commit/d64d988ce1a80f263ab911e99014e7d3679d21b9
