### ISSUE TITLE
Pass torch_dtype when exporting a Sentence Transformers model to ONNX

### ISSUE THREAD

**Issue by sjrl** [huggingface/optimum#2115]
### System Info

```shell
optimum: main
Mac OS
Python: 3.10
```

### Who can help?

Export of transformers model to ONNX: @michaelbenayoun 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

```bash
optimum-cli export onnx --model intfloat/multilingual-e5-base --task feature-extraction --library-name sentence_transformers ml_e5_onnx
```
and 
```bash
optimum-cli export onnx --model intfloat/multilingual-e5-base --task feature-extraction --library-name sentence_transformers --dtype bf16 ml_e5_onnx
```
result in the same export with float32. So the dtype flag is ignored. 

### Expected behavior

To get an ONNX export in bfloat16 when using the `--dtype bf16` flag

The issue is caused here https://github.com/huggingface/optimum/blob/d6de6762e0e4bf8136f0435211a0e777f5bf2f33/optimum/exporters/tasks.py#L2135-L2142

specifically it looks like the `torch_dtype` is not passed to the constructor of the SentenceTransformer model. So something like this 
```python
            model = model_class(
                model_name_or_path,
                device=device,
                cache_folder=cache_folder,
                token=token,
                trust_remote_code=trust_remote_code,
                model_kwargs={"torch_dtype": torch_dtype} # <-- Add this line
            )
```
should fix it.

**Comment by michaelbenayoun** [comment]
Interesting. Can you open a PR with the suggested change please?
