### ISSUE TITLE
Passing GPU Device to ORT Pipeline fails

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/optimum#213]
I was trying to run a GPU accelerated optimum pipeline but passing device to the pipeline object fails in the following way

```python
from optimum.pipelines import pipeline as ort_pipeline

ort_pipeline(
  "text-classification", model=quantized_model, tokenizer=tokenizer, return_all_scores=True, device=0
)
```

returns error
`AttributeError: 'ORTModelForSequenceClassification' object has no attribute 'to'`

This works for the standard transformers pipeline object. I am exporting my quantized model which does not seem to support a `to_gpu` flag like the fit command does. Wondering how people export a quantized model then run it on GPU.

**Comment by JingyaHuang** [comment]
Pinging @philschmid for information.

**Comment by philschmid** [comment]
hey @sam-h-bean,

Currently, the `device` parameter is not used. The Model is automatically loaded on the GPU when it is available (when onnxruntime-gpu) is installed. 
We are working on improving this.

**Comment by sam-h-bean** [comment]
@philschmid I see! I had only installed onnxruntime which makes a lot of sense. Thank you for the ping.
