### ISSUE TITLE
Add Past key value support for `ORTModelForCausalLM`

### ISSUE THREAD

**Issue by philschmid** [huggingface/optimum#259]

**Comment by tiena2cva** [comment]
Is there any update on this issue?

I have already done a version of that with the idea from `ORTModelForSeq2SeqLM` class: Have 2 sessions instead 1:
- Both 2 session has past_key_values (present) in the outputs
- The first model doesn't have past_key_values in the input, the other does. [Idea from](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/modeling_seq2seq.py#L379):
  ```
  onnx_config_decoder = DecoderOnnxConfig(model.config, task=cls.pipeline_task, use_past=False)
  onnx_config_decoder_with_past = DecoderOnnxConfig(model.config, task=cls.pipeline_task, use_past=True)
  ```
- In the top class, if past_key_values is not appended in the input, pass the inputs to the first model, else pass them to the second model. [Idea from](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/modeling_seq2seq.py#L568):
  ```
        if past_key_values is None:
            decoder_outputs = self.decoder(
                input_ids=decoder_input_ids,
                encoder_hidden_states=encoder_outputs.last_hidden_state,
                encoder_attention_mask=attention_mask,
            )
        else:
            decoder_outputs = self.decoder_with_past(
                input_ids=decoder_input_ids[:, -1:],  # Cut decoder_input_ids if past is used
                past_key_values=past_key_values,
                encoder_hidden_states=encoder_outputs.last_hidden_state,
                encoder_attention_mask=attention_mask,
            )
  ```
What do you think about my approach?

@philschmid @echarlaix

**Comment by echarlaix** [comment]
Hi @tiena2cva, this work is currently in progress and is in the same line of thought as what you are proposing, you can follow the progress [here](https://github.com/huggingface/optimum/tree/add-causallm-with-pkv).

**Comment by tiena2cva** [comment]
Hi @echarlaix, I read your commit and it looks pretty same as mine :smile:
However, there is some line of code and class name that makes me confused. Can I comment on your code or push some commits to your branch?
