### ISSUE TITLE
Missing documentation of `ORTModel.from_pretrained()`

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#272]
### Feature request

We miss the documentation of `ORTModel.from_pretrained()` in https://huggingface.co/docs/optimum/main/en/onnxruntime/modeling_ort . It's not much, just need to add the documentation to the method and modify the mdx file.

Also, compared to https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained , we don't have an argument `pretrained_model_name_or_path`. Currently to load a local `.onnx` file, we must do e.g. `ORTModelForSequenceClassification.from_pretrained("/path/to/folder/", file_name="model.onnx")`.

I wonder if, like for Tensorflow/Flax models in transformers, we could not do `ORTModelForSequenceClassification.from_pretrained("/path/to/folder/model.onnx"` and have the check `os.path.isfile()` like in the transformers method. Alternatively, have an argument `from_onnx=True`.

Here is how the check is done in transformers: https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/modeling_utils.py#L1944

https://github.com/huggingface/optimum/blob/958b31757bd2453d1c0758c342aa873be4040646/optimum/modeling_base.py#L165-L174

https://github.com/huggingface/optimum/blob/958b31757bd2453d1c0758c342aa873be4040646/optimum/onnxruntime/modeling_ort.py#L155-L165

### Your contribution

I can work on this

**Comment by philschmid** [comment]
Thank you @fxmarty for opening the issue. I compared the documentation with `transformers` as well. It seems that for `AutoModelForXXX` in transformers there is also no `from_pretrained` documentation: See [BERT](https://huggingface.co/docs/transformers/v4.20.1/en/model_doc/bert#transformers.BertForSequenceClassification). 

What we could do is add a `Main Class` section in the documentation and add the [OptimizedModel](https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/modeling_base.py#L166) to it which implements the base `from_pretrained` method. For this we should add a similar nice docstring than `transformers`. 

Can you take a look on adding the documentation and the docstring? 

---

For the second part

> Currently to load a local .onnx file, we must do e.g. ORTModelForSequenceClassification.from_pretrained("/path/to/folder/", file_name="model.onnx").

This shouldn't be the case to load a local file you should be able to only provide the `path` see [here](https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/onnxruntime/modeling_ort.py#L191). The `file_name` can always be added to load different onnx models, .e.g q8 model. 

> I wonder if, like for Tensorflow/Flax models in transformers, we could not do ORTModelForSequenceClassification.from_pretrained("/path/to/folder/model.onnx" and have the check os.path.isfile() like in the transformers method. Alternatively, have an argument from_onnx=True.

Thats shouldn't be needed. Since the default always expects a `model.onnx` at the directory or repository. And the default is "onnx" that's why we have the `from_transformers` argument. 

Could you please double-check? or provide an example to reproduce.

**Comment by fxmarty** [comment]
Thank you, I will do a PR ASAP for this!

> This shouldn't be the case to load a local file you should be able to only provide the path see [here](https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/onnxruntime/modeling_ort.py#L191). The file_name can always be added to load different onnx models, .e.g q8 model.

Yes, there is the default `ONNX_WEIGHT_NAME` (which is `model.onnx`): https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/onnxruntime/modeling_ort.py#L189

Although this would break with transformers (that also make use of `TF_WEIGHTS_NAME`, `FLAX_WEIGHTS_NAME`, etc.), here as we just expect a single .onnx file I don't think it would be bad to accept
```python
ORTModelForSequenceClassification.from_pretrained("/path/to/my/abcd.onnx")
```

Currently

```python
model = ORTModelForSequenceClassification.from_pretrained("/home/my/path/", file_name="quantized_model.onnx")
```
prints `config.json NOT FOUND in HuggingFace Hub`

and

```python
model = ORTModelForSequenceClassification.from_pretrained("/home/my/path/quantized_model.onnx")
```

prints `requests.exceptions.HTTPError: 404 Client Error: Not Found for url`.

**Comment by philschmid** [comment]
> Currently
> 
> ```python
> model = ORTModelForSequenceClassification.from_pretrained("/home/my/path/", file_name="quantized_model.onnx")
> ```
> 
> prints `config.json NOT FOUND in HuggingFace Hub`

Is there a `config.json` in your directory? the `ORTModelForXXX` are expecting a `config.json` similar to what the `transformers` models are expecting for correct outputs etc.

**Comment by fxmarty** [comment]
There is no `config.json` in my directory. What should I put in it if I have a vanilla onnx (e.g. exported from `python -m transformers.onnx`)? A `ORTConfig` https://huggingface.co/docs/optimum/main/en/onnxruntime/configuration#optimum.onnxruntime.ORTConfig ? From what I read in the code, this config.json should populate `self.config`, but this is used nowhere I think, checking the ouputs doesn't require it, for me it is the InferenceSession's `get_outputs()` that does the job:

https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/onnxruntime/modeling_ort.py#L332

I agree it is useful to have this config attribute to know about the model / consistency with transformers though.

To be fully consistent, if we require a config I would suggest to remove the default `config = None` in the `ORTModelFor...`: https://github.com/huggingface/optimum/blob/42825ce3e73c381ed14c2fe906cd970e9090d325/optimum/onnxruntime/modeling_ort.py#L405-L414

There is no such default in transformers, see https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/models/bert/modeling_bert.py#L1510-L1511 and https://github.com/huggingface/transformers/blob/d0acc9537829e7d067edbb791473bbceb2ecf056/src/transformers/modeling_utils.py#L1016

**Comment by fxmarty** [comment]
Thinking more about my last comment @philschmid , I think it is best practice to incentivize to have a config.json all along to know what are the model outputs, labels, etc. Not necessarily used right now, but it is nice to have to understand what the onnx model is (otherwise it's a bit of a blackbox).

One doubt I have is: we are currently trying to dissociate `ORTQuantizer` from transformers. From what I understand, this means that we may provide any sole `.onnx`, and get a quantized model as a sole `model_quantized.onnx`. There is no config file here as there was none to begin with. Shouldn't we be able to load this `model_quantized.onnx` into an `ORTModel` with `from_pretrained()`, even though there is no config?

**Comment by philschmid** [comment]
> One doubt I have is: we are currently trying to dissociate ORTQuantizer from transformers. From what I understand, this means that we may provide any sole .onnx, and get a quantized model as a sole model_quantized.onnx. There is no config file here as there was none to begin with. Shouldn't we be able to load this model_quantized.onnx into an ORTModel with from_pretrained(), even though there is no config?

If you are converting your model with `ORTModelFromXXX` and `from_transformers` the `config.json` is available and so if you are saving the model to the same directory or pushing it to the hub then yes. But that's a good point. We should probably rather create a default `config` when there is none available like `transformers` is doing. 

Could you take a look?
