### ISSUE TITLE
Force write of vanilla onnx model with `ORTQuantizer.export()`

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#276]
### Feature request

Force write of the non-quantized onnx model with `ORTQuantizer.export()`, or add an option to force write.

### Motivation

Currently, if the `onnx_model_path` already exists, we don't write the non-quantized model in to the indicated path.

https://github.com/huggingface/optimum/blob/04a2a6d290ca6ea6949844d1ae9a208ca95a79da/optimum/onnxruntime/quantization.py#L313-L315

Meanwhile, the quantized model is always written, even if there is already a model at the `onnx_quantized_model_output_path` (see https://github.com/onnx/onnx/blob/60d29c10c53ef7aa580291cb2b6360813b4328a3/onnx/__init__.py#L170).

Is there any reason for this different behavior? It led me to unexpected behaviors, where the non-quantized / quantized models don't correspond if I change the model in my script. In this case, the `export()` reuses the old non-quantized model to generate the quantized model, and all the quantizer attributes are ignored!

### Your contribution

I can do this if approved

**Comment by regisss** [comment]
I agree with @fxmarty here, I got similar unexpected behaviors because of this.

**Comment by echarlaix** [comment]
Thanks for pointing it out, the `ORTQuantizer` class is currently being refactorized in #270 and this behavior was removed.
