### ISSUE TITLE
Quantization and Optimization for Convnext models.

### ISSUE THREAD

**Issue by dingusagar** [huggingface/optimum#291]
### Feature request

Wanted to try optimization and quantization for facebook/convnext-base-224.

### Motivation

Was trying out various image models for a image vector search usecase. Found the embeddings of this model to be really good in getting semantic matches. But the inference latency is around 668 ms for a single image. Just converting it to onnx using transformers.onnx brought down the time to 532ms. Would like to see if quantization and optimisation techniques would help to bring it down even further. 

### Your contribution

Would love to give it a try if someone can point me to some reference code/materials for other similar models.

**Comment by kofi2614** [comment]
Is it possible to combine both optimization and quantization

**Comment by echarlaix** [comment]
Hi @kofi2614, 

Yes it is possible to combine optimization with quantization as described in https://github.com/huggingface/optimum/issues/198

**Comment by regisss** [comment]
@kofi2614 As @echarlaix said, it is possible to combine them. However, depending on the optimization level you applied, it is possible that some operators are not recognized anymore and thus they are not quantized. So I recommend you to pay attention to this.
