### ISSUE TITLE
Pipeline "zero-shot-classification" is not supported

### ISSUE THREAD

**Issue by Sudo-Swapnil** [huggingface/optimum#297]
### System Info

```shell
google colab:
   optimum==1.3.0, python==3.7.13

two ubuntu 20.04 systems:
   transformers==4.20.1
   optimum==1.2.3
   python==3.9.12

docker:
   transformers==4.20.1
   optimum==1.2.3
   python==3.9.12
```

### Who can help?

@philschmid 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to load "zero-shot-classification" pipeline. I am getting the following error:

```
from optimum.pipelines import pipeline

classifier = pipeline(task="zero-shot-classification", accelerator="ort")
```

```
ValueError                                Traceback (most recent call last)
[<ipython-input-3-0f041b354f55>](https://localhost:8080/#) in <module>()
      1 from optimum.pipelines import pipeline
      2 
----> 3 classifier = pipeline(task="zero-shot-classification", accelerator="ort")

[/usr/local/lib/python3.7/dist-packages/optimum/pipelines.py](https://localhost:8080/#) in pipeline(task, model, tokenizer, feature_extractor, use_fast, use_auth_token, accelerator, **kwargs)
    106 
    107     if targeted_task not in list(SUPPORTED_TASKS.keys()):
--> 108         raise ValueError(f"Task {targeted_task} is not supported. Supported tasks are { list(SUPPORTED_TASKS.keys())}")
    109 
    110     if accelerator != "ort":

ValueError: Task zero-shot-classification is not supported. Supported tasks are []
```

### Expected behavior

Pipeline should download the default model.

**Comment by regisss** [comment]
@Sudo-Swapnil  I don't manage to reproduce it. With Optimum 1.2.3, it works. With Optimum 1.3.0, I get another error:
```shell
Traceback (most recent call last):
  File "test_yolos.py", line 3, in <module>
    classifier = pipeline(task="zero-shot-classification", accelerator="ort")
  File "/home/regis/HuggingFace/dev/tmp_venv/lib/python3.8/site-packages/optimum/pipelines.py", line 113, in pipeline
    load_tokenizer = type(model.config) in TOKENIZER_MAPPING or model.config.tokenizer_class is not None
AttributeError: 'NoneType' object has no attribute 'config'
```
I'm going to open a PR to solve this one.

I can confirm you that `zero-shot-classification` is in `SUPPORTED_TASKS` in both versions 1.2.3 and 1.3.0 IF `onnxruntime` is installed. Could you install Optimum with `pip install optimum[onnxruntime]` and let us know if it solves your issue?

**Comment by regisss** [comment]
The error mentioned in my previous message is fixed in #301.

**Comment by Sudo-Swapnil** [comment]
Thanks
> `pip install optimum[onnxruntime]` 

worked for me. (with version 1.2.3)

Also, I noticed that the optimum pipeline calls 'ort' accelerator by default [(see here)](https://github.com/huggingface/optimum/blob/7c1a6211079ea03a899a0afb801fac1599be999d/optimum/pipelines.py#L101
)

It would be great if `pip install optimum` by default, installs `pip install optimum[onnxruntime]` .
If it is fine by you, I could raise a PR to change this in the documentation.

**Comment by regisss** [comment]
@Sudo-Swapnil Optimum comes with a lot of subpackages (onnxruntime, intel, graphcore, habana) and we prefer not installing by default a library that won't be used by other subpackages and might create conflicts. So I think we should keep `onnxruntime` out of the base install.

However, the documentation may not be clear regarding the different possible setup configurations. Do not hesitate to propose a PR to improve it.

Closing this issue.
