### ISSUE TITLE
Add support for encoder-decoder models

### ISSUE THREAD

**Issue by Serlopal** [huggingface/optimum#367]
### Feature request

Optimum has recently added support for encoder-decoder type models. I have succesfully converted some of them (such as mt5) to ONNX using optimum. However, I have a encoder-decoder type model (https://huggingface.co/docs/transformers/model_doc/encoder-decoder) built using 2x Roberta type models from the hub, that I want to convert to ONNX. Whenever I try to do so, I get an “unsupported” message, giving me a list of the supported models (using this tutorial https://huggingface.co/blog/convert-transformers-to-onnx which seems to be in line with the docs).

```
from pathlib import Path
import transformers
from transformers.onnx import FeaturesManager
from transformers import AutoConfig, AutoTokenizer, AutoModelForSequenceClassification, AutoModelForSeq2SeqLM

# load model and tokenizer
model_id = "path/to/model"
tokenizer_id = "path/to/tokenizer"
feature = "seq2seq"
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(tokenizer_id)

# load config
model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model, feature=feature)
onnx_config = model_onnx_config(model.config)

# export
onnx_inputs, onnx_outputs = transformers.onnx.export(
        preprocessor=tokenizer,
        model=model,
        config=onnx_config,
        opset=13,
        output=Path("trfs-model.onnx")
)
```

And this is the exception that I get, suggesting that I open an issue here

_KeyError: "encoder-decoder is not supported yet. Only ['albert', 'bart', 'beit', 'bert', 'big-bird', 'bigbird-pegasus', 'blenderbot', 'blenderbot-small', 'bloom', 'camembert', 'codegen', 'convbert', 'convnext', 'data2vec-text', 'deberta', 'deberta-v2', 'deit', 'detr', 'distilbert', 'electra', 'flaubert', 'gpt2', 'gptj', 'gpt-neo', 'ibert', 'layoutlm', 'layoutlmv3', 'levit', 'longt5', 'marian', 'mbart', 'mobilebert', 'mobilevit', 'm2m-100', 'perceiver', 'resnet', 'roberta', 'roformer', 'squeezebert', 't5', 'vit', 'xlm', 'xlm-roberta', 'yolos'] are supported. If you want to support encoder-decoder please propose a PR or open up an issue."_

Since encoder-decoder models are a bit of a special case (Roberta is actually supported, but the combination of two of them in the form of a encoder-decoder model does not seem to be) **I wanted to ask if there's actually a way for me to optimize my model’s inference in production using Optimum to use a ONNX version of the same.** Right now the model is extremely slow taking close hundreds of miliseconds to perform inference in a single string using the generate function, and I hope I can improve on that.

Thanks for your help,

Sergio

### Motivation

I want to be able to use encoder-decoder models in production, but the generate method is extremely slow in its baseline form. ONNX seems to be a great method of speeding up the model's inference times.

### Your contribution

.

**Comment by michaelbenayoun** [comment]
Hi @Serlopal ,
The ONNX export of encoder - decoder models, as well as optimizing them, is something that we are currently working on.
This should come soon!
cc @mht-sharma

**Comment by mht-sharma** [comment]
hi @krtin I have started working on the export of such models. PR [588](https://github.com/huggingface/optimum/pull/588) for reference

**Comment by fxmarty** [comment]
Fixed in https://github.com/huggingface/optimum/pull/588

**Comment by mht-sharma** [comment]
Reopening as only as only a generic class was added in #588 and export is not yet supported
