### ISSUE TITLE
Add support for ViT MAE

### ISSUE THREAD

**Issue by RobertHua96** [huggingface/optimum#380]
### Feature request

Currently ViT MAE isn't supported by ORT to export to ONNX

### Motivation

ViT MAE is one of the more effective ways to pre-train a vision transformer. It would be great if we could get further benefits from optimising it with the Optimum library!

### Your contribution

-

**Comment by michaelbenayoun** [comment]
Hi @RobertHua96,
You would love to be able to export ViT MAE to the ONNX format right?
We are currently working on adding ONNX export features to `optimum`, and will try to support this architecture as well.

**Comment by RobertHua96** [comment]
Amazing! Really looking forward to it
