### ISSUE TITLE
what the difference between decoder_model.onnx and decoder_with_past_model.onnx

### ISSUE THREAD

**Issue by akk-123** [huggingface/optimum#390]
### Feature request

none

### Motivation

none

### Your contribution

none

**Comment by echarlaix** [comment]
Hi @akk-123,

The difference is that the `decoder_with_past_model.onnx` has the pre-computed key/values hidden-states as one of its inputs while the `decoder_model.onnx` has not. See [here](https://huggingface.co/docs/optimum/onnxruntime/modeling_ort#export-and-inference-of-sequencetosequence-models) for more information.

**Comment by ayansengupta17** [comment]
@echarlaix  The link is not available anymore, can you please update your last comment?

**Comment by regisss** [comment]
@ayansengupta17 It has been moved [here](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/models#export-and-inference-of-sequencetosequence-models).
