### ISSUE TITLE
Static quantization doesn't work with calibration mode 'percentile' and 'entropy'

### ISSUE THREAD

**Issue by MathVast** [huggingface/optimum#409]
### System Info

```shell
python == 3.9.10
optimum == 1.4.0
transformers == 4.22.0
```

### Who can help?

@echarlaix @JingyaHuang 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am currently working on quantization for a Ranker so I am trying to transpose the [example code](https://github.com/huggingface/optimum/tree/main/examples/onnxruntime/quantization/text-classification) provided for GLUE on MS-MARCO. 
When launching the script with dynamic quantization mode, everything works fine (no matter the calibration mode, reduce-range to True, etc.). The problem occurs with static quantization mode and when the calibration mode is set to 'percentile' or 'entropy'. The error that I get when running the script is : "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". It happens during the call to collect_value() with the HistogramCollector, in the call to quantizer.partial_fit().
I have observed that the problem only appears when calibration_batch_size is superior to 1 (in my case, 8).

To be sure that the problem wasn't due to my dataset, I went back to the original script on GLUE and ran the command given as an example but observed the same behavior.

### Expected behavior

Static quantization working with the different calibration methods and for batch sizes superior to 1.

**Comment by regisss** [comment]
Hi @MathVast, thanks for using Optimum! I think this may be related to #331. Could you try to set `calibration_batch_size` as a divisor of your total number of calibration samples and let me know if it works please? To confirm whether this is the same issue as #331 or not.

**Comment by MathVast** [comment]
Hi @regisss and thanks for the answer! I kept working on it since posting the issue and this was the fix that I came up with and it did make the whole thing work.
