### ISSUE TITLE
 Failed to create CUDAExecutionProvider.

### ISSUE THREAD

**Issue by hungnmai** [huggingface/optimum#416]
### System Info

```shell
Linux
Python version: 3.8.13
Cuda version: 11.6
GPU Tesla T4 16Gb
Python Libraries:

- transformers==4.22.1
- optimum==1.3.0
- onnx==1.12.0
- onnxruntime-gpu==1.12.1

```

### Who can help?

Hello @JingyaHuang and @echarlaix
I have an issue when running with onnx-gpu. I get an error  **Failed to create CUDAExecutionProvider.** when load model:
`model = ORTModelForQuestionAnswering.from_pretrained(
model_name,
                                                     file_name="model-optimized.onnx",
                                                     use_auth_token=access_token,
                                                     cache_dir=onnx_path)`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`model = ORTModelForQuestionAnswering.from_pretrained(model_name,file_name="model-optimized.onnx",
                                                     use_auth_token=access_token,
                                                     cache_dir=onnx_path)`

### Expected behavior

ONNX model can run with GPU

**Comment by michaelbenayoun** [comment]
Hi @hungnmai, 
Can you share the full error message please, I am able to run this on my end:
```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForQuestionAnswering

tok = AutoTokenizer.from_pretrained("bert-base-uncased")
model = ORTModelForQuestionAnswering.from_pretrained(
    "bert-base-uncased",
    from_transformers=True, 
    provider="CUDAExecutionProvider"
)

model(**tok("this is a test", return_tensors="pt"))
```

It might be an installation issue, but I cannot confirm without the full error message.

**Comment by BNDSllx** [comment]
Maybe your ORT version and CUDA version don't match, try checking the [version requirement](https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html)

**Comment by fxmarty** [comment]
closed in https://github.com/huggingface/optimum/pull/514
