### ISSUE TITLE
"self.log_level" required to be string instead of int, while optimum convert it into int in function __init__

### ISSUE THREAD

**Issue by zhijxu-MS** [huggingface/optimum#418]
### System Info

```shell
optimum and transformers are all installed from source code.
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

the shell command to reproduce:
`python -m torch.distributed.launch --nproc_per_node=1 /optimum/examples/onnxruntime/training/text-classification/run_glue.py --model_name_or_path distilbert-base-uncased --task_name mnli --max_seq_length 128 --learning_rate 3e-6 --do_train --output_dir /dev/shm --overwrite_output_dir --max_steps 200 --logging_steps 20 --per_device_train_batch_size 1300 --fp16 --optim adamw_ort_fused`

the error log is 
![image](https://user-images.githubusercontent.com/43435212/194693485-9ea24671-460a-404c-97a5-52b94fbce662.png)

the root cause is the transformer PR https://github.com/huggingface/transformers/pull/19239

### Expected behavior

the command should be runnable with default args.

**Comment by JingyaHuang** [comment]
Hi @zhijxu-MS, thanks for reporting!

I linked a PR that will fix the bug, and I added a test for DDP to track the breaking changes led by the updates in transformers.
