### ISSUE TITLE
Tried to load a model to both cores of a two-core GPUs, but only one core (device:0) is used. 

### ISSUE THREAD

**Issue by mrxiaohe** [huggingface/optimum#426]
I used Optimum to convert a finetuned `xlm-roberta-base` model to an ONNX model by following the tutorial in [this link](https://huggingface.co/docs/optimum/quicktour). I have a two core GPU. When I tried to load the original finetuned model, I was able to load it to both cores of my GPU. But for some reason, when I try it with the ONNX model, the model only gets loaded into one of the cores. And because of that, that core's memory gets maxed out. 

The code that deals with model loading is below, and any suggestion and advice would be much appreciated! 

```
def worker(i, sents, model_path):
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = ORTModelForSequenceClassification.from_pretrained(model_path)
    if i % 2 == 0:        
        pipe = pipeline("text-classification", 
                        model=model
                        tokenizer=tokenizer, 
                        padding="max_length", 
                        max_length=96, 
                        truncation=True, 
                        device=0, 
                        batch_size=64)
    else:
        pipe = pipeline("text-classification", 
                        model=model, 
                        tokenizer=tokenizer, 
                        padding="max_length", 
                        max_length=96, 
                        truncation=True, 
                        device=1, 
                        batch_size=64)
    scores = pipe(sents)
    return scores
```

**Comment by fxmarty** [comment]
Thank you! This a limitation from https://github.com/huggingface/optimum/blob/d15b47f6f0ab750b1203463f98869a8bcbb99c77/optimum/onnxruntime/modeling_ort.py#L141-L153 . Let me fix this shortly.

**Comment by mrxiaohe** [comment]
Thanks! @fxmarty. How do I install the updated version of optimum?

**Comment by fxmarty** [comment]
The PR is merged for the fix.

Could you try
```
pip uninstall optimum
pip install git+https://github.com/huggingface/optimum.git@main
```

This will install the development branch of Optimum before the next release. You script should then work as is. Let me know if there is still any issue.
