### ISSUE TITLE
Add support for ORTModelForVision2Seq

### ISSUE THREAD

**Issue by entropy2333** [huggingface/optimum#451]
### Feature request

I would like to use VisionEncoderDecoderModel (such as [Donut](https://huggingface.co/docs/transformers/model_doc/donut) or [TrOCR](https://huggingface.co/docs/transformers/model_doc/trocr)) for vision2seq-lm tasks. 

### Motivation

I use HuggingFace's TrOCR for an vision2seq-lm task and would love to improve my inference speeds. ONNX conversion of such model is already [supported](https://github.com/huggingface/transformers/issues/19604) by executing

```bash
python -m transformers.onnx --model="microsoft/trocr-base-printed" --feature=vision2seq-lm trocr_onnx/ --atol 1e-3
```

I hope to leverage onnx support for ORTModelForVision2Seq.

Example usage:
```python
from transformers import TrOCRProcessor
from optimum.onnxruntime.modeling_vision2seq import ORTModelForVision2Seq

processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-printed')
onnx_model = ORTModelForVision2Seq.from_pretrained(
    "microsoft/trocr-base-printed", 
    from_transformers=True,
    use_cache=True,
)
pixel_values = processor(images=image, return_tensors="pt").pixel_values
generated_ids = onnx_model.generate(pixel_values)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
```

### Your contribution

Please let me know what needs to be done to add this support!

**Comment by JingyaHuang** [comment]
Hi @entropy2333 !

Thanks for bringing the request, we are definitely interested in adding ONNX Runtime support for vision encoder-decoder models.  Gently pinging @mht-sharma for some inputs.

**Comment by mht-sharma** [comment]
Hi @entropy2333 , thank you for your interest in contributing `ORTModelForVision2Seq` class in `optimum`. Currently we are in process of doing some refactor in optimum which will change how the existing integration of `ORTModel` works. 

Would suggest to wait for that update before integrating the above class.

**Comment by arj7192** [comment]
Hi,
Are there any updates on this feature request?
Thanks!

**Comment by mht-sharma** [comment]
Hi @arj7192  the PR for `ORTModelForVision2Seq` is merged here https://github.com/huggingface/optimum/pull/742

**Comment by arj7192** [comment]
May I ask why Donut model could not supported still, as mentioned in [the PR](https://github.com/huggingface/optimum/pull/742)

**Comment by dneemuth** [comment]
> Thanks @mht-sharma! May I ask why Donut model could not supported still, as mentioned in [the PR](https://github.com/huggingface/optimum/pull/742)

Thanks a lot @mht-sharma  I've been working with Donut model, have succeeded up-to now to convert to onnx model. but curretnly stuck with making the inference part work with the onnx model. any ideas how to proceed ? thanks.
