### ISSUE TITLE
Add possibility to trigger nightly tests manually in PRs

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#465]
### Feature request

Currently nightly tests as onnxruntime gpu tests can not be run in PRs. Would be nice to be able to.

### Motivation

Check before merging that changes related to nightly tests are fine.

### Your contribution

Maybe like https://github.com/microsoft/onnxruntime/pull/13536#issuecomment-1300588976 ?

Does it exist on transformers? Not familiar with GitHub but there should be an easy way, I guess.

**Comment by regisss** [comment]
The super easy solution here is to just add `workflow_dispatch` to the list of triggering events in your workflow, such as here for generating the doc: https://github.com/huggingface/optimum/blob/df66bd3468e21044050f49b36056405bc40b08fb/.github/workflows/build_main_documentation.yml#L9

It will enable you to choose the branch you want to run the workflow on. For example, also for the doc, you can click on "Run workflow" and then select any branch you want: https://github.com/huggingface/optimum/actions/workflows/build_main_documentation.yml

But I'm not sure if that's exactly what you want.

**Comment by fxmarty** [comment]
Yes, it works in case the branch is under huggingface/optimum. I tend to work on my fork so could not launch the workflows.
