### ISSUE TITLE
BetterTransformers Support For DeBERTaV3

### ISSUE THREAD

**Issue by forrestfaraday** [huggingface/optimum#487]
### Feature request

Hello, I often use libraries developed by Huggingface in my projects. 
I follow your innovations and  I want to implement them in my projects. BetterTransformers intrigued me and I want to try it with Debertav3. When I tried BetterTransformer with DeBERTaV3, It gave `NotImplementedError: The Better Transformers implementation for the model DebertaV2ForTokenClassification has not been implemented yet. Please open an issue requesting the addition of this model with its BetterTransformer implementation.`
 When can you provide BetterTransformer support for Debertav3?
 
You are doing great work, thank you

### Motivation

I look forward to trying Better Transformer and seeing results.

### Your contribution

Thanks for all

**Comment by younesbelkada** [comment]
Hi @forrestfaraday 
Thank you very much for your message and your interest in `BetterTransformer` integration! 🎉 
Unfortunately DeBERTa uses a special type of attention mechanism, which is not currently supported :/ Check out the specific conditions on the documentation [here](https://huggingface.co/docs/optimum/bettertransformer/tutorials/contribute). Is there any other architecture you might be interested in? We are also planning to open "Good first issues" for contributing in `BetterTransformer` - you'll see, it's should be very easy to add new models and we'll be here to help you!

cc @michaelbenayoun @fxmarty

**Comment by forrestfaraday** [comment]
Thank you for your attention to my issue. Recently I have focused on BetterTransformer and optimum[ONNX] specifically to speed up deberta models. 
I sincerely support your work. 
Your success makes it easy for us to do our job.
Best wishes

**Comment by younesbelkada** [comment]
Thank you very much for your words @forrestfaraday !
