### ISSUE TITLE
[BT] Documentation clarification

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/optimum#518]
### System Info

Moved the issue from: @ravenouse https://github.com/huggingface/hub-docs/issues/528

> I found some dead links and some unclear points on this tutorial webpage.
> In Step 2: Building the xxxLayerBetterTransformer module, the link to modeling_encoder.py is dead.
> In Step 4: Sanity check!, the link to tutorials sections is dead.
>The description about what conditions the BetterTransformer are not applied is unclear and kinda confusing, particularly for the even head condition. On this tutorial, it seems that the model should have an even number of head to be convertible, while on this notebook, the even head seems to prevent the model to be converted.
> Could you help to solve these problems?
> Thank you so much.

**Comment by younesbelkada** [comment]
Hi @ravenouse ! 
Let's move the discussion here ;) 
Thanks again for raising the issues! Some points might need some clarification indeed yes!
Regarding your points 1 & 2 the PR https://github.com/huggingface/optimum/pull/517 should hopefully resolve the dead links
For the last point, could you elaborate more on the concern? `roberta-base` has indeed an even number of heads as you can confirm it from the config file: https://huggingface.co/roberta-base/blob/main/config.json#L16 and the model is correctly converted (from `print(bt_model)` you can see that the `RobertaLayer` are replaced by the `BertLayerBetterTransformer`.) In other words, as long as `num_attention_heads % 2 == 0`, then your architecture respects one of the conversion condition.

**Comment by fxmarty** [comment]
@younesbelkada just did the edit. Thanks for the feedback!
