### ISSUE TITLE
Add `BetterTransformers` support for `M2M100` models

### ISSUE THREAD

**Issue by xhluca** [huggingface/optimum#521]
### Feature request

Adding support for M2M100 would allow running faster translation on GPUs thanks to the optimizations in the BetterTransformers module.

It would also benefit the decoder in addition to the encoder:
> Other transformer models (such as decoder models) which use the PyTorch MultiheadAttention module will benefit from the BetterTransformer fastpath. Planned future work is to expand the end-to-end BetterTransformer fastpath to models based on [TransformerDecoder](https://pytorch.org/docs/stable/generated/torch.nn.TransformerDecoder.html) to support popular seq2seq and decoder-only (e.g., [OPT](https://ai.facebook.com/blog/democratizing-access-to-large-scale-language-models-with-opt-175b/)) model architectures, and to training.

### Motivation

It is currently not implemented. If we try to use BetterTransformers, it gives the following error:
```
NotImplementedError: The Better Transformers implementation for the model M2M100ForConditionalGeneration has not beenimplemented yet. Please open an issue requesting the addition of this model with its `BetterTransformer`implementation.
```

### Your contribution

I am unfortunately not familiar with optimum to help

**Comment by younesbelkada** [comment]
Thanks a lot for your interest in the addition of `M2M100` model for `BetterTransformer`
Note that the model is currently being converted in this PR: https://github.com/huggingface/optimum/pull/516 - as soon as this PR is merged, anyone will be able to use `BetterTransformer` support for `M2M100` !

**Comment by younesbelkada** [comment]
#516 has just been merged, you can use NLLB with `BetterTransformer` on the main branch of `optimum` now!

**Comment by xhluca** [comment]
Cool! Trying it now.

Does that mean M2M100 and MBart50 will be supported soon?

**Comment by fxmarty** [comment]
@xhluca Yes, in the next release of Optimum!

If you want to try out right away (at your own risk), you can with the dev branch: `pip install -U git+https://github.com/huggingface/optimum.git@main`
