### ISSUE TITLE
🚀  Add built-in support for autorregressive text generation with ONNX models.

### ISSUE THREAD

**Issue by piEsposito** [huggingface/optimum#55]
# 🚀  Add built-in support for autorregressive text generation with ONNX models.

After converting a autorregressive model to ONNX, it would be nice to be able to generate text with it via something like:
```python
from transformers import OnnxTextGenerationModel, AutoTokenizer

model_path = "gpt-something.onnx"
tokenizer_name = "gpt2"

model = OnnxTextGenerationModel(model_path)

# and then

text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model.generate(encoded_input)
```

With support to using `past_key_values` internally in the most efficient way. 

## Motivation

When trying to accelerate inference with transformers, being unable to load our ONNX model with the lib and running a `model.generate` method to seamlessly generate sequences and perform Beam Search is somehow frustrating. That leads us to have to rely on custom implementations - which takes time and are a lot more prone to have bugs.

**Comment by philschmid** [comment]
Hey @piEsposito, 

This is now supported with the latest release of optimum v1.2, which introduces `ORTModelForXXX` and support for pipelines. 
You can learn more about in:
* our new blog: https://huggingface.co/blog/optimum-inference
* or the documentation: https://github.com/huggingface/optimum/issues/55

Here is an example

  ```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
import torch

model_path = "path/to/gpt-something.onnx"
# the model_path also needs to include the `config.json` from the original model
tokenizer_name = "gpt2"

tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
model = ORTModelForCausalLM.from_pretrained(model_path)

inputs = tokenizer("My name is Philipp and I live in Germany.", return_tensors="pt")

gen_tokens = model.generate(**inputs,do_sample=True,temperature=0.9, min_length=20,max_length=20)
tokenizer.batch_decode(gen_tokens)
```

**Comment by piEsposito** [comment]
Hugging Face rocks.

**Comment by kargarisaac** [comment]
@piEsposito 
I have one onnx model locally and cannot use the above script. How should I do that? Should I push it to huggingface hub and then use `model = ORTModelForCausalLM.from_pretrained(model_path)`?
right now I'm using:
```python
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
import torch

model_path = "./onnx/model.onnx"

tokenizer = AutoTokenizer.from_pretrained(model_name)
opt_model = ORTModelForCausalLM.load_model(model_path) # from_pretrained(model_path, config=onnx_config)

inputs = tokenizer(prompt, return_tensors="pt")

gen_tokens = model.generate(**inputs,do_sample=True,temperature=0.9, min_length=10,max_length=20)
tokenizer.batch_decode(gen_tokens)
```

and I get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-16-6b46c703da9c>](https://localhost:8080/#) in <module>()
     10 inputs = tokenizer(prompt, return_tensors="pt")
     11 
---> 12 gen_tokens = model.generate(**inputs,do_sample=True,temperature=0.9, min_length=10,max_length=20)
     13 tokenizer.batch_decode(gen_tokens)

AttributeError: 'InferenceSession' object has no attribute 'generate'
```

**Comment by harishankar-gopalan** [comment]
Hi I went through the code for S2S generation in optimum. I wanted to understand where the beam search is happening exactlt. My expectation was that it should happen in the ORTDecoder or the ORTModelForConditionedGeneration or ORTModelForSeq2SeqLM 's forward pass. But I couldn't find it exactly in the code. Is there some doc or a brief pointer to understand the beam search part of the implementation ?

**Comment by philschmid** [comment]
@harishankar-gopalan the S2S model can use the [GenerationMixin](https://github.com/huggingface/optimum/blob/ee8350541b8286b1dadd138df3fcc595ef17be3f/optimum/onnxruntime/modeling_seq2seq.py#L559) since we implement a coherent API to `transformers`. 
You can find the code for the GenerationMixin [here](https://github.com/huggingface/transformers/blob/main/src/transformers/generation_utils.py#L379)

**Comment by harishankar-gopalan** [comment]
@philschmid Thanks for the update. I did manage to find out after some deep diving into the HuggingFace Transformers repo.
