### ISSUE TITLE
BetterTransformer for T5ForConditionalGeneration 

### ISSUE THREAD

**Issue by R4ZZ3** [huggingface/optimum#577]
### Feature request

Got this error when trying out BetterTransformer:
"The Better Transformers implementation for the model T5ForConditionalGeneration has not been implemented yet. Please open an issue requesting the addition of this model with its BetterTransformerimplementation."

### Motivation

I would like to speed up some text2text models with BetterTransformer

### Your contribution

I can at least test the feature once it is ready

**Comment by younesbelkada** [comment]
Hi @R4ZZ3 
Thanks so much for your interest in BetterTransformer! 
As stated in https://github.com/huggingface/transformers/issues/20372#issuecomment-1324736962 , sadly T5 cannot be supported yet for BetterTransformer

**Comment by fxmarty** [comment]
@younesbelkada Maybe we should add in the doc a section of models that can't be supported.

**Comment by R4ZZ3** [comment]
Yeah, maybe the error message should also be adjusted accordingly

**Comment by fxmarty** [comment]
Hi @R4ZZ3 , more informative error messages are added in https://github.com/huggingface/optimum/pull/594

**Comment by younesbelkada** [comment]
Thanks for addressing this @fxmarty let's close the issue!
