### ISSUE TITLE
About the input of the onnx model (encoder, decoder, decoder_with_past)

### ISSUE THREAD

**Issue by young-chao** [huggingface/optimum#583]
## Background
Because I found out that there are [performance problems](https://github.com/huggingface/optimum/issues/524) in loading the onnx model for inference by using the pipeline method, I tried to design the beam search solution by myself, and used numpy.array instead of torch.tensor for inference throughout the inference process, but I encountered some problems.

## Question:
I still haven't figured out the actual meaning of "input_ids" and "encoder_attention_mask" from the source code debugging, so I can't provide accurate input to decoder_with_past_model during the beam search process. 

## Model Inputs
decoder_with_past_model.onnx:
name: input_ids
type: int64[batch,past_decoder_sequence + sequence]

name: encoder_attention_mask
 type: int64[batch,encoder_sequence]

**Comment by fxmarty** [comment]
@young-chao Have you solved your issue?
