### ISSUE TITLE
ONNX export of decoder/decoder with past has unwanted output nodes

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#599]
### System Info

```shell
Transformers commit: 3ee958207a9830da6afcf2c20772ef9a2159ca30
Optimum commit: 9c71dd52f71f397bd97da2228691a3c7049f4452
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python3 -m optimum.exporters.onnx --model t5-small --task seq2seq-lm-with-past --for-ort t5_onnx
```

![image](https://user-images.githubusercontent.com/9808326/208106672-a1cf1af2-00ba-4057-ac80-28016d9b77ab.png)

### Expected behavior

No unwanted output node

**Comment by fxmarty** [comment]
cc @JingyaHuang I'll look into it

**Comment by fxmarty** [comment]
For decoder with/without past it's the same:

![image](https://user-images.githubusercontent.com/9808326/208107251-a9c389b1-78ba-41c3-a371-927b2d391b2e.png)

**Comment by fxmarty** [comment]
@mht-sharma looks similar to the issue you had no?

**Comment by mht-sharma** [comment]
This is a new issue, have observed this a little back in a few models. 

I have a saved checkpoint of t5 with me but I do not see the node. Some option in the modelling code might be returning the `encoder_hidden_states` with `hidden_states`?

**Comment by fxmarty** [comment]
yes exactly Mohit!
