### ISSUE TITLE
Unable to load whisper model using ORTModelForSpeechSeq2Seq

### ISSUE THREAD

**Issue by Rishabh-Choudhry** [huggingface/optimum#632]
### System Info

```shell
onnxruntime==1.13.1
optimum==1.5.2
python=3.8.12
```

### Issue

Loading the whisper model using 'ORTModelForSpeechSeq2Seq' throws the following error:

> KeyError: "Unknown task: speech2seq-lm. Possible values are [<class 'transformers.models.auto.modeling_auto.AutoModel'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMaskedLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSequenceClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForTokenClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMultipleChoice'>, <class 'transformers.models.auto.modeling_auto.AutoModelForObjectDetection'>, <class 'transformers.models.auto.modeling_auto.AutoModelForQuestionAnswering'>, <class 'transformers.models.auto.modeling_auto.AutoModelForImageClassification'>, <class 'transformers.models.auto.modeling_auto.AutoModelForImageSegmentation'>, <class 'transformers.models.auto.modeling_auto.AutoModelForMaskedImageModeling'>, <class 'transformers.models.auto.modeling_auto.AutoModelForSemanticSegmentation'>, <class 'transformers.models.auto.modeling_auto.AutoModelForVision2Seq'>]"

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

To reproduce, simply try loading the model:
```
from optimum.onnxruntime import ORTModelForSpeechSeq2Seq

model = ORTModelForSpeechSeq2Seq.from_pretrained("openai/whisper-tiny.en", from_transformers=True, use_cache=True)

```

### Expected behavior

Should be able to load the whisper model using 'ORTModelForSpeechSeq2Seq'.

**Comment by fxmarty** [comment]
@Rishabh-Choudhry I have no issue using transformers==4.25.1 and optimum==1.5.2. Can you confirm?

**Comment by Rishabh-Choudhry** [comment]
Yes, it works fine after updating the transformers version to 4.25.1.

**Comment by fxmarty** [comment]
Awesome!
