### ISSUE TITLE
Causal attention hard-codes lower triangular matrices as uint8

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#636]
### System Info

```shell
- `optimum` version: 1.5.3.dev0
- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
- Python version: 3.9.12
- Huggingface_hub version: 0.12.0.dev0
- PyTorch version (GPU?): 1.13.1+cu117 (cuda availabe: True)
- Tensorflow version (GPU?): 2.9.1 (cuda availabe: True)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Not necessarily a bug per se. Likely due to e.g. https://github.com/huggingface/transformers/blob/4d10ffd50614ebcdfe7e99c0092740f0f7234923/src/transformers/models/gpt2/modeling_gpt2.py#L196 . Similar for other models.

```
optimum-cli export onnx --model gpt2 --task causal-lm --for-ort gpt2_onnx
```

![image](https://user-images.githubusercontent.com/9808326/209191770-718fe7b1-fd55-4a40-9586-cf3c955e9b07.png)

### Expected behavior

/

**Comment by fxmarty** [comment]
Related: https://github.com/huggingface/optimum/issues/627

**Comment by fxmarty** [comment]
Actually comes from https://github.com/huggingface/transformers/blob/4d10ffd50614ebcdfe7e99c0092740f0f7234923/src/transformers/models/gpt2/modeling_gpt2.py#L130 .

I have no idea why `torch.uint8` is used and not `torch.bool` here. Any idea @LysandreJik @sgugger ?

**Comment by sgugger** [comment]
My best guess would be because it's very old code and PyTorch did not support `torch.bool` back then.

**Comment by fxmarty** [comment]
Closing as in any case pytorch represents torch.bool on a byte (https://github.com/pytorch/pytorch/issues/41571#issuecomment-830174411), and ONNX as well (checking the initializer ByteSize()).
