### ISSUE TITLE
A weird input in onnx graph from ORTModel pretrained FlauBERT

### ISSUE THREAD

**Issue by BenoitHardier** [huggingface/optimum#667]
### System Info

```shell
Python 3.8.10
"optimum[onnxruntime]==1.5.0"
"transformers==4.25.1"
```

### Who can help?

Probably export bug so -> @lewtun, @michaelbenayoun

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from optimum.onnxruntime import ORTModelForFeatureExtraction
from transformers import AutoTokenizer

model = ORTModelForFeatureExtraction.from_pretrained('flaubert/flaubert_base_uncased', from_transformers=True)
tokenizer = AutoTokenizer.from_pretrained("flaubert/flaubert_base_uncased")
inputs = tokenizer("Le chat mange une pomme.", return_tensors="pt")
pred = model(**inputs)
```

### Expected behavior

I should get a `BaseModelOutPut` with `last_hidden_state` tensor as `pred` variable (or something close to that). Actually, when I replace the FlauBERT model `flaubert/flaubert_base_uncased` by another french model CamemBERT `camembert/camembert-base` the above snippet works as expected. (I tried this on my cpu, no gpus involved)
   
But I get an `InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:token_type_ids`.
So I investigate the input of the onnx model graph and find a weird third input with static dimensions:   
```
 name: "input.5"
type {
  tensor_type {
    elem_type: 7
    shape {
      dim {
        dim_value: 2
      }
      dim {
        dim_value: 8
      }
    }
  }
}
```
This input should probably not be there and I suspect that the export is broken in some way for FlauBert model.
(I also get  `TraceWarning` when exporting caused by asserts located in the `forward` method of the transformer implementation of FlauBERT but I am not sure if it is related to my issue)

**Comment by michaelbenayoun** [comment]
Hi @BenoitHardier,

You are right, the `FlaubertOnnxConfig` should not inherint from `DistilBertOnnxConfig` but from `BertOnnxConfig`, #669 fixes that.
