### ISSUE TITLE
ORTQuantizer file_name argument not working

### ISSUE THREAD

**Issue by hlums** [huggingface/optimum#681]
### System Info

```shell
optimum: optimum @ git+https://github.com/huggingface/optimum.git@e19928316bbf66047085160fb0adaf1a25da3751
Platform: Ubuntu
Python: 3.7.13
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Although the ORTQuantizer.from_pretrained method has a file_name parameter, the actual code still complains if there are multiple onnx files in the ort_model path. 
```
quantizer = ORTQuantizer.from_pretrained(ort_model, file_name=model_file)
```
Traceback (most recent call last):
  File "/home/honglu/RC.Scripts/onnx/pytorch2onnx/optimum_export.py", line 144, in <module>
    export_hf_model_to_onnx(model_dir, transformer_task)
  File "/home/honglu/RC.Scripts/onnx/pytorch2onnx/optimum_export.py", line 85, in export_hf_model_to_onnx
    quantizer = ORTQuantizer.from_pretrained(ort_model, file_name=model_file)
  File "/home/honglu/miniconda3/envs/question_generation/lib/python3.7/site-packages/optimum/onnxruntime/quantization.py", line 136, in from_pretrained
    raise ValueError(ort_quantizer_error_message)
ValueError: ORTQuantizer does not support multi-file quantization. Please create separate ORTQuantizer instances for each model/file.

### Expected behavior

The ORTQuantizer should be initialized for the onnx file specified by file_name.

**Comment by fxmarty** [comment]
Hi @hlums , thanks for the report. Yes I agree https://github.com/huggingface/optimum/blob/bc5e10fb15b04f79ce25dd99823ec9c49b984e1c/optimum/onnxruntime/quantization.py#L137-L145 is quite harsh, we will soften it!

**Comment by fxmarty** [comment]
Fixed in https://github.com/huggingface/optimum/pull/701
