### ISSUE TITLE
ORTModelForSeq2SeqLM.generate not working

### ISSUE THREAD

**Issue by hlums** [huggingface/optimum#682]
### System Info

```shell
optimum: optimum @ git+https://github.com/huggingface/optimum.git@e19928316bbf66047085160fb0adaf1a25da3751
Platform: Ubuntu
Python: 3.7.13
```

### Who can help?

@lewtun @michaelbenayoun 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The ORTModelForSeq2SeqLM seems to fall behind the latest GenerationMixin in transformers. 
```
encoder_session, decoder_session, decoder_with_past_session = ORTModelForSeq2SeqLM.load_model(
        encoder_path="./encoder_model_opt_1_q.onnx",
        decoder_path="./decoder_model_opt_1_q.onnx",
        decoder_with_past_path="./decoder_with_past_model_opt_1_q.onnx",
        provider="CUDAExecutionProvider",
        session_options=ort_sess_options
    )
config = PretrainedConfig.from_json_file("./config.json")
ort_model = ORTModelForSeq2SeqLM(
    encoder_session=encoder_session,
    decoder_session=decoder_session,
    decoder_with_past_session=decoder_with_past_session,
    config=config
)
ort_model.generate(**inputs)
```
Traceback (most recent call last):
  File "onnx_test.py", line 94, in <module>
    ort_model.generate(**ort_inputs)
  File "/home/honglu/miniconda3/envs/question_generation/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/honglu/miniconda3/envs/question_generation/lib/python3.7/site-packages/transformers/generation/utils.py", line 1136, in generate
    self._validate_model_class()
  File "/home/honglu/miniconda3/envs/question_generation/lib/python3.7/site-packages/transformers/generation/utils.py", line 945, in _validate_model_class
    if not self.can_generate():
AttributeError: 'ORTModelForSeq2SeqLM' object has no attribute 'can_generate'

### Expected behavior

The ORTModelForSeq2SeqLM.generate method should generate sequence of token ids without error.

**Comment by fxmarty** [comment]
Hi hlums, can you use transformers stable version (not dev)?

**Comment by fxmarty** [comment]
Fixed in https://github.com/huggingface/optimum/pull/651
