### ISSUE TITLE
Accept Numpy input to model

### ISSUE THREAD

**Issue by j-adamczyk** [huggingface/optimum#689]
### Feature request

Models like `ORTModelForImageClassification` should accept Numpy arrays as input. This can be easily done with a type check.

### Motivation

Currently there is no type check e.g. in `ORTModelForImageClassification` and inputs are assumed to be PyTorch tensors. For CPU and GPU without using io bindings they are changed to Numpy arrays anyway:
```
onnx_inputs = {
    "pixel_values": pixel_values.cpu().detach().numpy(),
}
```
This means that if someone already has Numpy arrays, e.g. as the output of a preprocessor, they have to be converted to Pytorch tensors, just to be changed back to Numpy in the `forward()` method.
```
images = preprocessor(imgs)["pixel_values"]
images = np.stack(images)
images = torch.from_numpy(images)  # this should not be required
```

### Your contribution

Yes, but I am new to this library, and this should be very easy to implement to someone already familiar with Optimum.

**Comment by fxmarty** [comment]
Hi @j-adamczyk , sorry for the delay. This addressed in https://github.com/huggingface/optimum/pull/790
