### ISSUE TITLE
xformers support for transformers

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#690]
### Feature request

Could there be a smooth way to support xformers in transformers? I doubt modifying 150 modeling files is an option, but there could be something to do in Optimum.

One downside is that it somewhat overlaps with PyTorch transformer fastpath (aka BetterTransformer). But BetterTransformer currently does not have support training, so xformers may be very valuable.

### Motivation

xformers rocks and is fast + supports training.

### Your contribution

/

**Comment by fxmarty** [comment]
This will probably not happen as PyTorch is upstreaming memory efficient attention in core.

**Comment by IlyasMoutawwakil** [comment]
> This will probably not happen as PyTorch is upstreaming memory efficient attention in core.

An alternative could be to instantiate `nn.TransformerEncoderLayer` in BetterTransformer layers instead of calling `torch._transformer_encoder_layer_fwd`.
