### ISSUE TITLE
GPU tests can't access to AWS

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum#718]
### System Info

```shell
/
```

### Who can help?

@phili

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The GPU tests started failing due to a setup issue: https://github.com/huggingface/optimum/actions/runs/3993809658 while they were going fine three days ago: https://github.com/huggingface/optimum/actions/runs/3965480978

@philschmid Do you know if a token has been changed? Maybe we need to change the secrets or something.

### Expected behavior

/

**Comment by regisss** [comment]
It is now failing because of the recent change to SSO on Github for the HF org. The owner of the token has to allow SSO for this token. Maybe @mfuntowicz ?

**Comment by fxmarty** [comment]
Fixed by @mfuntowicz !
