### ISSUE TITLE
Support Donut in VisionEncoderDecoder ONNX export and inference

### ISSUE THREAD

**Issue by mht-sharma** [huggingface/optimum#743]
### Feature request

Add the Donut model in the `VisionEncoderDecoder` export.

Currently, adding the model directly to `exporters` creates a onnx model with low accuracy. This happens when the model is exported and tested with different batch sizes.

The above issue needs to be fixed to enable export of the model.

### Motivation

Priority model for inference

### Your contribution

Would fix the issue and add the model

**Comment by Kiryuumaru** [comment]
Hi, any updates on this?

**Comment by mht-sharma** [comment]
The export of the Donut model is supported in current version of optimum. Will merge the CPU inference part by EOD

**Comment by Kiryuumaru** [comment]
Will it be possible to convert the model from ONNX to TensorRT?

**Comment by arj7192** [comment]
Hi @mht-sharma 
Are there any updates on donut inference using optimum onnxruntime?
Many thanks 🙏

**Comment by mht-sharma** [comment]
Hi @arj7192 the CPU inference for donut is currently supported in optimum.

**Comment by arj7192** [comment]
Thank you @mht-sharma 
Looking forward to GPU support!

**Comment by mht-sharma** [comment]
Closing and creating new issue for GPU support
