### ISSUE TITLE
Cannot export TrOCR to ONNX with past

### ISSUE THREAD

**Issue by mht-sharma** [huggingface/optimum#744]
### System Info

```shell
- `optimum` version: 1.6.4.dev0
- `transformers` version: 4.26.0
- Platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.17
- Python version: 3.8.15
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.13.1+cu117 (cuda availabe: True)
- Tensorflow version (GPU?): 2.10.1 (cuda availabe: False)
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```bash
python -m optimum.exporters.onnx --model="microsoft/trocr-small-handwritten" --task=vision2seq-lm-with-past model_trocr_base   --for-ort
```

Error:
```bash
ValueError: Exporting past key values is not supported with TrOCR model!
```

### Expected behavior

Exporting TrOCR to ONNX with past should work.

**Comment by fxmarty** [comment]
Hi, this is fixed in https://github.com/huggingface/optimum/pull/1456

**Comment by goodevile** [comment]
I got it with:

`!optimum-cli export onnx --task image-to-text --model microsoft/trocr-small-printed trocr-small-printed_onnx/`

**Comment by CrasCris** [comment]
> I got it with:
> 
> `!optimum-cli export onnx --task image-to-text --model microsoft/trocr-small-printed trocr-small-printed_onnx/`

Thats the Task of TrOCR, i dont find any docs for that
