### ISSUE TITLE
optimum.exporters.onnx: config file is not a valid JSON file

### ISSUE THREAD

**Issue by Eichhof** [huggingface/optimum#770]
### System Info

```shell
Optimum: 1.6.3
Python: 3.10.4
Platform: Windows 10
Cuda: 11.6
```

### Who can help?

@lewtun 
@michaelbenayoun 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I was running `python -m optimum.exporters.onnx --task causal-lm-with-past --atol=1e-4 --for-ort --model pytorch_model.bin gptj_onnx/` to transform GPT-J to ONNX. I'm getting the following error:

`OSError: It looks like the config file at 'pytorch_model.bin' is not a valid JSON file.`

The config.json file (in the same folder as pytorch_model.bin) looks as follows:

```
{
  "_name_or_path": "EleutherAI/gpt-j-6B",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTJForCausalLM"
  ],
  "attn_pdrop": 0.0,
  "bos_token_id": 50256,
  "embd_pdrop": 0.0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gptj",
  "n_embd": 4096,
  "n_head": 16,
  "n_inner": null,
  "n_layer": 28,
  "n_positions": 2048,
  "resid_pdrop": 0.0,
  "rotary": true,
  "rotary_dim": 64,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50,
      "temperature": 1.0
    }
  },
  "tie_word_embeddings": false,
  "tokenizer_class": "GPT2Tokenizer",
  "transformers_version": "4.21.2",
  "use_cache": true,
  "vocab_size": 50400
}
```

I have created the pytorch_model.bin with to_hf_weights.py from https://github.com/kingoflolz/mesh-transformer-jax to convert the weights which I have trained using mesh-transformer-jax on TPU to HuggingFace format.

### Expected behavior

Transformation to ONNX should succeed.

**Comment by michaelbenayoun** [comment]
Hi,

The `--model` parameter expects either a directory with the the model weights (which you seem to have) along with the model config (`config.json`) and the preprocessor files as well, or a model repo from the Hugging Face Hub.

Do you have the required files?
If so you should succeed by putting everything under the same directory.

**Comment by Eichhof** [comment]
It worked.
