### ISSUE TITLE
BetterTransformer support for Marian

### ISSUE THREAD

**Issue by ericbugin** [huggingface/optimum#782]
`The model type marian is not yet supported supported to be used with BetterTransformer.`

Wondering if there is a way to get this working with BetterTransformer. I am trying to get this model translating faster. https://huggingface.co/Helsinki-NLP/opus-mt-zh-en?

**Comment by fxmarty** [comment]
@younesbelkada

**Comment by IlyasMoutawwakil** [comment]
> `The model type marian is not yet supported supported to be used with BetterTransformer.`
> 
> Wondering if there is a way to get this working with BetterTransformer. I am trying to get this model translating faster. https://huggingface.co/Helsinki-NLP/opus-mt-zh-en?

I don't think that's possible for now. One reason is the fact that this architecture uses SiLUActivation which is not currently supported in the pytorch fastpath (only supports relu and gelu).

**Comment by IlyasMoutawwakil** [comment]
@fxmarty yes I'll submit a PR

**Comment by IlyasMoutawwakil** [comment]
@fxmarty support for marian is possible, it's actually the opus-mt variant that specifically uses `SiLUActivation`.
