### ISSUE TITLE
ORTOptimizer support for ORTModelForCausalLM

### ISSUE THREAD

**Issue by cyang49** [huggingface/optimum#785]
### System Info

```shell
optimum[onnxruntime-gpu] 1.6.4 
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I have a script the loads HF CodeGen model and store it in ONNX format. It then loads from local stored model path and encounters an error.

Error message
```
Traceback (most recent call last):
  File "model2ort-minimal.py", line 21, in <module>
    optimizer = ORTOptimizer.from_pretrained(ort_model)
  File "/opt/conda/lib/python3.8/site-packages/optimum/onnxruntime/optimization.py", line 87, in from_pretrained
    onnx_model_path.append(model_or_path.model_path)
AttributeError: 'ORTModelForCausalLM' object has no attribute 'model_path'
```

This script can be used to reproduce it.
```
import time
import onnx
import onnxruntime
from optimum.onnxruntime import ORTModelForCausalLM
from optimum.onnxruntime import ORTOptimizer, AutoOptimizationConfig

model_name = "Salesforce/codegen-350M-multi"
onnx_model_dir = "./models/ort"
cache_dir = "~/.cache/huggingface/transformers/"
use_cache = True
ort_model = ORTModelForCausalLM.from_pretrained(model_name,
                                            cache_dir=cache_dir,
                                            from_transformers=True,
                                            use_cache=use_cache)
ort_model.save_pretrained(onnx_model_dir)   
optimized_model_dir = onnx_model_dir+"_opt"
optimizer = ORTOptimizer.from_pretrained(ort_model)
```

### Expected behavior

Expect the stored onnx model to be loaded without an error

**Comment by fxmarty** [comment]
Thank you, we will be working on it!

**Comment by cyang49** [comment]
My local patch is as the following:
File: optimum/onnxruntime/optimization.py

Add an `elif` for `ORTModelForCausalLM`
```
...
from .modeling_decoder import ORTModelForCausalLM
...
        if isinstance(model_or_path, ORTModel):
            if isinstance(model_or_path, ORTModelForSeq2SeqLM):
                onnx_model_path += [
                    model_or_path.encoder_model_path,
                    model_or_path.decoder_model_path,
                ]   
                # Add the decoder with past key/values if present
                if model_or_path.use_cache:
                    onnx_model_path.append(model_or_path.decoder_with_past_model_path)
            elif isinstance(model_or_path, ORTModelForCausalLM):
                onnx_model_path.append(model_or_path.decoder_model_path)
                if model_or_path.use_cache:
                    onnx_model_path.append(model_or_path.decoder_with_past_model_path)
            else:
                onnx_model_path.append(model_or_path.model_path)
...
```

**Comment by fxmarty** [comment]
Thank you, I did pretty much the same in https://github.com/huggingface/optimum/pull/794 . The PR just adds a few tests on top.

**Comment by cyang49** [comment]
> Hi @cyang49 , #794 has been merged.
> 
> One issue I have yet to investigate:
> 
> * GPT-J with past key values and fp16 conversion fails at inference.
> 
> Note as well that I have not yet tested how much the optimizations help on the speed side, so it is kind of experimental. But at least it provides a decent front end to ONNX Runtime optimizations.

Is the issue similar to this?
```
RuntimeError: Error in execution: Non-zero status code returned while running Transpose node. Name:'Transpose_token_96' Status Message: /onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:83 virtual OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,16,1024,64} != {1,16,1025,64}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.
```

**Comment by fxmarty** [comment]
Which version of Optimum are you using? Is it with GPT-J? Could you share your branch and a script/model to reproduce?

**Comment by cyang49** [comment]
It's `optimum-1.6.4` and the model is `Salesforce/codegen-350M-multi`.

Here is a script to reproduce the problem:

```
import os
import time
import onnx
import onnxruntime
from optimum.onnxruntime import ORTModelForCausalLM
from optimum.onnxruntime import ORTOptimizer, AutoOptimizationConfig
from transformers import AutoTokenizer

model_name = "Salesforce/codegen-350M-multi"
onnx_model_dir = "./models/ort"
cache_dir = "~/.cache/huggingface/transformers/"
use_cache = True

ort_model = ORTModelForCausalLM.from_pretrained(model_name,
                                            cache_dir=cache_dir,
                                            from_transformers=True, 
                                            use_cache=use_cache)

ort_model.save_pretrained(onnx_model_dir)

optimized_model_dir = onnx_model_dir+"_opt"
optimizer = ORTOptimizer.from_pretrained(ort_model)

optimization_config = AutoOptimizationConfig.O4(for_gpu=False, disable_shape_inference=True)
optimizer.optimize(save_dir=optimized_model_dir, optimization_config=optimization_config)

opt_model = ORTModelForCausalLM.from_pretrained(optimized_model_dir,
                                            cache_dir=cache_dir,
                                            use_cache=use_cache,
                                            provider="CUDAExecutionProvider") 


tokenizer = AutoTokenizer.from_pretrained(model_name)
tokens = tokenizer("hello world", return_tensors='pt')
output = opt_model.generate(tokens['input_ids'].to('cuda:0'),
                do_sample=False,
                num_return_sequences=1,
                temperature=0.2,
                max_new_tokens=16,
                top_p=0.95,
                use_cache=use_cache,)
```

Error:
```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Transpose node. Name:'Transpose_token_96' Status Message: /onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:83 virtual OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,16,2,64} != {1,16,3,64}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.
```

**Comment by cyang49** [comment]
This error is likely the same as mentioned in onnxruntime issue 
https://github.com/microsoft/onnxruntime/issues/14582

**Comment by fxmarty** [comment]
Thank you @cyang49 , I can reproduce the issue. Not sure there is much we can do on our end, it looks like an issue either in the ONNX for codegen, or a bug in ONNX Runtime.

So far I disabled the test for codegen due to an other bug in ONNX Runtime I encountered with this architecture: https://github.com/huggingface/optimum/blob/0d948ae48d66b98055302f8363b19628b4ef335b/tests/onnxruntime/test_optimization.py#L331

**Comment by fxmarty** [comment]
@cyang49 Looks to be the same issue: https://github.com/huggingface/optimum/issues/800

**Comment by fxmarty** [comment]
Hi @cyang49 , https://github.com/huggingface/optimum/pull/871 may have fixed your issue. Could you try on optimum main?

I was able to use codegen with ORT fp16 optimization: `optimum-cli export onnx --model hf-internal-testing/tiny-random-CodeGenModel --task causal-lm-with-past --device cuda --optimize O4 codegen_onnx` & then loading into ORTModelForCausalLM.

**Comment by cyang49** [comment]
Hi @fxmarty I tested the optimization quickly and loaded the model. I don't encounter the same error as before.

However, I still need to set `disable_shape_inference=True` for the optimization to be successful.
```
optimization_config = AutoOptimizationConfig.O4(for_gpu=args.for_gpu, disable_shape_inference=True)
```
The shape inference error may be something else and maybe in your environment you don't encounter this. Can you check whether you also disabled shape inference, and if you didn't need to do that, let me know what onnxruntime version it is in your environment?

Thank you so much

**Comment by fxmarty** [comment]
Hi @cyang49 , yes sorry for being unclear, I meant that the issue `Shape mismatch attempting to re-use buffer` should be fixed. The `incomplete shape inference` is a classic and I have no better solution than disabling shape inference for now.

Note that I am for now not sure if it's a good practice or not to pass `disable_shape_inference=True` when using O4 (aka ORT fp32 to fp16 conversion), for reference https://github.com/microsoft/onnxruntime/issues/15063

**Comment by cyang49** [comment]
@fxmarty thanks for the info.
Yes, I've tested the latest code and didn't run into the same runtime error anymore. I think you can close this
