### ISSUE TITLE
Optimum CLI tool: error: invalid choice: 'onnxruntime' (choose from 'export', 'env')

### ISSUE THREAD

**Issue by sanbuphy** [huggingface/optimum#793]
### System Info

```shell
ubuntu 22.04
optimum 1.6.4
onnxruntime 1.14.0
```

### Who can help?

I want to use optimum-cli to optimize my own onnx model.

I refer to this documentation:
https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization#optimizing-a-model-to-be-used-with-optimums-ortoptimizer 

but when i use `optimum-cli onnxruntime optimize --help`  it shows that:
```
usage: optimum-cli <command> [<args>]
Optimum CLI tool: error: invalid choice: 'onnxruntime' (choose from 'export', 'env')
```

I don't see 
```
optimum-cli onnxruntime optimize --help
usage: optimum-cli <command> [<args>] onnxruntime optimize [-h] --onnx_model ONNX_MODEL [-o OUTPUT] (-O1 | -O2 | -O3 | -O4)

options:
  -h, --help            show this help message and exit
  -O1                   Basic general optimizations (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O2                   Basic and extended general optimizations, transformers-specific fusions (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O3                   Same as O2 with Gelu approximation (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O4                   Same as O3 with mixed precision (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -c, --config          `ORTConfig` file to use to optimize the model.

Required arguments:
  --onnx_model ONNX_MODEL
                        Path indicating where the ONNX models to optimize are located.

Optional arguments:
  -o OUTPUT, --output OUTPUT
                        Path indicating the directory where to store generated ONNX model. (defaults to --onnx_model value).
```

Can you tell me the reason?  Thank you very much.

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

optimum-cli onnxruntime optimize --help

### Expected behavior

```
optimum-cli onnxruntime optimize --help
usage: optimum-cli <command> [<args>] onnxruntime optimize [-h] --onnx_model ONNX_MODEL [-o OUTPUT] (-O1 | -O2 | -O3 | -O4)

options:
  -h, --help            show this help message and exit
  -O1                   Basic general optimizations (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O2                   Basic and extended general optimizations, transformers-specific fusions (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O3                   Same as O2 with Gelu approximation (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -O4                   Same as O3 with mixed precision (see: https://huggingface.co/docs/optimum/onnxruntime/usage_guides/optimization for more details).
  -c, --config          `ORTConfig` file to use to optimize the model.

Required arguments:
  --onnx_model ONNX_MODEL
                        Path indicating where the ONNX models to optimize are located.

Optional arguments:
  -o OUTPUT, --output OUTPUT
                        Path indicating the directory where to store generated ONNX model. (defaults to --onnx_model value).
```

**Comment by fxmarty** [comment]
Hi @sanbuphy , you are seeing the `main` documentation, the release one is: https://huggingface.co/docs/optimum/v1.6.3/en/onnxruntime/usage_guides/optimization

We will do a release soon.

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , you are seeing the `main` documentation, the release one is: https://huggingface.co/docs/optimum/v1.6.3/en/onnxruntime/usage_guides/optimization
> 
> We will do a release soon.

Thank you very much.

I want to use optimum to optimize my own bert-like onnx model, but I get an error after reading it with this api
`optimizer = ORTOptimizer.from_pretrained("path/to/model")`
, so I want to use optimum_ctl, but he's gone , sad .

![image](https://user-images.githubusercontent.com/96160062/220075821-7ee3f14d-0b5a-4fa9-a002-cc95b731b8f4.png)
![image](https://user-images.githubusercontent.com/96160062/220075847-0c82fe43-9515-4c22-9e15-d409132c72e8.png)

**Comment by fxmarty** [comment]
@sanbuphy Yes, we expect models coming from https://github.com/huggingface/transformers library, so having a `config.json` is necessary.

Unfortunately, it seems that simbert is not supported in transformers. Optimum is untested for this use case, but there's indeed a case where the optimizer should work for any onnx model, not necessarily coming from transformers.

**Comment by sanbuphy** [comment]
> mers. Optimum is untested for this use case, but there's indeed a case where the optimizer should work for a

Yes, i  get it .
But I think Optimum is just the wrapper of the optimizer of onnxruntime, the mechanism should be common, what optimization does Optimum use in it? I only know that optimization level 2 is used

**Comment by fxmarty** [comment]
Thank you, it is indeed just a wrapper around ONNX Runtime optimization tools. I think that the ORTOptimizer could indeed be used for models outside of transformers. Feel free to open an issue or contribute a PR for it, I keep it in mind as well.

**Comment by sanbuphy** [comment]
> Thank you, it is indeed just a wrapper around ONNX Runtime optimization tools. I think that the ORTOptimizer could indeed be used for models outside of transformers. Feel free to open an issue or contribute a PR for it, I keep it in mind as well.

I will try to modify it and let it be a independent model.
