### ISSUE TITLE
Error when transforming Wav2Vec2ForCTC model to BetterTransformer

### ISSUE THREAD

**Issue by Valterrsj** [huggingface/optimum#795]
### System Info

```shell
I encountered an error when transforming the Wav2Vec2ForCTC model to BetterTransformer. Specifically, the error occurred when using the model "lgris/wav2vec2-large-xlsr-open-brazilian-portuguese-v2" available on Hugging Face.

The error message I received was: "The transformation of the model Wav2Vec2ForCTC to BetterTransformer failed while it should not."

Versions of the libraries used:

Optimum: 1.6.4
Torch: 1.13.1+cu116
Transformer: 4.25.1

The traceback is as follows:

Traceback (most recent call last):
...
File "/home/code/app/asr/wav2vec2_inference.py", line 59, in init
self.model = BetterTransformer.transform(self.model)
File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
return func(*args, **kwds)
File "/opt/conda/lib/python3.9/site-packages/optimum/bettertransformer/transformation.py", line 215, in transform
set_last_layer(model_fast)
File "/opt/conda/lib/python3.9/site-packages/optimum/bettertransformer/transformation.py", line 133, in set_last_layer
raise Exception(
Exception: The transformation of the model Wav2Vec2ForCTC to BetterTransformer failed while it should not. Please fill a bug report or open a PR to support this model at https://github.com/huggingface/optimum/
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import (
    AutoModelForCTC,
    Wav2Vec2Processor,
    Wav2Vec2ProcessorWithLM,
)
from optimum.bettertransformer import BetterTransformer

MODEL_NAME = "lgris/wav2vec2-large-xlsr-open-brazilian-portuguese-v2"
model = AutoModelForCTC.from_pretrained(MODEL_NAME)
better_model = BetterTransformer.transform(model)

### Expected behavior

The code should run without errors and the model model should be loaded and transformed by the BetterTransformer.transform method.

**Comment by fxmarty** [comment]
@younesbelkada

**Comment by younesbelkada** [comment]
HI @Valterrsj 
Thanks for the issue, indeed there is a variant of `Wav2Vec2` that was not supported. #803 should add the support of this model

**Comment by zZwufeng** [comment]
> HI @Valterrsj Thanks for the issue, indeed there is a variant of `Wav2Vec2` that was not supported. #803 should add the support of this model

Hi, this bug seems to still exist. I run again the script above and still got the error message. 

**Reproduction**
from transformers import (
AutoModelForCTC,
Wav2Vec2Processor,
Wav2Vec2ProcessorWithLM,
)
from optimum.bettertransformer import BetterTransformer

MODEL_NAME = "lgris/wav2vec2-large-xlsr-open-brazilian-portuguese-v2"
model = AutoModelForCTC.from_pretrained(MODEL_NAME)
better_model = BetterTransformer.transform(model)

**Comment by younesbelkada** [comment]
Hello @zZwufeng 

Just to confirm, are you using the `main` branch of `optimum` ?
```
pip install git+https://github.com/huggingface/optimum.git
```

**Comment by zZwufeng** [comment]
@younesbelkada 

I install optimum using:

`pip install optimum`

and the version is:
```
Name: optimum
Version: 1.6.4
```

**Comment by younesbelkada** [comment]
@zZwufeng 
Please use the latest changes of `optimum` library by installing from source as the changes have not been published yet
```
pip uninstall optimum
pip install git+https://github.com/huggingface/optimum.git
```

**Comment by zZwufeng** [comment]
@younesbelkada 
Ok, i'll try, thanks！😊

**Comment by younesbelkada** [comment]
Thanks @zZwufeng 💯 !
