### ISSUE TITLE
Stale comment in the Optimum docs

### ISSUE THREAD

**Issue by nickchomey** [huggingface/optimum#804]
This line is now stale. It points to an ONNX bug that was closed a couple weeks ago. 
https://github.com/huggingface/optimum/blob/d2436cf386dd32a8d9bbad97e577502248914398/docs/source/onnxruntime/usage_guides/gpu.mdx?plain=1#L397

There doesn't seem to be a way for me to submit a PR to you guys, so I'm creating this issue.

**Comment by fxmarty** [comment]
Hi @nickchomey , thank you for the hint! Indeed this seem to have been fixed. I'll update the documentation ASAP.

**Comment by fxmarty** [comment]
Hi @nickchomey the documentation was slightly overhauled with a better example in https://github.com/huggingface/optimum/pull/812. Through benchmarks are still missing.
