### ISSUE TITLE
AttributeError: 'Box' object has no attribute 'use_multi_head_attention' when trying to optimize ONNX model

### ISSUE THREAD

**Issue by shahafpalomo** [huggingface/optimum#811]
### System Info

```shell
python-3.8.16
optimum 1.5
onnxruntime-1.14.0
```

### Who can help?

@JingyaHuang
@echarlaix

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

when trying to optimize ONNX model (after conversion from all-MiniLM-L6-v2 model) following https://www.philschmid.de/optimize-sentence-transformers this blog post to accelerate embeddings
with the following code:

from optimum.onnxruntime import ORTModelForFeatureExtraction
from transformers import AutoTokenizer
from pathlib import Path
import os

base_path = "C:/Users/spalomo/OneDrive - Verint Systems Ltd/Desktop/calls/"
model_name = 'all-MiniLM-L6-v2'
model_path = os.path.join(base_path,'models',model_name)
model_id="sentence-transformers/all-MiniLM-L6-v2"
onnx_path = Path(base_path, "models", "onnx")

# load vanilla transformers and convert to onnx
model = ORTModelForFeatureExtraction.from_pretrained(model_id, from_transformers=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)

# save onnx checkpoint and tokenizer
model.save_pretrained(onnx_path)
tokenizer.save_pretrained(onnx_path)

im getting the following exception:

Traceback (most recent call last):
  File "C:\Users\spalomo\AppData\Local\miniconda3\envs\pytorch_env\modelOptimizer.py", line 14, in <module>
    optimizer.optimize(save_dir=onnx_path, optimization_config=optimization_config)
mize
    optimization_options = optimization_config.create_fusion_options(model_type)
  File "C:\Users\spalomo\AppData\Local\miniconda3\envs\pytorch_env\lib\site-packages\optimum\onnxruntime\configuration.py", line 745, in create_fusion_options
    return FusionOptions.parse(args)
  File "C:\Users\spalomo\AppData\Local\miniconda3\envs\pytorch_env\lib\site-packages\onnxruntime\transformers\fusion_options.py", line 76, in parse
    if args.use_multi_head_attention:
AttributeError: 'Box' object has no attribute 'use_multi_head_attention'

after reviewing the code in this github (optimum), looks like there is a problem with the input parameters.

### Expected behavior

i expected that the code will run and optimize my model.

**Comment by fxmarty** [comment]
Hi @shahafpalomo , could you try with optimum==1.6.4? This should have been fixed in https://github.com/huggingface/optimum/pull/772

**Comment by shahafpalomo** [comment]
@fxmarty thanks for your comment. will try and update here with the results.

**Comment by shahafpalomo** [comment]
@fxmarty it worked. thank you for your assistance. much apricated!
