### ISSUE TITLE
When I import BetterTransfomer, It Return Syntax Error

### ISSUE THREAD

**Issue by ricoyudog** [huggingface/optimum#908]
### System Info

```shell
optimum = 1.7.1
Python Version == 3.7.11
```

### Who can help?

Thank you everyone, when I try to import the bettertransformer, It return syntax error.

`from optimum.bettertransformer import BetterTransformer`
Error
`Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_1227/438332947.py", line 1, in <module>
    from optimum.bettertransformer import BetterTransformer

  File "/home/jovyan/.local/lib/python3.7/site-packages/optimum/bettertransformer/__init__.py", line 15, in <module>
    from .transformation import BetterTransformer

  File "/home/jovyan/.local/lib/python3.7/site-packages/optimum/bettertransformer/transformation.py", line 30
    **def raise_save_or_push_incompatible(dummy, /, *_, **__):**
                                               ^
SyntaxError: invalid syntax`

Please help to solve this problem, Thank you very much!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. pip install --user optimum[onnxruntime]
2. from optimum.bettertransformer import BetterTransformer`

### Expected behavior

I expected to successfully load the BetterTransformer.

**Comment by fxmarty** [comment]
This is due to the syntax `raise_save_or_push_incompatible(dummy, /, *_, __)` that is valid only from python 3.8 onwards.

This was fixed in https://github.com/huggingface/optimum/pull/881 and will be included in a patck release this week. As a general recommendation, I would advise to use python >=3.8 though, as python 3.7 end of life comes soon: https://devguide.python.org/versions/
