### ISSUE TITLE
Regression: merge_decoders fails in 1.7.3

### ISSUE THREAD

**Issue by claeyzre** [huggingface/optimum#921]
### System Info

```shell
Python Version: 3.8
Optimum: 1.7.3
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

In Optimum 1.7.3 this fails:
```
from optimum.onnxruntime import ORTModelForSeq2SeqLM
from optimum.onnx.graph_transformations import merge_decoders
model = ORTModelForSeq2SeqLM.from_pretrained("t5-small", from_transformers=True)

merge_decoders(model.decoder_model_path, model.decoder_with_path_model_path)
```

with the error:
`ValueError: Two model protos need to have the same outputs. But one has 26 outputs while the other has 14 outputs.`

In Optimum 1.7.1 this was not the case.

Notably because when merging the two decoders, the outputs of the two Onnx graph should be exactly the same. In 1.7.1 there was no problem but [this change](https://github.com/huggingface/optimum/commit/69b4285ecd5044b5384a5f9ea012d73d260811e1#diff-6fb560fd316f38fac94c55202bc2ada7c167bbe0971850d3dcbf1298694122aeR718) have made the two graphs outputs diverge and thus impossible to merge. I understand why this has been done but I was wondering if this behavior could be rectified w.r.t optimum's roadmap (whether you want to keep the `merge_decoders` in your codebase in the future) or if there is a new correct way of calling this method without

Thanks

### Expected behavior

The merge should happen correctly as in 1.7.1, this might be done by "faking" constant output nodes for the decoder (with use_past to False) at the time of merging ?

**Comment by fxmarty** [comment]
Hi @claeyzre , thank you, yes I edited the release note to mention this breaking change: https://github.com/huggingface/optimum/releases/tag/v1.7.3

I think the solution would be to have dummy inputs/outputs, as the two `If` branches do not need to have inputs/outputs of the same shape: https://github.com/onnx/onnx/blob/main/docs/Operators.md#If:

> Values that are live-out to the enclosing scope. The return values in the `then_branch` and `else_branch` must be of the same data type. The `then_branch` and `else_branch` may produce tensors with the same element type and different shapes.

It is definitely something I want to work on.

To be honest, `merge_decoders` should probably be private as it is not tested in our CI. What is extensively tested in the CI is the merging of decoder for decoder-only models.

**Comment by xenova** [comment]
> By the way @xenova this could be an issue to you as well.

Hmmm, I did once have that issue, but I re-ran the command and it worked 👀  Didn't question it too much after that... 🤣

**Comment by fxmarty** [comment]
Hi @claeyzre @xenova, this should be fixed in https://github.com/huggingface/optimum/pull/924. I'll probably do a patch release once https://github.com/huggingface/optimum/pull/926 is merged + we include the support in ORTModel as well.

**Comment by xenova** [comment]
> Hi @claeyzre @xenova, this should be fixed in https://github.com/huggingface/optimum/pull/924. I'll probably do a patch release once https://github.com/huggingface/optimum/pull/926 is merged + we include the support in ORTModel as well.

Sweet! I'll test it out now 💪

**Comment by fxmarty** [comment]
Beware that it has some tests (https://github.com/huggingface/optimum/blob/3f58fef3e9b47a9f8050d689a60d775e2b4d44ca/tests/onnx/test_onnx_graph_transformations.py#L73-L75), but it's very rudimentary for now 😄 https://github.com/huggingface/optimum/pull/926 will bring more tests)

**Comment by fxmarty** [comment]
Beware that it has some tests (https://github.com/huggingface/optimum/blob/3f58fef3e9b47a9f8050d689a60d775e2b4d44ca/tests/onnx/test_onnx_graph_transformations.py#L73-L75), but it's very rudimentary for now 😄 https://github.com/huggingface/optimum/pull/926 will bring more tests)

**Comment by xenova** [comment]
Everything seems to be working! 🥳
