### ISSUE TITLE
disable or remove non-implemented `entry_points`

### ISSUE THREAD

**Issue by sugatoray** [huggingface/optimum#95]
The code for the following three `entry_points` do not exist currently. Please either disable them by commenting them out, until implemented, or remove them entirely.

- `optimum.onnxruntime.convert:main`
- `optimum.onnxruntime.optimize_model:main`
- `optimum.onnxruntime.convert_and_optimize:main`

https://github.com/huggingface/optimum/blob/1ac1f767815f1583a6228b8011e7eef54dd9cf4b/setup.py#L68-L73

Current repo structure:
![image](https://user-images.githubusercontent.com/10201242/158044540-c8389462-0900-446a-a4ac-7fae80bd27bc.png)

**Comment by sugatoray** [comment]
cc: @echarlaix @mfuntowicz

**Comment by sugatoray** [comment]
I was working on adding `optimum` to conda-forge channel. That's when I realized the non-existent `entry_points` are making the build fail for conda-forge packaging.

- https://github.com/conda-forge/staged-recipes/pull/18300

**Comment by echarlaix** [comment]
Hi @sugatoray,
Thank you for opening this issue, the three entry points were removed accordingly.

**Comment by sugatoray** [comment]
@echarlaix Please let me know once you push a new release. The updated version is needed on PyPI to build the conda-forge package .

**Comment by sugatoray** [comment]
@echarlaix Thank you, for the update. The delay presented an opportunity for me to create the conda-forge recipe with a git-patch as a temporary fix. It was fun learning this alternative.

**Comment by mfuntowicz** [comment]
Can we close this one @echarlaix ?

**Comment by echarlaix** [comment]
Very happy to hear that @sugatoray !
