### ISSUE TITLE
Adding newer models to Optimum (bloom, alpaca)

### ISSUE THREAD

**Issue by AbhayGoyal** [huggingface/optimum#956]
### Feature request

Hi,
I just wanted to know if you could add Bloom and Alpaca for better transformers

### Motivation

We need to be able to see how the big models run on smaller systems

### Your contribution

I could help in making this happen but I do not have a basic understanding of optimum yet,

**Comment by ingo-m** [comment]
Bloom models are supported (right?) but do not work as expected: https://github.com/huggingface/optimum/issues/1171

**Comment by fxmarty** [comment]
Hi @vincentmin, @AbhayGoyal Bloom support with SDPA was added in https://github.com/huggingface/optimum/pull/1221. Alpaca is based on Llama so should be working already.

Feel free to open a new issue if you encounter any problem!
