### ISSUE TITLE
Benchmark tool for ONNX models

### ISSUE THREAD

**Issue by jplu** [huggingface/optimum#966]
### Feature request

Hello!

I think a script to benchmark ONNX Models in order to be able to evaluate their performance in terms of memory size / inference speed would be a nice to have. With such a script one will be able to properly see the impact to deploy a model with such or such ORT configuration.

Having such output for example:
```
===================       INFERENCE - SPEED - RESULT       ====================
--------------------------------------------------------------------------------
          Model Name             Batch Size     Seq Length     Time in s
--------------------------------------------------------------------------------
model                                8               8             0.027
model                                8               32            0.071
model                                8              128            0.253
model                                8              512            1.436
--------------------------------------------------------------------------------

====================      INFERENCE - MEMORY - RESULT       ====================
--------------------------------------------------------------------------------
          Model Name             Batch Size     Seq Length    Memory in MB
--------------------------------------------------------------------------------
model                                8               8              1252
model                                8               32             1281
model                                8              128             1319
model                                8              512             1515
--------------------------------------------------------------------------------

====================        ENVIRONMENT INFORMATION         ====================
-optimum_version: 1.7.3
- framework: ORT
- framework_version: 1.14.0
- python_version: 3.9.5
- system: Linux Ubuntu 22.10
- cpu: x86_64
- architecture: 64bit
- date: 2023-04-11
- time: 14:39:37.797685
- num_threads_available: 12
- machine_cpu_ram_mb: 32GB
- machine_gpu_ram_mb: 6GB
- model_cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
- model_gpu: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
- use_cpu: True
- use_gpu: False
- optimization_option: 3
```

### Motivation

This kind of script would be very helpful to take a decision on choosing a model not only depending on the accuracy results (or others kind of metric) but also on the amount of memory a model takes and its inference speed.

### Your contribution

I will be happy to help if this feature sounds interesting.

**Comment by fxmarty** [comment]
Agreed, this would be very useful. Feel free to submit a PR if you'd like to work on it!

As a first step, I would suggest to add a script like this in https://github.com/huggingface/optimum/tree/main/tests/benchmark (similar to what has been done for bettertransformer).

Options to pass could be:
* `model_name_or_path` (expecting say either an already exported/optimized/quantized model or a PT model exported on the fly maybe)
* `provider`,
* `use_cache` (specific to decoders),
* `use_io_binding` (specific to CUDA EP),
* `sequence_length` (specific to text, audio, maybe optional),
* `generation_sequence_length` (specific to decoders, maybe optional), set by `min_new_tokens`, `max_new_tokens`
* `batch_size`
* `num_threads` (specific to CPU EP)
* etc

What do you think? As a next step, I think it could be great to expose this kind of script in e.g. `optimum-cli onnxruntime benchmark`, `optimum-cli bettertransformer benchmark`.

**Comment by jplu** [comment]
Okay! I will think about it. Maybe at first I will do it for simple encoder models and then extend it to more complex ones with decoder and encoder/decoder.

I had the same set of options in mind :+1: Maybe having `model_name_or_path` to be able to handle a set of models would be nice, so at the end we have a tab of comparisons.

The next thing I thought (to do at the late state) would be to export the results of the benchmark in Markdown with an option. Do you think this would be useful?

Thanks for the benchmark scripts for BetterTransformers this is a good set of example and seems very helpful and a good starting point.

To have a benchmark CLI integrated would be a neat feature, I love it!!

**Comment by fxmarty** [comment]
Yes, having the output as csv/markdown sounds good!

**Comment by regisss** [comment]
@jplu Take a look at Optimum Benchmark, it should enable you to do this kind of benchmark easily: https://github.com/huggingface/optimum-benchmark

cc @IlyasMoutawwakil

**Comment by jplu** [comment]
Oh it is awesome!! Thanks a lot for sharing I did not find enough time to take care of that, sorry :-( 

I definitely take a look!
